### PR TITLE
Added README.md file in pulumi/sdk/python

### LINKED ISSUE #10080: python sdk missing README.md
### What happened?

https://github.com/pulumi/pulumi/blob/1d0f50581f9e5c0233b4e3ae291806cf2cd4620a/sdk/README.md says to check the README.md for python and there is no README.md

### Steps to reproduce

go to https://github.com/pulumi/pulumi/blob/1d0f50581f9e5c0233b4e3ae291806cf2cd4620a/sdk/README.md and click the link to python

### Expected Behavior

README.md exists

### Actual Behavior

doesn't exist

### Versions used

v3.35.3

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by vaibhavkoshti7**
# Description

Added README.md file for python sdk which was missing earlier . I reffered documentation given in pulumi website to create this file.

Fixes #10080

### CODE REVIEW

**Review by justinvp — COMMENTED** [review]
Note that we currently copy over and use the README.md from the root of the repository when building the package. If we're adding a dedicated `README.md` just for Python, we'll need to delete that from the `Makefile` so we don't overwrite it when building.

https://github.com/pulumi/pulumi/blob/449307d4d20f386bcc9df923ebc4ef209d09ff50/sdk/python/Makefile#L38

**Comment by vaibhavkoshti7** [comment]
@justinvp can you please tell me what exactly is to be done now. Can we try renaming to solve this issue. If not what would be the further step. I really want to solve this issue as this is my first open source contribution. Thankyou.

**Review by justinvp — APPROVED** [review]
Apologies for the delay, @vaibhavkoshti7. This looks good to me. On second look, I don't think we need to do anything w.r.t. copying the repo's README for the package. We can continue to do that for now.

**Comment by justinvp** [comment]
bors merge

**Pull request merged**
