### PR TITLE
update package details anchors

### PR DESCRIPTION
**Pull request by sean1588**
fixes: https://github.com/pulumi/registry/issues/1819

OK taking this for round 2. The first [PR](https://github.com/pulumi/pulumi/pull/11861) to make this change I ended up reverting because there were some pages (the function pages and module pages) still being generated with empty href tags. 

I have addressed this and updated the change to define the DisplayName and RepositoryName props on the `packageDetails` struct for the individual module pages and function pages. This updates the repository anchor in the Package Details section of the api docs pages. I updated it to display `<package name> repository` for the anchor text in place of the url that was previously shown there. 

image

So now this will show the following on the following pages:
1. the root index package pages
2. the module pages
3. the resource pages
4. the function pages

### CODE REVIEW

**Review by RobbieMcKinstry — APPROVED** [review]
The file count was misleading. This was easy to review!

**Comment by sean1588** [comment]
haha yeah most of the diff is the newly generated test data. thanks @RobbieMcKinstry

**Comment by sean1588** [comment]
bors try

**Pull request merged**
