### PR TITLE
deps: Upgrade google.golang.org/{genproto, grpc}

### PR DESCRIPTION
**Pull request by abhinav**
Updates to the latest versions of
google.golang.org/genproto and google.golang.org/grpc
in all submodules in the repository.

This is necessary because in a recent change,
genproto split out some of its subpackages into independent submodules.
(https://github.com/googleapis/go-genproto/issues/1015)

As a result of this, some users may see the error:

```
google.golang.org/genproto/googleapis/rpc/status: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/status in multiple modules:
    google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1 (/home/runner/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230410155749-daa745c078e1/googleapis/rpc/status)
    google.golang.org/genproto/googleapis/rpc v0.0.0-20230725213213-b022f6e96895
```

Because pu/pu is using 20230410155749,
which has googleapis/rpc as a subpackage,
but another dependency references the independent submodule (20230725213213),
so the system doesn't know which module to use for the import path,
google.golang.org/genproto/googleapis/rpc/status.

This is a problem for codegen tests and ProgramTest-based tests
for Pulumi Go programs that do not have a go.mod in the test directory.
This issue was encountered by @thomas11 while attempting to upgrade
dependencies in pulumi-docker (pulumi/pulumi-docker#700).

The grpc upgrade is necessary because the current version of grpc
also pulls the outdated version of genproto.

### CODE REVIEW

**Review by thomas11 — APPROVED** [review]

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
Something is off about those failures. These tests all pass locally for me.

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13593** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/13593" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/13593?utm_source=stack-comment).

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
The failures suggest that this is still broken:

```
        internal-dependencies-go/example imports
        	github.com/pulumi/pulumi/sdk/v3/go/pulumi imports
        	github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin imports
        	google.golang.org/grpc/status imports
        	google.golang.org/genproto/googleapis/rpc/status: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/status in multiple modules:
        	google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1 (/home/runner/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230410155749-daa745c078e1/googleapis/rpc/status)
        	google.golang.org/genproto/googleapis/rpc v0.0.0-20230706204954-ccb25ca9f130 (/home/runner/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20230706204954-ccb25ca9f130/status)
        internal-dependencies-go/example imports
        	github.com/pulumi/pulumi/sdk/v3/go/pulumi imports
        	github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin imports
        	google.golang.org/grpc/codes tested by
        	google.golang.org/grpc/codes.test imports
        	google.golang.org/genproto/googleapis/rpc/code: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/code in multiple modules:
        	google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1 (/home/runner/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230410155749-daa745c078e1/googleapis/rpc/code)
        	google.golang.org/genproto/googleapis/rpc v0.0.0-20230706204954-ccb25ca9f130 (/home/runner/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20230706204954-ccb25ca9f130/code)
        internal-dependencies-go/example imports
        	github.com/pulumi/pulumi/sdk/v3/go/pulumi imports
        	github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin imports
        	google.golang.org/grpc/status tested by
        	google.golang.org/grpc/status.test imports
        	google.golang.org/genproto/googleapis/rpc/errdetails: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/errdetails in multiple modules:
        	google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1 (/home/runner/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230410155749-daa745c078e1/googleapis/rpc/errdetails)
        	google.golang.org/genproto/googleapis/rpc v0.0.0-20230706204954-ccb25ca9f130 (/home/runner/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20230706204954-ccb25ca9f130/errdetails)
```

The tests passed locally when I tried them last. Will dig in more later. Converting to Draft for now.

**Comment by abhinav** [comment]
bors try

**Comment by abhinav** [comment]
I'm really confused. CI fails consistently. The test runs fine on Linux:

```
=== RUN   TestGeneratePackage
=== PAUSE TestGeneratePackage
=== CONT  TestGeneratePackage
=== RUN   TestGeneratePackage/internal-dependencies-go
=== PAUSE TestGeneratePackage/internal-dependencies-go
=== CONT  TestGeneratePackage/internal-dependencies-go
    sdk_driver.go:457: Emit Go internal dependencies
=== RUN   TestGeneratePackage/internal-dependencies-go/go/compile
    gen_test.go:110: Found an existing go.mod, leaving as is
    command.go:34: **** Invoke '/usr/lib/go/bin/go mod tidy' in '/Users/abg/src/pulumi/pulumi/pkg/codegen/testing/test/testdata/internal-dependencies-go/go'
    command.go:106: Command completed without output
    command.go:34: **** Invoke '/usr/lib/go/bin/go build -v all' in '/Users/abg/src/pulumi/pulumi/pkg/codegen/testing/test/testdata/internal-dependencies-go/go'
    command.go:106: Command completed without output
=== RUN   TestGeneratePackage/internal-dependencies-go/go/test
    command.go:34: **** Invoke '/usr/lib/go/bin/go test internal-dependencies-go/...' in '/Users/abg/src/pulumi/pulumi/pkg/codegen/testing/test/testdata/internal-dependencies-go/go'
    command.go:106: Command completed without output
--- PASS: TestGeneratePackage (0.00s)
    --- PASS: TestGeneratePackage/internal-dependencies-go (4.09s)
        --- PASS: TestGeneratePackage/internal-dependencies-go/go/compile (3.43s)
        --- PASS: TestGeneratePackage/internal-dependencies-go/go/test (0.65s)
PASS
ok      github.com/pulumi/pulumi/pkg/v3/codegen/go      4.125s
```

**Comment by abhinav** [comment]
Okay, so the local checkout had the generated go.mod files sitting around, which is why it's been passing locally

**Comment by abhinav** [comment]
Okay, so the old version of grpc was pulling in the old version of genproto, which was causing that issue for tests. Upgrading that too.

**Comment by abhinav** [comment]
bors try

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
bors try

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
