### PR TITLE
Helper method to log an exception in .NET

### PR DESCRIPTION
**Pull request by mikhailshilkov**
A tiny convenience method.

@CyrusNajmabadi What does `ephemeral` mean in the context of errors?

### CODE REVIEW

**Comment by lukehoban** [comment]
@mikhailshilkov whats a standard use case for this?  Why can’t you just call Error with the toString’d exception yourself?  And why is it common to even want to do this instead of letting the exception bubble up and fail the deployment?

**Comment by mikhailshilkov** [comment]
@lukehoban I *think* this whole `Log` class is intended for providers to log errors/warnings, e.g. the docker provider logs errors from the docker CLI output. If a provider gets an exception, they could call the new helper method directly.
I'm used to have a logger with a helper method to log exceptions (e.g. [LogError(ILogger, Exception, String, Object[]) ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-3.0) but here it seems to be of low value.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi What does ephemeral mean in the context of errors?

'ephemeral' means "only shown for progress while the console tree is updating.  will not be shown at the end in the final list of diagnostics".

It's good for things like showing what docker is doing while it's running.  It shouldn't be used for actual errors we need the user to see and address.

**Comment by CyrusNajmabadi** [comment]
I'm personally fine with this.  It seems to be pretty common in .net libs to have this pattern.   It also gives us more information that we can use in teh future.  i.e. if we want to print the exception in a better way.

**Comment by mikhailshilkov** [comment]
> It's good for things like showing what docker is doing while it's running. It shouldn't be used for actual errors we need the user to see and address.

Should we actually exclude this parameter from the errors then?

**Pull request merged**
