### PR TITLE
Revert "Warn about ambient plugins loaded from $PATH"

### LINKED ISSUE #13656: Pulumi 3.77.0 generates incorrect warnings about officialy installed Homebrew plugins
On 3.77.0 I'm seeing this warning when using normal Homebrew pulumi.

```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-aws-cdk-fargate-luke-dev):
    warning: using pulumi-language-nodejs from $PATH at /opt/homebrew/bin/pulumi-language-nodejs
    warning: using pulumi-language-nodejs from $PATH at /opt/homebrew/bin/pulumi-language-nodejs
```

That is from the officially installed location for my pulumi so not sure why it is warning (and twice?).

```
% which pulumi
/opt/homebrew/bin/pulumi
```

It seems our warnings are too aggressive here?

### PR DESCRIPTION
**Pull request by dixler**
Reverts pulumi/pulumi#13607

Fixes #13656

### CODE REVIEW

**Review by lukehoban — APPROVED** [review]

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors retry

**Comment by dixler** [comment]
bors retry

**Comment by dixler** [comment]
bors cancel

**Comment by dixler** [comment]
bors retry

**Comment by dixler** [comment]
bors retry

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
@Frassle we reverted the PR due to the noisy warnings on MacOS in case you want to revive it.

**Pull request merged**
