### PR TITLE
feat: sign pulumi binaries with cosign

### PR DESCRIPTION
**Pull request by dirien**
# Description

This PR adds cosign to the build process of the Pulumi binaries. I changed the pipeline so cosign can sign without keys by authenticating with OIDC. GitHub supports this.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by AaronFriel — APPROVED** [review]
bors merge

**Comment by dirien** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors retry

**Comment by AaronFriel** [comment]
bors retry

**Comment by AaronFriel** [comment]
bors retry

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Pull request merged**
