### PR TITLE
chore: bumps python grpcio versions in dockerfile

### LINKED ISSUE #9697: Update protoc to a new version
As part of https://github.com/pulumi/pulumi/issues/9694 we had to pin pythons protobuf library to not use version 4 or higher.

I looked at updating things to generate protobuf code that version 4 would be happy with, but it turned out to be involved due to us being on an a very old version of protoc and both Go and Nodejs have also changed behavior and options over time.

This ticket is to update all our SDKs to use and generate from up-to-date versions of protoc and protobuf.

### PR DESCRIPTION
**Pull request by kpitzen**
# Description

Fixes #9697 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by RobbieMcKinstry — APPROVED** [review]

**Comment by kpitzen** [comment]
bors merge

**Comment by kpitzen** [comment]
bors retry

**Comment by kpitzen** [comment]
bors retry

**Comment by kpitzen** [comment]
bors retry

**Pull request merged**
