### PR TITLE
Revert package.json lookup fix.

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
# Description

Fixes https://github.com/pulumi/pulumi/issues/12945

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by justinvp — APPROVED** [review]

**Review by abhinav — APPROVED** [review]
😢

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
Oops. @RobbieMcKinstry, mind squashing the commits?

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
