### PR TITLE
Enable ESModule interoperability

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
# Description

This PR enables ESModule interop for the NodeJS SDK. By enabling interop, we should in theory remove subtle bugs from Pulumi programs that assume our libraries are interopable. In practice, only a few modules weren't already interoperable. Nevertheless, enabling this compiler flag will require future code to be compatible with ESModules, potentially eliminating future bugs.

Fixes https://github.com/pulumi/pulumi/issues/10621

This PR is required for bundling the NodeJS runtime (https://github.com/pulumi/pulumi/issues/10210).

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]
This looks good! I don't think this can break users in any way,  and changes look legit.

**Comment by RobbieMcKinstry** [comment]
This task is failing consistently (I reran a couple times). It looks like a typo though (capital L instead of lowercase L?)

**Comment by t0yv0** [comment]
Rebase on `master`?

**Comment by RobbieMcKinstry** [comment]
The error is caused by a missing enums import in codegen test.

Screen Shot 2022-09-06 at 7 18 01 PM

**Comment by t0yv0** [comment]
Can you link to the CI failure? I'm not seeing this. I see sxs test failure, which is plausibly affected by node SDK changes.

https://github.com/pulumi/pulumi/runs/8217396681?check_suite_focus=true#step:33:1150

**Comment by t0yv0** [comment]
Another rebase here? Master builds are succeeding so we either have a regression in this PR or something really weird going on.

**Comment by RobbieMcKinstry** [comment]
I finally got around to digging into this. The tests that are failing are... very brittle!
They hardcode a compiled `util.js` files from this repo, and assert that we can capture the JS code in a closure.

As an example of a failing test:
1. This repo defines `util.ts` which is used as part of the automation API.
2. `util.ts` is compiled to `util.js`
3. There's a test in `tests/runtime/tsClosureCases.ts` that hardcodes the value of `util.js` from a point in time into the test and matches against it.
4. Because this PR changes the contents of `util.ts`, the resulting `util.js` is changed, which fails the test.

**Comment by t0yv0** [comment]
Sounds like we can accept the new version of utils.js without making the test any weaker then. Or any other workaround.

**Comment by RobbieMcKinstry** [comment]
@t0yv0 ready for re-review. I had to disable one test because the diff had grown by well over 12,000 characters... it's just not useful to track how `typescript.parse()` compiles into javascript...

**Review by t0yv0 — APPROVED** [review]

**Pull request merged**
