### PR TITLE
Consistently disable HTML escaping in JSON output

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Fixes https://github.com/pulumi/pulumi/issues/10439

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
ah of course this horribly breaks config, will need to be a bit more targeted about what is or isn't indented.

**Comment by Frassle** [comment]
ah this changed new line behaviour as well... I _think_ that's ok and we can just change the tests but will double check.

**Comment by Frassle** [comment]
Welp, this is fun.
`json.Marshal` doesn't give any control over the escapeHTML option.
`json.NewEncoder().Encode` doesn't give any control over it writing out a new line character after every `Encode` call.

Go has the most annoying design decisions.

**Review by Zaid-Ajaj — APPROVED** [review]
Nice one!

**Pull request merged**
