### PR TITLE
Add ResourceOutput type to Go SDK

### PR DESCRIPTION
**Pull request by lblackstone**

### CODE REVIEW

**Comment by lblackstone** [comment]
I'm not sure if I'm putting this type in the right place, and I assume I need to call `RegisterOutputType` somewhere.

**Comment by pgavlin** [comment]
> I'm not sure if I'm putting this type in the right place, and I assume I need to call RegisterOutputType somewhere.

I would put this in https://github.com/pulumi/pulumi/blob/master/sdk/go/pulumi/types.go. The `RegisterOutputType` call can go in an `init` function in that file.

**Comment by pgavlin** [comment]
We'll probably want to treat this as a codegen'd builtin in due time, but hand-rolling this is fine for now.

**Comment by lblackstone** [comment]
@pgavlin Ok to merge?

**Pull request merged**
