### PR TITLE
WIP: Simple `EnumerablePromise` model

### PR DESCRIPTION
**Pull request by hausdorff**
NOTE: This PR contains #2630, which it depends on. You probably want to start by looking at the new TS tests to get a flavor for what's happening.

This WIP PR shows how we're starting to think about `list`-style queries in Pulumi.

Unfortunately, the state of the LINQ-style query libraries in the JS ecosystem is quite bad. Particularly for our use case:

* These libraries tend to either diverge from the "canonical" `Enumerable` model in ways that are subtle, surprising, or bad
* None of these libraries play well with `Promise<T>`, which is a big deal in JS because concurrency can't be "hidden" in the way it can with C#.
* The mature model in this space that _does_ deal with `Promise<T>` and has a reasonable enumeration model is rxjs. But it actually an `Observable` model, which provides a fully stream query algebra. This _dramatically_ increases the complexity writing queries in a way that is probably unacceptable for many of the comparatively "boring" use cases we have in mind.
* Less critically, rxjs also uses the `pipe` API instead of methods, which diverges quite a bit from the rest of the Pulumi API.

To this end, we present a very simple `EnumerablePromise<T>` API, which is essentially a `Promise<T[]>`, but with some query primitives hanging off of it. For example:

```typescript
// Take the first 5 elements of an infinite range. `EnumerablePromise` takes `Promise`s,
// but also has a couple handy primitives building queries out of ranges, arrays, etc.
const xs = await EnumerablePromise.range(0)
    .take(5)
    .toArray(); // Converts `EnumerablePromise<T>` -> `Promise<T[]>`

// Add 1 to every element in an array.
const xs = await EnumerablePromise.from([1, 2, 3, 4])
    .map(x => x + 1)
    .toArray();

// Find Kubernetes Service objects in the statefile. (There will be more sugar around this soon.)
const svcs = await EnumerablePromise.from(getResourceOutputs())
    .filter(k8s.core.v1.isService)
    .toArray()
```

This PR includes a bunch of tests, but I'll be coming back and rounding off edges, making sure the API is what we want, _etc_.

### CODE REVIEW

**Comment by hausdorff** [comment]
cc @joeduffy @lukehoban

**Comment by lukehoban** [comment]
@hausdorff Can you remind me why we need this?  Is it just because `invoke` is async, and so we can't just return a `T[]` and must return  a `Promise<T[]>`?  For the use cases we have in mind, is it really necessary to be async all the way down (vs. just a single await to resolve the promise, and then handling plain old arrays)?  

It would be useful to see this connected through to the directly user-callable side to ensure this is really the right way to expose things.

**Comment by hausdorff** [comment]
@lukehoban I'm not sure what you mean to ask, but it sounds like you're suggesting to use `T[]` everywhere, which would give us perhaps an API like this:

```typescript
const svcs = await k8s.core.v1.Service.list();
const publiclyExposed = query.from(svcs).filter(svc => svc.spec.type === "LoadBalancer");
```

Perhaps you meant to propose that `list()` here returns some type of `Enumerable`, but it seems like that would only remove the need for `query.from`, giving you `svcs.filter(svc => svc.spec.type === "LoadBalancer");` instead. Maybe there is a way to do this better, but I don't see it.

Contrast this with the following, which looks a lot closer to what we've been talking about

```typescript
const publiclyExposed = await k8s.core.v1.Service.list()
    .filter(svc => svc.spec.type === "LoadBalancer");
```

I'm also not sure how serious you think the "async all the way down" problem is. I don't see this as being a big problem at all, as the `then`s are all (purposefully) hidden behind the implementation. I do think the second is much cleaner, and I don't know of any serious drawbacks to using promises everywhere.

**Comment by hausdorff** [comment]
See also the context in this issue, which captures our thinking through most of the design process: https://github.com/pulumi/pulumi/issues/2601

**Comment by hausdorff** [comment]
Let's close this and merge with #2630

**Pull request closed without merging**
