### PR TITLE
Optionally include stack values for explicit Provider config

### LINKED ISSUE #12176: Allow provider config from stack and Provider arguments
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Provider configuration can be set in the following ways:
1. Explicit configuration on a first-class Provider resource
2. Stack/project configuration values (e.g., `kubernetes:enableServerSideApply: “true”`)
3. Environment variables

Options 1 and 2 are currently mutually exclusive [1], and 1 takes precedence if both are set. The `Configuration` method in the provider interface only passes through one source of configuration. Option 3 can be read by the provider directly, so it may always be available, depending on the provider implementation (the provider can read the env var directly, or it may be set in the SDK layer, and passed into a constructed first-class Provider).

It would be useful for the engine to pass stack/project configuration to the `Configuration` method for both default and first-class Providers, and then override values that are set as explicit arguments on first-class Providers rather than dropping some of the configuration in the engine if both 1 and 2 are set. This would allow users to set common configurations (e.g., cloud auth credentials) at the stack level, and then add additional configuration in a first-class Provider.

[[1]](https://www.pulumi.com/docs/intro/concepts/config/#provider-configuration-options)
> Configuration file settings are only used by the default provider. If you instantiate a provider object, it will not read values from the stack configuration.

Related issues:
https://github.com/pulumi/pulumi/issues/10126
https://github.com/pulumi/pulumi/issues/6961
https://github.com/pulumi/pulumi/issues/2059
https://github.com/pulumi/pulumi-aws/issues/2484

### Affected area/feature

Provider configuration

### PR DESCRIPTION
**Pull request by lblackstone**
# Description

Fixes #12176 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
Not overly keen on new global feature flags.
I feel either we need a path where we expect this to become the default in 4.0 or this should be a local option per-provider or per-stack rather than an env var.

**Comment by lblackstone** [comment]
> I feel either we need a path where we expect this to become the default in 4.0 or this should be a local option per-provider or per-stack rather than an env var.

I'm in favor of making this behavior default in 4.0, but for the meantime, happy to revise the way this is enabled. Were you picturing another project/stack config value that toggles the behavior, or something else?

**Comment by Frassle** [comment]
> Were you picturing another project/stack config value that toggles the behavior, or something else?

Yeh kind of like the disable default providers option. 

But if we think we're going to eventually make this the default mode and remove the flag then I'm fine with it being an envvar. Hopefully some time before 4.0 we could flip the default state of the envvar (with lots of upfront warning and messaging) and then 4.0 remove the envvar and only have the "explicit providers read from program inputs and stack config" behavior.

**Comment by lblackstone** [comment]
We decided not to go with this direction, so I'm closing this PR.

**Pull request closed without merging**
