### PR TITLE
Bump go-git to v5.6.0 to remove cgo dependency.

### LINKED ISSUE #12309: Bump go-git to `v5.6.0` to remove cgo dependency
The current version of go-git depends on cgo.

This cgo dependency is breaking our build in pulumi-docker-containers
https://github.com/pulumi/pulumi-docker-containers/issues/127

go-git release v5.6.0 has removed the cgo dependency
https://github.com/go-git/go-git/releases/tag/v5.6.0

### PR DESCRIPTION
**Pull request by dixler**
# Description

This PR removes a cgo dependency from pulumi which broke builds in pulumi-docker-containers (see https://github.com/pulumi/pulumi-docker-containers/issues/127).

go-git introduced a cgo dependency they have removed the dependency as of https://github.com/go-git/go-git/releases/tag/v5.6.0 and this PR bumps our version of go-git to that version.

Fixes #12309 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by abhinav** [comment]
I think you'll need to update some of the test go.mod files as well.

```
% rg -g 'go.mod' -l go-git | wc -l
      50
```

Something like this will update all of them:

```bash
find . -name go.mod -exec dirname '{}' ';' | while read R; do
  (cd "$R" && go get github.com/go-git/go-git/v5@latest)
done
./scripts/tidy.sh
```

**Review by abhinav — APPROVED** [review]
image

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge

**Pull request merged**
