### PR TITLE
[auto/go] Add support for `destroy --preview-only`

### LINKED ISSUE #16601: Option to re-enable preview & confirmation on auto.Stack.Destroy
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm using the Automation API to create a more customised and complete end-to-end experience for my users, e.g. by automatically initialising environment variables that pulumi requires, and automatically logging in to the correct backend.

For wrapping destroy in particular though, I'd still like to have it preview and prompt before going through. The current implementation (in Go) unconditionally adds the `--yes`, `--skip-preview` options, making that impossible.

### Affected area/feature

Automation API, github.com/pulumi/pulumi/sdk/v3/go/auto.Stack.Destroy

### PR DESCRIPTION
**Pull request by devnev**
Based on #15340

Closes #16601

### CODE REVIEW

**Comment by devnev** [comment]
Unfortunately I can't work out how to run the test locally, running `make test` fails on something unrelated

**Comment by Frassle** [comment]
> Unfortunately I can't work out how to run the test locally,

You can probably just run the one new test directly with e.g. `go test ./... -run=TestNewStackInlineSource`

**Comment by devnev** [comment]
Luckily, it passed in the acceptance tests now.

**Review by Frassle — APPROVED** [review]

**Pull request merged**
