### PR TITLE
Update grpc package to 1.24.2 for js sdk

### PR DESCRIPTION
**Pull request by c2h5oh**
Fixes building grpc package with gcc8 and newer
Fixes building grpc package for node 13.x
Matches minor gprc release (1.24.x) to version used by dotnet sdk

### CODE REVIEW

**Comment by pgavlin** [comment]
Thanks, @c2h5oh! In order to get CI coverage on this, I am going to open an equivalent PR. If that PR passes CI, we'll merge this.

**Comment by c2h5oh** [comment]
Any updates on this?

**Comment by pgavlin** [comment]
Just ran it; things look good.

**Comment by pgavlin** [comment]
Okay, we're good. The test failures were transient.

**Pull request merged**
