### PR TITLE
Add winget and msi install checks in download cron job

### LINKED ISSUE #10667: Extend Download Pulumi Cron to check for package version on WinGet
We have no active monitoring of whether WinGet publishing succeeded and usually wait for community members to ask questions before we detect a problem. I suggest extending the [Download Pulumi Cron](https://github.com/pulumi/pulumi/actions/workflows/download-pulumi-cron.yml) action with a step to check WinGet.

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #10667

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

**Comment by Zaid-Ajaj** [comment]
borse merge

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by mikhailshilkov** [comment]
@Zaid-Ajaj Our WinGet check seems to be failing with `winget: command not found`  https://github.com/pulumi/pulumi/actions/runs/3213404655/jobs/5253046325

**Comment by Zaid-Ajaj** [comment]
@mikhailshilkov expected windows-latest to have it installed since winget is included in Windows 11 by default AFAIK

**Pull request merged**
