### PR TITLE
Preallocate slices of known size.

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
Enable the "prealloc" lint, which identifies locations where slices have a known size, and can be preallocated, instead of allocated and reallocated when the length exceeds capacity.

# Description

## Checklist

- [ ] **N/A: Linter refactor** have added tests that prove my fix is effective or that my feature works

- [ ] **N/A: No changelog required.**I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by RobbieMcKinstry** [comment]
When I enabled this locally, `typecheck` lint started to fail! Pushing to see if that's a local problem or a more interesting failure.

**Comment by RobbieMcKinstry** [comment]
@abhinav instead of merging `master` into this branch, we need to rebase instead. We need to maintain a linear release history for our customers who maintain their own upstream.

**Comment by abhinav** [comment]
Ack. My bad.

**Comment by RobbieMcKinstry** [comment]
For simplicity, going to close this and reopen in a separate PR

**Comment by Frassle** [comment]
You know you can just force push to PR branches.

**Pull request closed without merging**
