### PR TITLE
Work around commonjs protoc bug

### PR DESCRIPTION
**Pull request by swgillespie**
When compiling with the commonjs target, the protoc compiler still emits
references to Closure Compiler-isms that whack global state onto the
global object. This is particularly bad for us since we expect to be
able to make backwards-compatible changes to our Protobuf definitions
without breaking things, and this bug makes it impossible to do so.

To remedy the bug, this commit hacks the output of protoc (again) with
sed in order to avoid ever touching the global object. Everything still
works fine because the commonjs target (correctly) exports the protobuf
message types via the module system - it's just not writing to global
anymore.

### CODE REVIEW

**Comment by swgillespie** [comment]
I manually edited the protobuf JS files that participate in the repro for https://github.com/pulumi/pulumi/issues/2401 and this code edit fixes the problem. I'm going to test now that only editing the newer protobuf JS file also fixes the problem (since we can't edit protobuf files we've already shipped).

**Comment by pgavlin** [comment]
Looks like this has broken CI. We might need to find another approach here, even if it means revving the PB defs to use a different type for the `propertyDependencies` field (e.g. a repeated message)

**Comment by swgillespie** [comment]
> Looks like this has broken CI.

Yep, we just needed to add some additional properties to the fake `global` object. I think we should still be fine.

**Comment by swgillespie** [comment]
Yuck, this is still running into trouble with the `status.proto` definition. I think we can safely exclude it from this transformation, since we will never change it (and if we do, the entire gRPC ecosystem breaks with us).

**Comment by swgillespie** [comment]
@pgavlin It's all working now and is ready for review 🎉 

I'm going to do some additional testing as well before merge.

**Comment by pgavlin** [comment]
@swgillespie do we have any side-by-side tests? Is it possible to add some? Not sure quite how we'd go about doing so.

**Comment by swgillespie** [comment]
We've got this test:

https://github.com/pulumi/pulumi/blob/35c60d61ebd5ac0953b7ac015d7cd6c81d30f4c5/sdk/nodejs/tests/runtime/langhost/cases/015.runtime_sxs/index.js#L15-L18

It's probably not impossible to test for this. I imagine the hard part would be hacking the on-disk js files so that we can test that two protobuf libs, loaded in isolation, do not change each other's globals.

**Comment by swgillespie** [comment]
@pgavlin done!

**Pull request merged**
