### PR TITLE
Add `*[TYPE]` to `[TYPE]Ptr` methods

### LINKED ISSUE #11536: Make it easier to get an `IntPtr` from a `*int`
Today, the only conversion function available to create an `IntPtr` accepts an `int`, not a `*int`.  This makes it quite awkward to accept pointers as input and construct `IntPtr` values - the code must manually nil-check the input, and then also there is no easy way (or perhaps even no way at all?) to inject the nil value into the pointer from user code.

The current `pulumi.IntPtr` function looks like:

```go
// IntPtr is an input type for *int values.
func IntPtr(v int) IntPtrInput {
	return (*intPtr)(&v)
}
```

Of all the "projection" functions available to create Pulumi Output values from raw values, this is the only example where the projection input is not the same as the element type.  I expect this was a mistake, as I cannot think of any reason it would have been necessary, and is significantly less flexible.

We should add an option that accepts a `*int`.  Since we can't break existing code, we may have to name it something like `IntPtrFromPtr`. 

Everything above applies for all `pulumi.*Ptr` projection functions - not just Int.

Note though that SDK codegen get this "right" - and generates projection functions from pointer types.  It is only the core `pulumi` SDK primitives that have this "wrong".

```go
func BucketObjectLockConfigurationPtr(v *BucketObjectLockConfigurationArgs) BucketObjectLockConfigurationPtrInput {
	return (*bucketObjectLockConfigurationPtrType)(v)
}
```

### PR DESCRIPTION
**Pull request by aq17**
Fixes #11536
Adds methods to convert pointer types to corresponding pulumi Ptr types

### CODE REVIEW

**Comment by aq17** [comment]
Would be great if Go supported overloading functions ☹️

**Review by iwahbe — CHANGES_REQUESTED** [review]
`sdk/go/pulumi/types_builtins.go` is generated.
https://github.com/pulumi/pulumi/blob/86e7d56df231760ebbfc64c809a7755b70cd8e6e/sdk/go/pulumi/types_builtins.go#L15
The result is fine though.

**Review by iwahbe — CHANGES_REQUESTED** [review]
After playing around with this for a bit, can we structure the function to avoid fat pointer confusion: [Go Playground link](https://go.dev/play/p/WpqInPa9fys).

```go
import "fmt"

type fooPtr int

type Bar interface {
	IsFoo() bool
}

func (f fooPtr) IsFoo() bool { return true }

func MakeFooGood(f *int) Bar {
	if f == nil {
		return nil
	}
	return (*fooPtr)(f)
}

func MakeFooBad(f *int) Bar {
	return (*fooPtr)(f)
}

func main() {
	var i int
	fmt.Printf("Good: (MakeFoo(&i) == nil) = %v, (MakeFoo(nil) == nil) = %v\n", MakeFooGood(&i) == nil, MakeFooGood(nil) == nil)
	fmt.Printf("Good: (MakeFoo(&i) == nil) = %v, (MakeFoo(nil) == nil) = %v\n", MakeFooBad(&i) == nil, MakeFooBad(nil) == nil)

}
```

**Review by iwahbe — APPROVED** [review]

**Pull request merged**
