### PR TITLE
Set O_APPEND on the engine event log file

### PR DESCRIPTION
**Pull request by Frassle**
# Description

This _might_ help with the issues we've been seeing with [automation api reading malformed JSON lines](https://github.com/pulumi/pulumi/issues/6768).

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works - Should be covered by existing tests to make sure this doesn't break automation api.

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change - Probably not user visible, we just need this in and then track if we still get bug reports about automation api.

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by abhinav** [comment]
I may be missing something, but I'm not sure this will help. The `O_TRUNC` will clear the file. The `O_APPEND` won't have any effect if it's just one writer that has already cleared the file.

**Comment by Frassle** [comment]
> The O_APPEND won't have any effect if it's just one writer that has already cleared the file.

You'd think so, this is very much a stab in the dark. At any rate I can't imagine it will make things worse.

**Review by abhinav — APPROVED** [review]
Okay, yeah if we're just experimenting.

**Comment by Frassle** [comment]
bors merge

**Pull request merged**
