### PR TITLE
Policy Analyzer Wrappers for Compiled Languages (go & dotnet)

### PR DESCRIPTION
**Pull request by im7mortal**
This **draft** introduces changes required by pulumi/pulumi-policy#229 and pulumi/pulumi-policy#230.

Main changes 
- Added a gRPC server wrapper for the policy analyzer plugin interface implementation. This wrapper is utilized in `pulumi-policy-analyzer-go`, `pulumi-policy-analyzer-dotnet`, and within the Go implementation of `pulumi-policy`.
- Implemented `pulumi-policy-analyzer-go` using the framework provided by analyzer-policy-common.
- A `pulumi-policy-analyzer-dotnet` implementation, also based on analyzer-policy-common, has been developed and will be pushed soon to corresponding repository.

This version is intended for design review, and I still need to finalize some parts. I've tested it end-to-end with the `pulumi-policy` Go implementations, which I will push in the near future.

### CODE REVIEW

**Comment by im7mortal** [comment]
There is a high level design 

Untitled Diagram drawio(2)

**Comment by Frassle** [comment]
Hi @im7mortal, thanks for the interest here but this is one of those cases where an upfront issue about direction would have probably saved some time. 
The engine _already_ has a feature in it to allow the runtimes to start up plugins (providers, converters, or analysers) from source code, it's the `RunPlugin` method on the language host. We'd been looking at cleaning up the `policy-analyzer` bootstrap programs and just replacing them with `RunPlugin` usage instead.

The wrapper around the analyzer grpc layer is still worth adding, we'd need that for the Go implementation anyway. But we shouldn't need specific policy-analyzer plugins for Go and Dotnet, just fix up PolicyAnalyzer to use RunPlugin for those languages instead.

It might even be possible to fix up PolicyAnalyzer to use RunPlugin for node and python, although that probably requires some extra work in their runtime host implementations.

If you want to rework this PR for just the grpc wrapper we can give that a review and merge that in. Then maybe work to get the Go policy implementation merged and write some tests showing the cli can use that after fixing up the policy startup logic.

**Comment by im7mortal** [comment]
@Frassle Thank you for the response!

The main issue is pulumi/pulumi-policy#230, where I've posted the details about the implementation.

Thank you for the information. I will use RunPlugin.

**Comment by mikhailshilkov** [comment]
@im7mortal Are you still planning to move this PR forward and address the comments?

**Comment by im7mortal** [comment]
@mikhailshilkov, this issue was split into #17194 and #17242, so I will close it.

**Pull request closed without merging**
