### PR TITLE
Don't add children of remote componet resources

### LINKED ISSUE #9071: Python hangs on specific inputs
Thanks @iwahbe @justinvp – both of those workarounds are OK for the repro example. In practice, I've tried to use a new Kubernetes provider to create cluster resources and have come up against another issue. This seems to be because cluster resources like `Namespace` have `parent=cluster` and this is interacting with providers. When we run `pulumi preview` it just hangs.

To reproduce:
1. With `pulumi==3.22.1` (before #8770) run `pulumi up` with the following program:
     ```python
    import pulumi
    import pulumi_eks as eks
    import pulumi_kubernetes as k8s
    
    cluster = eks.Cluster(resource_name="test")
    
    namespace = k8s.core.v1.Namespace(
        resource_name="test", opts=pulumi.ResourceOptions(provider=cluster.provider, parent=cluster)
    )
    ```
2. Upgrade to `pulumi==3.25.0`.
3. Implement the workaround and run `pulumi preview`:
    ```python
    import json
    
    import pulumi_eks as eks
    import pulumi_kubernetes as k8s
    import pulumi
    
    cluster = eks.Cluster(resource_name="test")
    
    provider = k8s.Provider(
        resource_name="test", kubeconfig=cluster.kubeconfig.apply(lambda k: json.dumps(k))
    )
    
    namespace = k8s.core.v1.Namespace(
        resource_name="test",
        opts=pulumi.ResourceOptions(provider=provider, parent=cluster),
    )
    ```

_Originally posted by @calumabarnett in https://github.com/pulumi/pulumi/issues/9024#issuecomment-1053499137_

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

Fixes #9071

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by t0yv0** [comment]
I'm a bit confused here.

Can we first have a by-design spec of the dependency relation? @pgavlin we discussed late last year that you were going to provide a spec, time to return to this perhaps?

The spec I have in mind as "current" was using cycle breaking but did not have special rules for remote components. It's partially implemented (say .NET pending, probably Python pending) across SDKs.

**Review by pgavlin — APPROVED** [review]
I agree that we need a spec here. I think we're going to have to work together to come up with one. I'm pretty sure that we do eventually to port the cycle-breaking code that @t0yv0 added last year to the other SDKs. However, I think that what you have here works, and we should probably port it to the other SDKs as well.

If I had to give an _informal_ spec of the expected behavior as of today, I'd say that it's something like this. The dependencies of a resource `R` is the set of custom and remote component resources reachable through the union of `R`'s implicit and explicit dependencies (i.e. resources referred to by `R`'s inputs and those present in `R`'s `dependsOn` option, if any. A resource `A` is _reachable_ from another resource `B` if `B` is a non-remote component resource and `A` is one of its descendants.

I think that the changes in this PR agree with that informal statement.

**Comment by t0yv0** [comment]
The PR makes sense with the extended comment, great! 

Thinking out loud. Unlike remote=False, SDK cannot observe remote=True children. SDK is trying though to assist the engine with ordering of submitted RegisterResource calls, in particular if R depends on RemoteC, then it's trying to make sure RegisterResource(R) does not hit the engine until all of RemoteC's children are done. It appears waiting on `URN` of RemoteC to resolve is what guarantees it. The engine does not finish resolving the RemoteC.URN until all the children are done. 

@Frassle this will throw a wrench into trying to fiddle with remote-ness of URNs - this subtlety here is important, we use URN resolution as completion as signaling in the cooperative ordering game.

@iwahbe, the cycle breaking is totally problematic but without it you can get SDK hangs. The cycle breaking is the less problematic solution in practice over the set of programs people are trying to write.

We need to work out something better eventually. The key challenge is that the set of children of a resource is not known to the SDK when it's remote, and not known to the SDK when it's local either because the set is expanded as the program continues executing. There's no solid way to synchronize and do "please wait until all children are known", but we can design something perhaps.

**Review by t0yv0 — APPROVED** [review]

**Comment by Frassle** [comment]
> @Frassle this will throw a wrench into trying to fiddle with remote-ness of URNs - this subtlety here is important, we use URN resolution as completion as signaling in the cooperative ordering game.

Yeh I'm not planning on making URN get resolved by SDKs, I was just mulling over the idea of somehow typing it to show that it's an Output that will never be "unknown". Having thought more on that I don't think we actually need to do anything here.

> We need to work out something better eventually. The key challenge is that the set of children of a resource is not known to the SDK when it's remote, and not known to the SDK when it's local either because the set is expanded as the program continues executing. There's no solid way to synchronize and do "please wait until all children are known", but we can design something perhaps.

Yes. Seeing something very similar with https://github.com/pulumi/pulumi/issues/9457

**Pull request merged**
