### PR TITLE
Bump @opentelemetry packages in NodeJS SDK

### PR DESCRIPTION
**Pull request by marcusirgens**
This commit bumps the versions of the various `@opentelemetry` packages used by the NodeJS SDK to their latest versions.

### CODE REVIEW

**Comment by lunaris** [comment]
Hi @marcusirgens; thanks for your contribution! I'll kick off a test run now and we can see whether this looks good or not :+1:

**Review by lunaris — APPROVED** [review]

**Comment by lunaris** [comment]
Hey @marcusirgens, I think this is ready to go! Sorry to ask, but are you able to rebase this? There was a bug in our community CI workflow which should now be fixed, and with a rebase hopefully we can get this merged :smile:

**Comment by marcusirgens** [comment]
> Sorry to ask, but are you able to rebase this?

✅

**Pull request merged**
