### PR TITLE
Expose Context for plugin providers

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

As a provider author, I may want to access request Context while continuing to use plugin.NewProviderServer to create a pulumirpc.ResourceProviderServer while coding to a higher-level API than raw gRPC. The request context has cancellation and metadata that might be relevant. For example, as a provider author I may want to add tracing spans to internal operations and have them tied to the parent span coming through gRPC and the request context.

Before this PR it wasn't quite possible to do this, and I'd have to drop to coding at pulumirpc.ResourceProviderServer level directly to recover the Context.

This PR introduces a new interface PluginWithContext that I can code against as provider author that gives back the request Context in every method. The change is slightly duplicative but non-breaking.
 

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by abhinav** [comment]
What's your opinion on naming the new interface `ProviderContext` and the methods `FooContext` instead of `*WithContext`?

Relevant stdlib examples:
- [exec.CommandContext](https://pkg.go.dev/os/exec#CommandContext) for [exec.Command](https://pkg.go.dev/os/exec#Command)
- [signal.NotifyContext](https://pkg.go.dev/os/signal#NotifyContext) for [signal.Notify](https://pkg.go.dev/os/signal#Notify)
- The upcoming slog package has [FooCtx](https://pkg.go.dev/golang.org/x/exp/slog#ErrorCtx) variants for [corresponding non-context methods](https://pkg.go.dev/golang.org/x/exp/slog#Error)
- [Dialer.DialContext](https://pkg.go.dev/net#Dialer.DialContext) for [Dialer.Dial](https://pkg.go.dev/net#Dialer.Dial)

Counter example:
- [net/http.NewRequestWithContext](https://pkg.go.dev/net/http#NewRequestWithContext): This could be named to match the [WithContext method](https://pkg.go.dev/net/http#Request.WithContext) which couldn't be named just "Context", as that would conflict with the Context getter.

**Comment by t0yv0** [comment]
Happy to take that suggestion and rename. I don't have a good feeling yet for what's idiomatic Go naming.

**Comment by abhinav** [comment]
Yes, please rename to ProviderContext and the methods to FooContext.
The change is fine besides that.
One step towards better complex plumbing through the system.

**Review by Frassle — CHANGES_REQUESTED** [review]
I'm blocking this. We already have a plan for a new provider interface split from the grpc model and with context support. If we're going to do work to bring up new types please bring up that one.

**Comment by t0yv0** [comment]
Hm, is that available for use today and if so could you provide a link? 

If it's not presently available I can fork this and inline code into the use site to support plugin framework in tfbridge.

**Comment by Frassle** [comment]
> Hm, is that available for use today and if so could you provide a link?

No, it's planned not prioritized https://github.com/pulumi/pulumi/issues/12010

**Comment by t0yv0** [comment]
OK then the best course of action left to me is to fork this code with a reference to https://github.com/pulumi/pulumi/issues/12010 and rewrite again if/when that lands.

**Pull request closed without merging**
