### PR TITLE
remove "of the day" from login tip

### PR DESCRIPTION
**Pull request by susanev**
we have said "tip of the day" since pulumi's birth
adjusting it to say "tip" since it never changes

### CODE REVIEW

**Comment by dixler** [comment]
Lol. I'd love to actually incorporate cycling tips into the update display.

**Comment by susanev** [comment]
@dixler do you want to add this back when you do that? i don't mean to be a pessimist, but people have been saying that to me for a long time, lol.

**Review by RobbieMcKinstry — APPROVED** [review]

**Review by abhinav — APPROVED** [review]
If we start rotating the tip, "Tip" will still be accurate.

**Comment by RobbieMcKinstry** [comment]
bors rt+

**Pull request merged**
