### PR TITLE
Adopt normal JS semantics when lifting property accesses on a null/undefined Output.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes: https://github.com/pulumi/pulumi/issues/3111

Previously, we treated property accesses on a null/undefined Output as null-propagating.  i.e. 

`output(undefined).p` would produce a new `output of undefined`.  I was treating this similar to SQL-nulls where null values just propagate whatever you do.  However, this really isn't JS semantics.  JS throws on these sorts of property accesses.  Furthermore, propagating `undefined` outwards leads to strange user behavior as it actually masks bugs and makes it seem as if values are disappearing.

This change moves us to normal JS semantics for our lifted props.

Note: this is a breaking change, and could affect runtime behavior of existing code.  We need to establish if we're ok with that before proceeding.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@lukehoban Thoughts here?  Small breaking change, but better overall behavior.  To me, it's acceptable.  To you on bar check.

**Comment by CyrusNajmabadi** [comment]
@lukehoban ^

**Comment by lukehoban** [comment]
Although this feels like it’s definitely more correct, and unlikely to cause problems as a breaking change - it also doesn’t feel like a change we have to make - we haven’t heard any users report the issue, and although confusing, it’s unlikely this causes any deep problems for users. My suggestion would be to leave this as is, and possibly even close #3111 as by-design for Pulumi 1.c. Curious though if @pgavlin feels differently.

**Comment by pgavlin** [comment]
I think at this point we should simply close #3111 as by design.

**Comment by lukehoban** [comment]
> I think at this point we should simply close #3111 as by design.

Agreed - that makes sense to me.

**Comment by CyrusNajmabadi** [comment]
Agreed.  I will update our documentatoin to make what is going on clear though.

**Pull request closed without merging**
