### PR TITLE
Update x/sys for sdk to support go 1.17

### PR DESCRIPTION
**Pull request by roopakv**
# Description

This updates x/sys for the sdk and therefor adds support for go 1.17. More info here https://github.com/Homebrew/homebrew-core/pull/83413

This also ran go mod tidy to clean up the go.sum file :)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by marians** [comment]
@roopakv Please update the CHANGELOG too. Thanks for pushing 1.17!

**Review by lblackstone — APPROVED** [review]
Thanks for the PR @roopakv!

**Comment by roopakv** [comment]
thankk yiu for pushing this thru @lblackstone

**Pull request merged**
