### PR TITLE
 fix: Ports Python CONFIG, ROOT, and _SECRET_KEYS to ContextVars 

### LINKED ISSUE #6052: [Automation API] Support parallel execution of python inline programs
The Pulumi python runtime implementation uses quite a bit of global state: 
* [SETTINGS](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/settings.py#L94)
* [ROOT](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/settings.py#L189)
* [CONFIG](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/config.py#L24)

We'll need to refactor all usage of global state out of the python SDK to allow Automation API to execute concurrent programs on different stacks that use the inline/hosted execution model.

Related: https://github.com/pulumi/pulumi/issues/5449

### PR DESCRIPTION
**Pull request by kpitzen**
# Description

This PR makes our global values that are not more complicated classes (like SETTINGS) ContextVars, and updates their interfaces where appropriate.

Fixes #6052 
## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by kpitzen** [comment]
This PR also depends on #10402

**Comment by justinvp** [comment]
Presumably, once this lands, we can remove the locking we have in the following places:
- https://github.com/pulumi/pulumi/blob/89b08f3f1f0f366f93be3674c50fe220ed312822/sdk/python/lib/pulumi/provider/server.py#L66-L96
- https://github.com/pulumi/pulumi/blob/89b08f3f1f0f366f93be3674c50fe220ed312822/sdk/python/lib/pulumi/provider/server.py#L197-L225

**Comment by kpitzen** [comment]
The approach here is a bit more straightforward given how simple these specific globals are.

Also to your point @justinvp - that seems possible given no context should be able to contend for its own resources, and contextvars will prevent contexts from accessing other contexts' globals!

**Review by justinvp — APPROVED** [review]
LGTM

**Pull request merged**
