### PR TITLE
Add go 1.18 workspace

### PR DESCRIPTION
**Pull request by Frassle**
Remove the experimentalWorkspaceModule setting from vscode settings and add a go.work file for the four top level modules contained in this repo.

### CODE REVIEW

**Comment by Frassle** [comment]
Well this seems to break the go pipeline....
@AaronFriel what's you suggestion for managing work files like this? Worth me investigating to fix the pipeline to deal with them or should people just be newing these up for themselves?

**Comment by AaronFriel** [comment]
I'd ask that we don't merge this and have people use their own workspaces - we can document it in `CONTRIBUTING.md`, as nested workspaces aren't supported (only the first ancestor `go.work` is used), so merging this breaks any attempt to work across repositories. 

If we were to merge this, it would break any engineers attempting to work across `pulumi/pulumi` and `pulumi/pulumi-yaml`, for example.

**Review by AaronFriel — CHANGES_REQUESTED** [review]
See comment above.

**Comment by Frassle** [comment]
Ah ok that's fair enough, shame we can't have this _just work_ out the box.

**Pull request closed without merging**
