### PR TITLE
Add mapping service to converter

### PR DESCRIPTION
**Pull request by Frassle**
# Description

This adds a new `Mapper` gRPC service that will be hosted by the engine and exposed to converters to allow them to call into the engine to get hold of mapping data, rather than having to load plugins to get hold of mapping information themselves.
This _also_ means that the `--mappings` override passed to convert is applied for plugins as well without having to pass those manual mappings down to the plugin.

This all needs a robustness pass over it at some point, but for now this is all _experimental_ and we just want to get this stuff in quickly to try it out downstream.

### CODE REVIEW

**Review by Zaid-Ajaj — APPROVED** [review]
LGTM

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
Odd, every job hit a 401 trying to get pulumictl.

bors retry

**Comment by Frassle** [comment]
bors retry

**Pull request merged**
