### PR TITLE
Enable fish completions for pulumi cli

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #4375

This upgrades cobra to 1.0.0 (we were on 0.0.6 and only 0.0.7 was
available before 1.0.0). This enables us to allow users to generate
fish completions. We have defaulted to including the fish completion
description by default

### CODE REVIEW

**Comment by stack72** [comment]
Post-2.0 @justinvp

**Comment by nesl247** [comment]
This was merged, but they don't seem to be installed automatically when installing from homebrew. This really should be handled automatically like other applications.

**Comment by gerrywastaken** [comment]
@stack72 While you added this I doubt many people know it exists: https://www.pulumi.com/docs/reference/cli/#command-line-completion

I only ended up guessing and getting lucky.

**Comment by stack72** [comment]
Thanks @gerrywastaken I will get that added to the guide!

**Pull request merged**
