### PR TITLE
fix: Invalid namespace delimiter in dotnet codegen

### PR DESCRIPTION
**Pull request by tmeckel**
# Description

This PR fixes an in issue in the dotnet codegen where an invalid character is used to parse namespaces.

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
- [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Frassle — COMMENTED** [review]
This doesn't look right to me. The name passed to "namespaceName" should be a package or module name might have "-" in it, but shouldn't have "/". If it does have slash that's a bug up the callstack probably where a qualified module hasn't been split up correctly.

Do you have an issue raised describing what this is trying to fix?

**Comment by Frassle** [comment]
Ah I assume this is to go with https://github.com/pulumi/pulumi-dotnet/issues/25?

**Comment by tmeckel** [comment]
@Frassle I had opened a thread on slack for this. And @iwahbe commented accordingly about #14296 sorry for the confusion here. Didn't see Ian's answer on Slack earlier.

**Comment by tmeckel** [comment]
Closed in favor of #14297

**Pull request closed without merging**
