### PR TITLE
Use 'localhost' vs 0.0.0.0

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This fixes things on my machine.  Testing on travis as well.

**Comment by ellismg** [comment]
There's a bunch of changes in addition to moving from 0.0.0.0 to localhost are they needed?

**Comment by CyrusNajmabadi** [comment]
>There's a bunch of changes in addition to moving from 0.0.0.0 to localhost are they needed?

The other changes were:

1. supporting reflection on the grpc server (during tests only).  it was helpful for bein able to manually query it.  I could roll that back if we don't want it.
2. updating the version of grpc we use.  likely not necessary.  but maybe we shoudl try to stay more up to date?  i can do that in a separate PR though.

**Comment by CyrusNajmabadi** [comment]
Let me first just see if this works :)

**Pull request merged**
