### PR TITLE
Warn about undefined stack outputs

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Fixes https://github.com/pulumi/pulumi/issues/7376

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Comment by Frassle** [comment]
Not sure why the tests are failing, they don't look related 😕 will dig into those.

**Review by dixler — APPROVED** [review]
LGTM

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
Windows!

bors retry

**Pull request merged**
