### PR TITLE
Add color option to stack up, preview, destroy, and refresh for automation api

### LINKED ISSUE #6997: Colored output with automation
## Affected feature

When using the automation API, when calling `preview` or `up`, it would be nice if there was a configuration option to specify that you want ANSI color codes in the output, for use in custom CLI use cases.

### PR DESCRIPTION
**Pull request by adrianord**
# Description

Adds a color option to the stack's up, preview, destroy, and refresh commands for the automation API.

Fixes #6997 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by adrianord** [comment]
I'm not sure there are tests that need to be written for this change.

**Review by dixler — APPROVED** [review]
LGTM

**Comment by dixler** [comment]
@Frassle does dotnet look fine?

**Review by Frassle — APPROVED** [review]
Looks ok to me

**Pull request merged**
