### PR TITLE
Fix regression validating project files with `refresh: always` set

### LINKED ISSUE #10824: 'refresh: true' option results in type error (v3.40.1)
### What happened?

Running Pulumi CLI command with `refresh: true` option results in the following error:
```bash
error: could not load current project: 1 error occurred:
	* #/options/refresh: expected boolean, but got string
```

### Steps to reproduce

Add the following configuration in `Pulumi.yaml` and run any pulumi command:
```yaml
options:
  refresh: true
```

### Expected Behavior

Stack refreshes, then performs specified command.

### Actual Behavior

Stack does not refresh, command does not run, and the following error is displayed:
```bash
error: could not load current project: 1 error occurred:
	* #/options/refresh: expected boolean, but got string
```

### Output of `pulumi about`

```bash
CLI
Version      3.40.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.20.2
python      unknown

Host
OS       darwin
Version  12.6
Arch     x86_64

This project is written in python: executable='/Users/XXX/anaconda/anaconda3/bin/python3' version='3.9.7
'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/XXX
User           XXX
Organizations  XXX, XXX

Dependencies:
NAME                    VERSION
azure-identity          1.10.0
azure-keyvault-secrets  4.4.0
pip                     22.2.2
pulumi-kubernetes       3.20.2
setuptools              63.4.2
wheel                   0.37.1
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
We recently started validating the `Pulumi.yaml` file against its schema, leading to the following error when the `refresh: always` option is specified:

```
error: could not load current project: 1 error occurred:
	* #/options/refresh: expected boolean, but got string
```

The problem is the feature is expecting a string value of `"always"` but the schema for the project file is incorrectly specified as `boolean`.

This change fixes the schema, which avoids the error. A separate change will fix the documentation at https://www.pulumi.com/docs/reference/pulumi-yaml/#options-options

Fixes #10824

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

**Comment by justinvp** [comment]
bors merge

**Review by AaronFriel — APPROVED** [review]
lgtm

**Comment by justinvp** [comment]
bors merge

**Pull request merged**
