### PR TITLE
create unknowns when the provider is not known during construct

### PR DESCRIPTION
**Pull request by tgummerer**
Currently when a provider is not known when trying to call construct, we error out.  A provider not being known can however legitimately happen during a preview, for example when setting up an eks cluster, and then using that kubeconfig to set up a kubernetes provider.

Users can currently work around that by using `--skip-preview`, and only going through the actual up, where the provider is known.  This is however not a great user experience.

Return a specific error from the provider Construct call, which we can then use in the resource monitor to fake constructing a resource with all unknown outputs.  This way the preview can still succeed, but any dependencies will also end up being unknown.

Fixes https://github.com/pulumi/pulumi/issues/16331

### CODE REVIEW

**Comment by Frassle** [comment]
I'm away from desk for a few hours at the moment but I'll take a look at this when back, something like this is what we need but the details here are probably complex.

**Comment by tgummerer** [comment]
> I'm away from desk for a few hours at the moment but I'll take a look at this when back, something like this is what we need but the details here are probably complex.

Yeah, I wanted to see what tests fail for this first, and then work the complexities out from there.

**Comment by Frassle** [comment]
> This does seem to work fine on the example from the issue.

I think this will just make the Construct call do nothing. It won't cause anything to show up at preview, won't even return a valid URN to the SDK for the component which will probably trip other assumptions up.

I think what we need to do is fill in that the component resource still gets registered, but just without any outputs.

**Comment by tgummerer** [comment]
> I think what we need to do is fill in that the component resource still gets registered, but just without any outputs.

Hrm, without calling the provider we won't be able to get the URN though?  Would it be alright to just make something up for that?  I guess it won't be registered anywhere if the provider isn't known, but I dunno if that could cause problems down the line?

**Comment by Frassle** [comment]
> Hrm, without calling the provider we won't be able to get the URN though? Would it be alright to just make something up for that? I guess it won't be registered anywhere if the provider isn't known, but I dunno if that could cause problems down the line?

We can call RegisterResource as if we were the provider to create the component resource. We know the name and type from the construct args. We just can't be sure of the options (not that many matter for a component resource by itself) or any of the children or outputs.

**Comment by tgummerer** [comment]
> We can call RegisterResource as if we were the provider to create the component resource

I think we'll need to do this in `RegisterResource`, as I don't think we can call it from `Construct`.  There's also a call to `Construct` in `provider_server.go`, that I'm not sure how that's used?  Would it be better to try and generate the URN in the provider `Construct` directly?

**Comment by Frassle** [comment]
> I think we'll need to do this in RegisterResource, as I don't think we can call it from Construct

One of the arguments to Construct is the address of the resource monitor. We should construct a grpc client and call register resource on that. Do not hack around this in source_eval.

**Comment by tgummerer** [comment]
> One of the arguments to Construct is the address of the resource monitor

Ah I missed that.  The latest commit uses that.

**Review by julienp — APPROVED** [review]

**Pull request merged**
