### PR TITLE
state_move: allow providers with same URN if inputs match

### PR DESCRIPTION
**Pull request by tgummerer**
Currently when there's already a provider in the destination stack with the same URN as a provider in the source stack (for a resource that is about to be moved) we error out, unless the IDs match. This is done so we don't assign a provider to a resource that won't work for it (e.g. provider with the same name but that have different AWS region setups).

However we can be a little bit smarter than this, and assign a resource a provider from the destination stack as long as all the provider inputs match.  If all the inputs match, we can assume that the provider will give us a valid situation for the resource.

Fixes https://github.com/pulumi/pulumi/issues/16983

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

**Comment by scp-mb** [comment]
@tgummerer Trying to do a `state move` for the first time from an existing stack into a new stack with no resources (`pulumi up` run with empty dotnet codebase) with 3.131.0 installed and still getting `error: provider urn:pulumi:dev::xxxxxx::pulumi:providers:azure-native::default_2_59_0 already exists in destination stack`

Any ideas?

**Comment by tgummerer** [comment]
@scp-mb can you run `pulumi stack export` on the destination stack to see what's there?  If it's really empty we shouldn't error out here :thinking:

**Comment by scp-mb** [comment]
@tgummerer Worked out where the issue was, the source stack was missing the `location` in the inputs/outputs for the azure native provider. We tend to specify the location on all resources anyway so it's not been an issue so far.

Adding `azure-native:location: UKWest` to both stacks and `pulumi up`'ing them seems to have worked, but it does seem that the check may still be a bit too strict. If there's only one provider registered for the resource to be parented to then does it make sense to just do that even if the location on the provider is different (or missing entirely, as the case was here)

**Comment by tgummerer** [comment]
> If there's only one provider registered for the resource to be parented to then does it make sense to just do that even if the location on the provider is different (or missing entirely, as the case was here)

I don't think that's safe to do unfortunately. E.g. if you have the provider in the destination stack set up with `azure-native:location: Australia` (or no location, as long as the default is different from UKWest, not sure what the default is), and you move the resource over from a source stack with `azure-native:location: UKWest`, that would break, since the provider would then think the resource is in Australia, while it's in reality still in UKWest.

**Comment by scp-mb** [comment]
@tgummerer  That's not necessarily true thought right? If you manually provide the location that is different to the provider default you wouldn't be able to move it between stacks that have different defaults.

As an example:

Stack 1: UKWest
Stack 2: UKSouth

Azure traffic managers are a global resource, so you must specify them with `Location = "global"`. If you then attempted to move that traffic manager between stacks 1 and 2 you couldn't do it because the provider location differs, even though that shouldn't matter to the traffic manager resources

**Comment by tgummerer** [comment]
Yes, in that case it would work just fine, but it's not true for the general case, and we have currently no way to ask the provider whether this resource can be moved to a different provider resource.  The `state move` command prefers safety over convenience here, as breaking one stack would be a lot more work to recover if things go wrong.

**Comment by scp-mb** [comment]
Perhaps a `--force` flag then? At least that allows for the option of using move instead of having to hand edit the state or `delete-retain` in one stack and `import` into another (assuming that's an option, currently importing keyvault access policies is broken)

That combined with an update to the error message to state that the resource provider inputs/outputs don't match would go a long way to making `state move` a bit more user friendly

**Comment by andehpants** [comment]
@tgummerer , could we exclude the check on the `default_tags` arg on the provider? We always set `default_tags` on our providers with `pulumi.get_stack()` and `pulumi.get_project` which I believe is causing us issues with `pulumi state move`

**Pull request merged**
