### PR TITLE
Expose LocalSerializer

### PR DESCRIPTION
**Pull request by ffMathy**
# Description
**Use case:** I want to be able to deserialize a `Pulumi.stack.yml` file without using a `LocalWorkspace`, as that requires too much configuration and isn't very well-documented.

## Checklist

- [X] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by ffMathy** [comment]
Hmmm, not sure how to run the changelog thing myself. Also curious as to why this is not done automatically by a CI/CD environment 🤔

**Comment by Frassle** [comment]
>  not sure how to run the changelog thing myself

Run `make changelog`

**Review by Frassle — APPROVED** [review]
This looks reasonable, but out of interest why are you wanting to deserialize a Pulumi.stack.yml?

**Comment by ffMathy** [comment]
> >  not sure how to run the changelog thing myself
> 
> Run `make changelog`

Do I need something installed for this? And can I run it on Windows?

**Comment by Frassle** [comment]
> Do I need something installed for this? And can I run it on Windows?

Should just need go and make. If it doesn't work just comment what you'd like it to say I can push a changelog commit for you.

> But when doing that, I want some additional settings that tell my Pulumi program to not include certain resources.

Ah ok good context to know, I want to rework config manipulation from automation api at some point and I can keep that  in mind.

**Comment by iwahbe** [comment]
bors retry

**Pull request merged**
