### PR TITLE
[docs] experiment for example creation syntax from program-gen

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
### Description

Related to: https://github.com/pulumi/pulumi/issues/14675

A follow up to @lukehoban comment on #15219 on going the program-gen route to generate syntax examples for resource creation. 

This PR implements a new command in the CLI to play with the idea and see what kind of code it generates. 

Here is how to use it:
```
pulumi package example aws aws:lambda/function:Function --language typescript --out ts
```
You can change `aws` to any package, `aws:lambda/function:Function` to any resource or function token from that package and the rest is the same as other parameters from `pulumi convert`. 

There is also the flag `--required-properties-only` which will emit only the properties of the resource or function that are required. This is to generate a more succinct version of the creation example.

The command above will generate:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const example = new aws.lambda.Function("example", {
    architectures: ["string"],
    code: new pulumi.asset.FileArchive("./path/to/archive"),
    codeSigningConfigArn: "string",
    deadLetterConfig: {
        targetArn: "string",
    },
    description: "string",
    environment: {
        variables: {
            string: "string",
        },
    },
    ephemeralStorage: {
        size: 0,
    },
    fileSystemConfig: {
        arn: "string",
        localMountPath: "string",
    },
    handler: "string",
    imageConfig: {
        commands: ["string"],
        entryPoints: ["string"],
        workingDirectory: "string",
    },
    imageUri: "string",
    kmsKeyArn: "string",
    layers: ["string"],
    memorySize: 0,
    name: "string",
    packageType: "string",
    publish: false,
    reservedConcurrentExecutions: 0,
    role: "string",
    runtime: "string",
    s3Bucket: "string",
    s3Key: "string",
    s3ObjectVersion: "string",
    skipDestroy: false,
    snapStart: {
        applyOn: "string",
        optimizationStatus: "string",
    },
    sourceCodeHash: "string",
    tags: {
        string: "string",
    },
    timeout: 0,
    tracingConfig: {
        mode: "string",
    },
    vpcConfig: {
        ipv6AllowedForDualStack: false,
        securityGroupIds: ["string"],
        subnetIds: ["string"],
        vpcId: "string",
    },
});
```

Later on we can see how make this process faster to generate examples from all resources within a schema for all languages. Right now this is just a show case what output we get from program-gen. There is also the process of how to integrate those into the docs but we can follow a similar route to what `pulumi convert` does for the next iteration of example conversion

### CODE REVIEW

**Comment by toriancrane** [comment]
I tried this out with Python using the CloudFront Distribution resource:

```python
import pulumi
import pulumi_aws as aws

example = aws.cloudfront.Distribution("example",
    aliases=["string"],
    comment="string",
    continuous_deployment_policy_id="string",
    custom_error_responses=[aws.cloudfront.DistributionCustomErrorResponseArgs(
        error_caching_min_ttl=0,
        error_code=0,
        response_code=0,
        response_page_path="string",
    )],
    default_cache_behavior=aws.cloudfront.DistributionDefaultCacheBehaviorArgs(
        allowed_methods=["string"],
        cache_policy_id="string",
        cached_methods=["string"],
        compress=False,
        default_ttl=0,
        field_level_encryption_id="string",
        forwarded_values=aws.cloudfront.DistributionDefaultCacheBehaviorForwardedValuesArgs(
            cookies=aws.cloudfront.DistributionDefaultCacheBehaviorForwardedValuesCookiesArgs(
                forward="string",
                whitelisted_names=["string"],
            ),
            headers=["string"],
            query_string=False,
            query_string_cache_keys=["string"],
        ),
        function_associations=[aws.cloudfront.DistributionDefaultCacheBehaviorFunctionAssociationArgs(
            event_type="string",
            function_arn="string",
        )],
        lambda_function_associations=[aws.cloudfront.DistributionDefaultCacheBehaviorLambdaFunctionAssociationArgs(
            event_type="string",
            include_body=False,
            lambda_arn="string",
        )],
        max_ttl=0,
        min_ttl=0,
        origin_request_policy_id="string",
        realtime_log_config_arn="string",
        response_headers_policy_id="string",
        smooth_streaming=False,
        target_origin_id="string",
        trusted_key_groups=["string"],
        trusted_signers=["string"],
        viewer_protocol_policy="string",
    ),
    default_root_object="string",
    enabled=False,
    http_version="string",
    is_ipv6_enabled=False,
    logging_config=aws.cloudfront.DistributionLoggingConfigArgs(
        bucket="string",
        include_cookies=False,
        prefix="string",
    ),
    ordered_cache_behaviors=[aws.cloudfront.DistributionOrderedCacheBehaviorArgs(
        allowed_methods=["string"],
        cache_policy_id="string",
        cached_methods=["string"],
        compress=False,
        default_ttl=0,
        field_level_encryption_id="string",
        forwarded_values=aws.cloudfront.DistributionOrderedCacheBehaviorForwardedValuesArgs(
            cookies=aws.cloudfront.DistributionOrderedCacheBehaviorForwardedValuesCookiesArgs(
                forward="string",
                whitelisted_names=["string"],
            ),
            headers=["string"],
            query_string=False,
            query_string_cache_keys=["string"],
        ),
        function_associations=[aws.cloudfront.DistributionOrderedCacheBehaviorFunctionAssociationArgs(
            event_type="string",
            function_arn="string",
        )],
        lambda_function_associations=[aws.cloudfront.DistributionOrderedCacheBehaviorLambdaFunctionAssociationArgs(
            event_type="string",
            include_body=False,
            lambda_arn="string",
        )],
        max_ttl=0,
        min_ttl=0,
        origin_request_policy_id="string",
        path_pattern="string",
        realtime_log_config_arn="string",
        response_headers_policy_id="string",
        smooth_streaming=False,
        target_origin_id="string",
        trusted_key_groups=["string"],
        trusted_signers=["string"],
        viewer_protocol_policy="string",
    )],
    origin_groups=[aws.cloudfront.DistributionOriginGroupArgs(
        failover_criteria=aws.cloudfront.DistributionOriginGroupFailoverCriteriaArgs(
            status_codes=[0],
        ),
        members=[aws.cloudfront.DistributionOriginGroupMemberArgs(
            origin_id="string",
        )],
        origin_id="string",
    )],
    origins=[aws.cloudfront.DistributionOriginArgs(
        connection_attempts=0,
        connection_timeout=0,
        custom_headers=[aws.cloudfront.DistributionOriginCustomHeaderArgs(
            name="string",
            value="string",
        )],
        custom_origin_config=aws.cloudfront.DistributionOriginCustomOriginConfigArgs(
            http_port=0,
            https_port=0,
            origin_keepalive_timeout=0,
            origin_protocol_policy="string",
            origin_read_timeout=0,
            origin_ssl_protocols=["string"],
        ),
        domain_name="string",
        origin_access_control_id="string",
        origin_id="string",
        origin_path="string",
        origin_shield=aws.cloudfront.DistributionOriginOriginShieldArgs(
            enabled=False,
            origin_shield_region="string",
        ),
        s3_origin_config=aws.cloudfront.DistributionOriginS3OriginConfigArgs(
            origin_access_identity="string",
        ),
    )],
    price_class="string",
    restrictions=aws.cloudfront.DistributionRestrictionsArgs(
        geo_restriction=aws.cloudfront.DistributionRestrictionsGeoRestrictionArgs(
            locations=["string"],
            restriction_type="string",
        ),
    ),
    retain_on_delete=False,
    staging=False,
    tags={
        "string": "string",
    },
    viewer_certificate=aws.cloudfront.DistributionViewerCertificateArgs(
        acm_certificate_arn="string",
        cloudfront_default_certificate=False,
        iam_certificate_id="string",
        minimum_protocol_version="string",
        ssl_support_method="string",
    ),
    wait_for_deployment=False,
    web_acl_id="string"
)
```

**Comment by cnunciato** [comment]
This is awesome, thanks @Zaid-Ajaj! Some initial feedback (all of which you probably already know) after running this across a handful of resources:

* Generated programs are indeed pretty verbose, as I think we expected. I remember we talked about maybe providing two versions of these, one succinct (containing only required params) and one complete, like what we have here. Do you think that's something we might be able to do?

* Programs that convert often fail to preview because of placeholder values (again, presumably known).

* The `javascript` language option doesn't seem to be supported. I know we have [this issue](https://github.com/pulumi/pulumi/issues/14632) open, so I'm assuming this is expected, but figured I'd mention it just in case.

* Java programs often fail to convert (e.g., these):
    ```
    aws:s3/bucket:Bucket
    aws:cloudfront/distribution:Distribution
    aws:ec2/launchTemplate:LaunchTemplate
    ```

* Lots of invalid input errors, like:
    ```
    error: could not generate output program: 
    <nil>: "None|Single|OnePerAz" is not a valid value of the enum "awsx:ec2:NatGatewayStrategy"; Valid members are "None", "Single", "OnePerAz", and 2 other diagnostic(s)`
    ```

* YAML programs seem to be getting generated with a `Main.yaml`. (I'd expect there to be only a `Pulumi.yaml`.)

* AWSx, Azure Native, and Kubernetes resources don't seem to work; they all fail similarly: 
    ```
    error: main.pp:87,22-88,1: Invalid expression; Expected the start of an expression, but found an invalid expression token.
    error: could not generate output program: failed to bind program
    ```

* A few optional params to consider: repo slug, version string (or Git SHA), schema path -- or maybe just a fully-qualified HTTP or file:// URL. This would allow anyone to run this just by pointing to a schema file. (Relatedly, do you imagine this being runnable for any Pulumi package, or only Pulumi-authored ones?)

Here's the Bash script I used to run through these, if you'd like to have a look: https://gist.github.com/cnunciato/6481c53db22536697eca001ebcc3688b

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @cnunciato for the review and for the script 🙏 it helped me test this implementation better and address some of the issues you encountered:

> Generated programs are indeed pretty verbose, as I think we expected. I remember we talked about maybe providing two versions of these, one succinct (containing only required params) and one complete, like what we have here. Do you think that's something we might be able to do?

I implemented a new flag `--required-properties-only` which does exactly this ✅ 

> Programs that convert often fail to preview because of placeholder values (again, presumably known).

I would expect a preview to work if it doesn't validate the inputs.

> The javascript language option doesn't seem to be supported. I know we have https://github.com/pulumi/pulumi/issues/14632 open, so I'm assuming this is expected, but figured I'd mention it just in case.

I don't think we will be implementing a new program-gen in javascript just for docs, it is a _lot_ of work to get right. The easiest would be to compile the generated TypeScript programs.

> Java programs often fail to convert (e.g., these):

I've tried these and for example `aws:s3/bucket:Bucket` _does_ convert, except that it doesn't compile, that's a separate issue. Do you have an example that doesn't emit any code?

> Lots of invalid input errors, like [enum errors]

I have fixed those by making example generation pick the first enum value rather than generating all of them, this gives the best results with generated programs ✅ 

> YAML programs seem to be getting generated with a Main.yaml. (I'd expect there to be only a Pulumi.yaml.)

I am not sure when we started doing this, I will ask. This the same result we get from `pulumi convert` btw

> AWSx, Azure Native, and Kubernetes resources don't seem to work; they all fail similarly (GCP works, though):

Fixed those errors ✅ the generator didn't handle schema types `Any` and `JSON`. Now it does!

> A few optional params to consider: repo slug, version string (or Git SHA), schema path -- or maybe just a fully-qualified HTTP or file:// URL. This would allow anyone to run this just by pointing to a schema file. 

You can already specify `<package>@<version>` or a path to a local schema file ✅ 

> Relatedly, do you imagine this being runnable for any Pulumi package, or only Pulumi-authored ones?

I don't see why only Pulumi-authored ones, if you have a plugin that emits a schema, you can use it. Although it is 100% certain that the way we use logic is going to be implemented via CLI command since its use currently is internal but if people like this we can discuss. It all depends on how the docs team imagines the integration story with the registry.

**Comment by cnunciato** [comment]
>I implemented a new flag --required-properties-only which does exactly this ✅

Amazing! Works exactly like it's supposed to. 🎉 

One thing that'd be awesome would be to apply some formatting to these -- e.g., with `black` for Python, `prettier` with TypeScript, etc. Is that something you're thinking about also?

**Comment by Zaid-Ajaj** [comment]
> One thing that'd be awesome would be to apply some formatting to these -- e.g., with black for Python, prettier with TypeScript, etc. Is that something you're thinking about also?

@cnunciato Wasn't necessarily on my radar 🤔 we could shell out to `black` or `prettier` inside the output directory if we check that they exist on the user's PATH but I think it might not be necessary given how simple the generated code looks like.

> Could this functionality be adapted to support lookup functions also?

Done ✅ the provided tokens can now be function tokens and it will just work. Tested using these:
```
aws:index/getCallerIdentity:getCallerIdentity
aws:index/getService:getService
aws:ivs/getStreamKey:getStreamKey
```
Note that the resource schema and function lookup are not optimized for batch conversions. Every time the command runs, it loops through every resource token and function token (if resource schema wasn't found). For AWS, if I try a token that doesn't exist, it takes ~3s to fail which is worse case scenario. 

I think there is something we can do here. For example if token isn't provided, we can generate subdirectories inside the output directory for every resource and function from the input package, sure it would still take a long time to finish but faster than one by one.

Again this depends on how the docs teams envisions the integration story with the registry

**Comment by cnunciato** [comment]
>Done ✅ the provided tokens can now be function tokens and it will just work.

Indeed it does. Amazing. Thank you!

>For example if token isn't provided, we can generate subdirectories inside the output directory for every resource and function from the input package, sure it would still take a long time to finish but faster than one by one.

It'd be interesting to see how that looks, yeah. "Generate all" is something we'll definitely want to do, and those seconds saved over thousands of resources will definitely add up.

**Comment by cnunciato** [comment]
@Zaid-Ajaj Are you thinking we'll close #15219 in favor of this approach, then? If so, what's blocking this PR at this point?

**Comment by Zaid-Ajaj** [comment]
@cnunciato Nothing is blocking this PR in terms of functionality. If we are happy with it, I can discuss it with the team further on actually releasing it

**Comment by Zaid-Ajaj** [comment]
Closing in favor of [pulumi-converter-constructor-syntax](https://github.com/pulumi/pulumi-converter-constructor-syntax) which contains the functionality from this PR as a converter that works with `pulumi convert`

**Pull request closed without merging**
