### PR TITLE
[sdk/dotnet] Bump Grpc NuGet packages to 2.37.0

### LINKED ISSUE #6870: Bump Grpc NuGet packages to 2.37.0
There are more important fixes for dotnet/c# in [v1.37.0](https://github.com/grpc/grpc/releases/tag/v1.37.0) (NuGet [2.37.0](https://www.nuget.org/packages/Grpc.Core/2.37.0)) (since [v1.34.0](https://github.com/grpc/grpc/releases/tag/v1.34.0)):
> C#
> * [C#] Add buildTransitive directory to NuGet package. (#25385)
> * Reduce Grpc.Core nuget size by generating separate .so with/without debug symbols for grpc_csharp_ext. (#25729)
> * make Grpc C# work on aarch64 linux. (#25717)
> * Add support for additional protoc arguments in Grpc.Tools. (#25374)
> * C#: Use explicit native extension loading whenever possible. (#25490)

> * [Backport] [C#] Use explicit native extension loading whenever possible. (#25506)

> * fix nuget package signing on Linux (do not use PublicSign=true on non-windows). (#24980)
> * Remove C# as a supported language for xDS features. (#24982)
> * Fix C# native library loading in .NET 5 single-file apps. (#24744)

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #6870.

### CODE REVIEW

**Comment by gitfool** [comment]
Unrelated build failure in [Lint SDKs (Lint Python)](https://github.com/pulumi/pulumi/pull/6871/checks?check_run_id=2430069001#step:16:13):
> ************* Module pulumi.automation._cmd
Error: lib/pulumi/automation/_cmd.py:49:4: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
************* Module pulumi.automation._stack
Error: lib/pulumi/automation/_stack.py:668:4: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
Error: lib/pulumi/automation/_stack.py:672:4: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
************* Module pulumi.automation._local_workspace
Error: lib/pulumi/automation/_local_workspace.py:268:8: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)

**Comment by gitfool** [comment]
@mikhailshilkov 😉

**Review by mikhailshilkov — APPROVED** [review]
Ah, sorry, I haven't noticed the PR 👍

**Pull request merged**
