### PR TITLE
Default to a parallelism fanout of 10

### PR DESCRIPTION
**Pull request by swgillespie**
🚀

### CODE REVIEW

**Comment by swgillespie** [comment]
also cc @pgavlin @hausdorff

**Comment by swgillespie** [comment]
Well, that test result is not good. Investigating.

**Comment by swgillespie** [comment]
There is only one real issue here and it's a test issue, all of the other failures are due to Travis networking problems. With the latest commit (fixing the test) all tests passed locally.

**Comment by pgavlin** [comment]
> There is only one real issue here and it's a test issue, all of the other failures are due to Travis networking problems.

We have lots of tests that use resources with many potential partial orders. Do you plan to fix these up if/when they fail?

**Comment by swgillespie** [comment]
> We have lots of tests that use resources with many potential orders. Do you plan to fix these up if/when they fail?

Yes.

**Comment by swgillespie** [comment]
The Travis troubles appear to be ongoing and two of the three test legs completed without errors. Is anyone opposed to merging this PR?

**Comment by joeduffy** [comment]
I'm very happy to see this default to >1!

I'm wondering, why 10? Last we spoke, I thought we'd choose something like 4*numprocs. I actually wonder if we should be more aggressive. These tasks are going to be very IO heavy so 10 actually isn't an incredibly wide degree of parallelism. I could even imagine fixing it to something like 32.

Do you ever imagine this to be more adaptive? `-p auto`, like a threadpool, would be neat. (Not for now, obviously, but if there's merit to this, it's worth filing a work item.)

**Comment by swgillespie** [comment]
> I'm wondering, why 10? Last we spoke, I thought we'd choose something like 4*numprocs. I actually wonder if we should be more aggressive. These tasks are going to be very IO heavy so 10 actually isn't an incredibly wide degree of parallelism. I could even imagine fixing it to something like 32.

Luke pointed out this morning that 10 is the default for Terraform. Since we rely so heavily on Terraform providers, it made sense to start with what Terraform providers are used to seeing.

> Do you ever imagine this to be more adaptive? -p auto, like a threadpool, would be neat. (Not for now, obviously, but if there's merit to this, it's worth filing a work item.)

Absolutely. Go makes this very simple since spawning new goroutines is cheap. I don't think there's any need for threadpools if the Go scheduler is capable of handling the hard parts for us.

**Comment by lukehoban** [comment]
I think we all agree - long term we will move toward unbounded parallelism in the engine layer - short term 10 is a huge step forward. 

If others feel strongly we should jump straight to unbounded I’m not strictly opposed - but my preference would be to do this in two steps.

**Comment by swgillespie** [comment]
> If others feel strongly we should jump straight to unbounded I’m not strictly opposed - but my preference would be to do this in two steps.

I agree with this. I propose that we merge if there aren't any other objections.

**Comment by lukehoban** [comment]
Yes - let's merge this as is.

I've opened https://github.com/pulumi/pulumi/issues/1758 to track pushing this further by default.

**Pull request merged**
