### PR TITLE
Added a way to wrap a serialized function entrypoint

### PR DESCRIPTION
**Pull request by Tirke**
## Why

While looking at [pulumi-iopipe](https://github.com/pulumi/pulumi-iopipe/blob/master/index.js) I was wondering if we could avoid the regex thingy.
I made a very small modification on `serializeFunction` that allows wrapping the final endpoint.
This modification could simplify the implementation of `pulumi-iopipe` and will help with what I plan to do with `pulumi-epsagon` (epsagon is a little bit trickier because there is an init call necessary).

I'm not really sure that's a good PR so feel free to close or correct me.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@Tirke I'm not quite sure i understand what thsi is trying to do :)  Woudl you be willing to go over to the pulumi-community slack channel to discuss things?  If you don't have hte time, we can still do things here.  But i'd def like to understand your situation first.  Thanks!

**Comment by Tirke** [comment]
I'm sorry it's a bit late here but basically

Before:

```typescript
    const origSerializeFunction = pulumi.runtime.serializeFunction;
    pulumi.runtime.serializeFunction = async function(func, args) {
        const serialized = await origSerializeFunction(func, args);        
        // NOTE: We have a dependency here on the structure of the generated function serialization.
        const lines = serialized.text.split("\n");
        const match = /^exports\.(.*) = (.*);$/.exec(lines[0]);
        if (!match) {
            console.error("Failed to wrap Pulumi function with IO|.")
        } else {
            lines[0] = `exports.${match[1]} = require("@iopipe/iopipe")({token: "${token}"})(${match[2]});`;
        }
        return {
            ...serialized,
            text: lines.join("\n"),
        };
    };
```

After:

```typescript
    const origSerializeFunction = pulumi.runtime.serializeFunction;
    pulumi.runtime.serializeFunction = async function(func, args) {
        const wrappingCall= `require("@iopipe/iopipe")({token: "${token}"});
        const serialized = await origSerializeFunction(func, {...args, wrappingCall);        
        return serialized;
    };
```

Like I said not sure this feels right, but happy to discuss it tomorrow.

**Comment by CyrusNajmabadi** [comment]
So... if i'm understanding properly, you want to *export* something akin to:

```ts
module.exports = require("@iopipe/iopipe")({token: __originalFunctionEntrypoint});
```

Something like that?

If so... i think a cleaner way would be to use hte new factory function stuff we recently added.  You should be able to just do this:

```ts
import * as iopipe from "@iopipe/iopipe";
//...
pulumi.runtime.serializeFunction(() => {
    const wrapped = iopipe({ token: originalFunc });
    return wrapped;
}, { isFactoryFunc: true });
```

the 'isFactoryFunc' will cause us to execute that function at the end of module-load, taking the result of it and making it the module export.  

Can you take a look?  Note: i'm going on vacation soon for about 5 days.  But i will try to check back in to see if this can unblock you (or to learn why it's not sufficient!).

**Comment by lukehoban** [comment]
I do like the idea of being able to do something more like what @CyrusNajmabadi suggests - avoiding any string munging at all.  I feel like factory functions actually enables that (prior to those, this wasn't possible).  Not 100% sure that this will within the monkey-patching style approach needed for https://github.com/pulumi/pulumi-iopipe (and epsagon) though - will be interested to hear @Tirke's thoughts on that.

**Comment by Tirke** [comment]
Yes, I didn't like the _fragility_  of my design, relying on strings and potentially leading to problems (even though a classic user will never interact with the runtime).

I think I have successfully found a way to implement what is needed for IOPipe / Epsagon by just using factoryFunctions. Will test a little bit more and PR on the relevant repo.
Thanks a lot for your help.

**Comment by Tirke** [comment]
Closing this as we can easily implement IOPipe, Epsagon, ... integrations with factory functions. Thanks everyone.

**Comment by CyrusNajmabadi** [comment]
That's really great to hear!  That makes me feel like the factory function approach is a really nice and clean way to allow anyone to participate here and flexibly inject their own processing.  Thanks a lot for verifying!

**Comment by lukehoban** [comment]
@CyrusNajmabadi Check out the resulting changes in the IOpipe integration - really nice after moving to factory functions.  https://github.com/pulumi/pulumi-iopipe/compare/9cb88accea606cc1ba44e8cad37030e16fde603e...master

**Comment by CyrusNajmabadi** [comment]
That's super clean.  I also like the usage of `const newExtraIncludePackages = [...(extraIncludePackages || []), "@iopipe/iopipe"];` to ensure the right package is always included.

I'm both happy that people are integrating into this layer, but i'm also bummed as that means tweaking/changing the API shape is now basically so much harder.  Ah well.. it's a good problem to have :)

**Pull request closed without merging**
