### PR TITLE
🚀 Prepare Changelog for Release v3.38.0

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
# Description

🚀 This PR prepares the CHANGELOG for release v3.38.0

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by mikhailshilkov — APPROVED** [review]
LGTM although the PR title is a bit misleading

**Review by kpitzen — APPROVED** [review]
🤦 Apologies - I merged a PR after you posted this!  It LGTM though!

**Comment by RobbieMcKinstry** [comment]
> LGTM although the PR title is a bit misleading

Sorry! What do you find misleading about the title? Is it the emoji?

**Comment by RobbieMcKinstry** [comment]
> 🤦 Apologies - I merged a PR after you posted this! It LGTM though!

No worries dude! I'll rebase this PR and capture your change 👍🏻

**Comment by mikhailshilkov** [comment]
> What do you find misleading about the title? Is it the emoji?

Sorry, I should have explained. Actually, it's the fact that PR changes go.mod files in addition to Changelog. Based on the title, I assumed it would be a changelog bump (and therefore no build required).

**Comment by RobbieMcKinstry** [comment]
Ah, yes. That was automated by the release script. I didn't realize there were three commits in the PR until I submitted it. :)

**Pull request merged**
