### PR TITLE
Method renames for dotnet automation API GA

### PR DESCRIPTION
**Pull request by t0yv0**
Takes care of the part of https://github.com/pulumi/pulumi/issues/6459 as relates to method renames. In addition renames RemoveConfigAsync and RemoveAllConfigAsync.

### CODE REVIEW

**Comment by t0yv0** [comment]
CC @orionstudt

**Comment by orionstudt** [comment]
I will say that I'm not a fan of these names... I had thought that in the original Automation API PR we had agreed to go with names that unify related methods alphabetically for intellisense and usage purposes [here](https://github.com/pulumi/pulumi/pull/5761#discussion_r523156519)

**Comment by t0yv0** [comment]
Thanks for that pointer @orionstudt and the feedback. I think the current priority is cross-SDK consistency of the operation names so the decision was made to got his way. I will take a note to bring this up again with the team so we may reconsider.

**Comment by komalali** [comment]
@orionstudt Ah, I definitely missed that entire conversation. 

The issues for the other languages were never opened, and I wasn't aware that we had decided that we would align the other languages with C# rather than the other way around.

At this point, it wouldn't be entirely painless to take this breaking change in the 3 other SDKs, not to mention the related changes in the code that consumes these APIs. If we were to do it, we need to somehow fit that into the next 12 days which I'm not sure we have the capacity for.

**Comment by orionstudt** [comment]
@komalali it is what it is! I don't think it is that big of an issue, but I do think there is value in related methods being near each other alphabetically for intellisense. I think I tried to clarify the miscommunication [here](https://github.com/pulumi/pulumi/issues/6459#issuecomment-800731883) but I failed to be specific enough so its on me 😅

**Pull request merged**
