### PR TITLE
Do not emit an empty line after the generated-code warning.

### PR DESCRIPTION
**Pull request by pgavlin**

### CODE REVIEW

**Comment by pgavlin** [comment]
This is necessary so we can wrap this comment in `<auto-generated>` for .NET.

Happy to make this optional via a flag.

**Comment by CyrusNajmabadi** [comment]
> This is necessary so we can wrap this comment in <auto-generated>

Note: you don't have to do that.  All that matters is that the the section of comments contains `<auto-generated/>`

**Comment by CyrusNajmabadi** [comment]
Ack.  didn't mean to close.  soryr.

**Comment by pgavlin** [comment]
> Note: you don't have to do that. All that matters is that the the section of comments contains <auto-generated/>

Where is the documentation for this?? I could not find anything with a search. In that case I can just preface the comment with that tag.

**Comment by CyrusNajmabadi** [comment]
>Where is the documentation for this?

hahahahaha

**Comment by pgavlin** [comment]
Alright. I'm going to close this out, then.

**Pull request closed without merging**
