### PR TITLE
Allow `pulumi.export` calls from unit tests

### LINKED ISSUE #4478: Python tests fail on exports
Not sure if this is a Pulumi bug or just lack of documentation...?

I'm following this tutorial: https://www.pulumi.com/docs/guides/testing/unit/
But adding `pulumi.export` to the stack causes the tests to fail hard.

Is there a solution for this?

```
(.venv) cmclaughlin-local@cm in /tmp
$ git clone https://github.com/pulumi/examples.git
Cloning into 'examples'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (70/70), done.
Receiving objects: 100% (8466/8466), 9.34 MiB | 71.00 KiB/s, done.
remote: Total 8466 (delta 26), reused 37 (delta 14), pack-reused 8380
Resolving deltas: 100% (5094/5094), done.

(.venv) cmclaughlin-local@cm in /tmp
$ cd examples/testing-unit-py/

(.venv) cmclaughlin-local@cm in /tmp/examples/testing-unit-py
on master
$ echo "pulumi.export('hello', 'world')" >> infra.py

(.venv) cmclaughlin-local@cm in /tmp/examples/testing-unit-py
on master
$ python -m unittest
E
======================================================================
ERROR: test_ec2 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ec2
Traceback (most recent call last):
  File "/Users/cmclaughlin-local/.pyenv/versions/3.7.4/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/cmclaughlin-local/.pyenv/versions/3.7.4/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/private/tmp/examples/testing-unit-py/test_ec2.py", line 13, in <module>
    import infra
  File "/private/tmp/examples/testing-unit-py/infra.py", line 20, in <module>
    pulumi.export('hello', 'world')
  File "/Users/cmclaughlin-local/repos/shopstyle/pulumi/stacks/pypy/.venv/lib/python3.7/site-packages/pulumi-2.1.0a1587474541-py3.7.egg/pulumi/resource.py", line 884, in export
    raise Exception("Failed to export output. Root resource is not an instance of 'Stack'")
Exception: Failed to export output. Root resource is not an instance of 'Stack'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

### PR DESCRIPTION
**Pull request by justinvp**
The [previous attempt](https://github.com/pulumi/pulumi/pull/4518) to allow this didn't actually allow it, so this is take two. As part of the previous attempt, I thought after tweaking the test I had observed the test failing, and then succeeding after making the product changes, but I must have been mistaken.

It turns out that our existing "testing with mocks" tests _weren't running at all_ because of a missing `__init__.py` file. Once the missing `__init__.py` is added, the tests run, but other tests (the "test mode" tests) fail because the code that creates the mocks and resources will run during test discovery, and setting the mocks modifies global state.

To address the test issue, I've moved the mocks tests into their own `test_with_mocks` package that can be run separately from other tests.

To address the actual issue, a root Stack resource is initialized when the mocks are set.

Fixes #4478

### CODE REVIEW

**Comment by lukehoban** [comment]
> To address the actual issue, a root Stack resource is initialized when the mocks are set.

Should we be doing this consistently across languages?  I believe this is the root cause of https://github.com/pulumi/pulumi/issues/4669 as well - and quite likely other issues.

**Comment by justinvp** [comment]
> > To address the actual issue, a root Stack resource is initialized when the mocks are set.
> 
> Should we be doing this consistently across languages?

I think we should do this for Node.js too, but would love to hear @pgavlin's, and @mikhailshilkov's thoughts. Notably, .NET and Go don't really have these problems and already have a root stack created as part of running with mocks just by the nature of how mocks are used in those languages.

**Comment by justinvp** [comment]
Confirmed in the Travis logs that the "testing with mocks" tests are now actually running and succeeding:

```
pipenv run python -m unittest discover -s lib/test_with_mocks -v
3258test_component (test_testing_with_mocks.TestingWithMocks) ... ok
3259test_custom (test_testing_with_mocks.TestingWithMocks) ... ok
3260test_invoke (test_testing_with_mocks.TestingWithMocks) ... ok
```

**Comment by lukehoban** [comment]
> Do we still have an issue to track Node.js or should we make one?

#4669 is tracking this.

**Pull request merged**
