### PR TITLE
chore: Update go modules via go mod tidy

### PR DESCRIPTION
**Pull request by kpitzen**
# Description

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by kpitzen** [comment]
bors merge

**Review by Frassle — APPROVED** [review]

**Comment by Frassle** [comment]
bors merge

**Comment by kpitzen** [comment]
bors merge

**Comment by kpitzen** [comment]
bors p=100

**Pull request merged**
