### PR TITLE
Replace plugin.Proc with Kill

### PR DESCRIPTION
**Pull request by Frassle**
# Description

While today all plugins are processes we have plans to also run plugins via other methods. The only thing the process object was used for on the plugin struct was to kill it, so I've weakened the interface to just require a `Kill` method. We'll be able to implement that for our other plugin runners as well.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by t0yv0** [comment]
That method is very worrisome, having watched it operate on different platforms while debugging tests. I know it's a lot more work but can we consider reworking things to terminate gracefully without kill? Some heartbeat scheme perhaps where subordinate processes check in with the process monitor and if they can't reach it, gracefully shut down.

**Comment by t0yv0** [comment]
That method is very worrisome, having watched it operate on different platforms while debugging tests. I know it's a lot more work but can we consider reworking things to terminate gracefully without kill? Some heartbeat scheme perhaps where subordinate processes check in with the process monitor and if they can't reach it, gracefully shut down.

**Comment by t0yv0** [comment]
Linux and Mac are different in how they work with orphan process PIDs; whether the process sits in the process table after terminated or not, and Windows-specific things are really different they scan the process table... These race conditions associated with the fact that scanning process children may race with these processes creating children or stopping them. Also for GPID, setgpid accidentally or through library in a subprocess may disrupt the scheme of tracking "descendants" implied here.

**Comment by t0yv0** [comment]
Linux and Mac are different in how they work with orphan process PIDs; whether the process sits in the process table after terminated or not, and Windows-specific things are really different they scan the process table... These race conditions associated with the fact that scanning process children may race with these processes creating children or stopping them. Also for GPID, setgpid accidentally or through library in a subprocess may disrupt the scheme of tracking "descendants" implied here.

**Review by t0yv0 — APPROVED** [review]
Approving, with reservations.

**Comment by Frassle** [comment]
> That method is very worrisome, having watched it operate on different platforms while debugging tests.

This PR isn't changing the current method. Just changing the interface to call it, but yes I agree we can probably do this in a cleaner way.

**Pull request merged**
