### PR TITLE
Lock .version for 3.76.0 release

### PR DESCRIPTION
**Pull request by Frassle**

### CODE REVIEW

**Review by dixler — APPROVED** [review]

**Comment by Frassle** [comment]
Hmm hit a data race error:

```
=== FAIL: go/auto TestNewStackRemoteSourceWithSetup (76.52s)
==================
WARNING: DATA RACE
Read at 0x000002b22ce0 by goroutine 102:
  github.com/go-git/go-git/v5/plumbing/transport.FilterUnsupportedCapabilities()
      /Users/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.6.0/plumbing/transport/common.go:280 +0x9b1
  github.com/go-git/go-git/v5/plumbing/transport/http.advertisedReferences()
      /Users/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.6.0/plumbing/transport/http/common.go:70 +0x985
  github.com/go-git/go-git/v5/plumbing/transport/http.(*upSession).AdvertisedReferencesContext()
      /Users/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.6.0/plumbing/transport/http/upload_pack.go:32 +0x64
  github.com/go-git/go-git/v5.(*Remote).fetch()
      /Users/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.6.0/remote.go:420 +0x4a1
  github.com/go-git/go-git/v5.(*Repository).fetchAndUpdateReferences()
      /Users/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.6.0/repository.go:964 +0xd3
  github.com/go-git/go-git/v5.(*Repository).clone()
      /Users/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.6.0/repository.go:827 +0x624
  github.com/go-git/go-git/v5.PlainCloneContext()
      /Users/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.6.0/repository.go:415 +0xa4
  github.com/pulumi/pulumi/sdk/v3/go/auto.setupGitRepo()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/git.go:129 +0x103e
  github.com/pulumi/pulumi/sdk/v3/go/auto.NewLocalWorkspace()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace.go:778 +0x464
  github.com/pulumi/pulumi/sdk/v3/go/auto.NewStackRemoteSource()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace.go:1112 +0x2b0
  github.com/pulumi/pulumi/sdk/v3/go/auto.TestNewStackRemoteSourceWithSetup()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace_test.go:667 +0x667
  testing.tRunner()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1629 +0x47

Previous write at 0x000002b22ce0 by goroutine 101:
  github.com/pulumi/pulumi/sdk/v3/go/auto.setupGitRepo()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/git.go:134 +0x1153
  github.com/pulumi/pulumi/sdk/v3/go/auto.NewLocalWorkspace()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace.go:778 +0x464
  github.com/pulumi/pulumi/sdk/v3/go/auto.UpsertStackRemoteSource()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace.go:1131 +0x2b0
  github.com/pulumi/pulumi/sdk/v3/go/auto.TestUpsertStackRemoteSource()
      /Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace_test.go:558 +0x33e
  testing.tRunner()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1629 +0x47

Goroutine 102 (running) created at:
  testing.(*T).Run()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1576 +0x216
  testing.runTests()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:[190](https://github.com/pulumi/pulumi/actions/runs/5612292652/job/15206129639#step:34:191)6 +0xb44
  main.main()
      _testmain.go:154 +0x2fc

Goroutine 101 (running) created at:
  testing.(*T).Run()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:[203](https://github.com/pulumi/pulumi/actions/runs/5612292652/job/15206129639#step:34:204)6 +0x8d
  testing.tRunner()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1576 +0x[216](https://github.com/pulumi/pulumi/actions/runs/5612292652/job/15206129639#step:34:217)
  testing.runTests()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      /Users/runner/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1906 +0xb44
  main.main()
      _testmain.go:154 +0x2fc
==================
    testing.go:1446: race detected during execution of test
```

Clearly intermittent because every other merge has been ok, so I'll retry this to get the release out but we should look into this.

bors retry

**Comment by dixler** [comment]
@Frassle I'll open an issue

**Comment by Frassle** [comment]
bors retry

**Comment by Frassle** [comment]
windows test failed

bors retry

**Pull request merged**
