### PR TITLE
Remove dotnet

### PR DESCRIPTION
**Pull request by Frassle**
The dotnet sdk is being moved to https://github.com/pulumi/pulumi-dotnet

### CODE REVIEW

**Comment by Frassle** [comment]
bors try

**Comment by Zaid-Ajaj** [comment]
@Frassle the build seems to have failed because it couldn't find this artifact

> pulumi-language-dotnet-v3.50.0-windows-amd64.tar.gz

Whereas in the releases it is `pulumi-language-dotnet-v3.50.0-windows-amd64.zip`

**Comment by Frassle** [comment]
> @Frassle the build seems to have failed because it couldn't find this artifact

Just sent a message on slack about this, but we should change pulumi-dotnet to .tar.gz on windows. All our plugin logic assumes .tar.gz everywhere. pulumi-java should get fixed to .tar.gz as well really.

**Comment by Frassle** [comment]
bors try

**Review by Zaid-Ajaj — APPROVED** [review]

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
bors retry

**Pull request merged**
