### PR TITLE
chore(all): strings.Replace(..., -1) => strings.Replace(...)

### PR DESCRIPTION
**Pull request by abhinav**
Replaces all instances of `strings.Replace(s, old, new, -1)`
with the equivalent `strings.ReplaceAll(s, old, new)`.
This function has been available since Go 1.12.

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12267** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12267" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12267?utm_source=stack-comment).

**Review by justinvp — APPROVED** [review]

**Comment by abhinav** [comment]
Landing because this was green minus downstream codegen, which it doesn't actually change.
(Build above was canceled because workers were locked up yesterday.)

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
CI passed on merge. Failed during sign step:
https://github.com/pulumi/pulumi/actions/runs/4317693740/jobs/7535863162

**Pull request merged**
