### PR TITLE
Revert 7983 where possible

### LINKED ISSUE #8033: Emitted SDK versions breaking provider builds
https://github.com/pulumi/pulumi/pull/7938 started emitting versions for pulumi SDKs, which is causing issues during build because the locally generated version conflicts with that generated by CI. 

Example: https://github.com/pulumi/pulumi-aws/runs/3681142839

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

Fixes #8033

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by komalali** [comment]
Hey! Looks like you've just commented out the code instead of actually reverting the original change. Is there a reason for that?

**Comment by iwahbe** [comment]
@komalali yes. 2 Reasons. 
1. Hitting the revert button didn't work. It produced 
> Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged.
2. A lot of our codegen tests rely on the `dotnet` part of the change, as `dotnet` SDKs rely on `version.txt` to build.

**Comment by komalali** [comment]
Okay, for now I suggest that you:
* `git checkout master`
* `git pull`
* `git checkout -b revert-version-pr`
* `git revert 906dce73a1a5e66c9acbaeeaa26b2ee630630ad2`
* Resolve the conflicts (it might just be the changelog)
* Turn off compilation for dotnet for the codegen tests using `SkipCompileCheck`
* push up that PR

You can then take a look at this with fresh eyes tomorrow and work through whatever needs to be worked through.

**Comment by iwahbe** [comment]
Closed in favor of https://github.com/pulumi/pulumi/pull/8035

**Pull request closed without merging**
