### PR TITLE
Print out a 'still working' message every 20 seconds when in non-interactive mode.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/pulumi/pulumi/issues/1602

### CODE REVIEW

**Comment by lukehoban** [comment]
Curious - what does this look like?  Where does the message show up for users?

**Comment by joeduffy** [comment]
TBH, I am much more of a fan of  `........`s than I am `still working` messages.

**Comment by CyrusNajmabadi** [comment]
@joeduffy This is problematic as it affects all printing of future message.  i.e. you don't really want to end up with:

```
Creating resource
..........................................Resource Created
...............................Creating resource
```

**Comment by CyrusNajmabadi** [comment]
> Curious - what does this look like? Where does the message show up for user

It will look like this:

```
 *  aws:lambda:Function subscription-queue-subscription unchanged 
 *  aws:lambda:Permission subscription unchanged 
 *  aws:lambda:EventSourceMapping subscription unchanged 
Still working...
Still working...
 -  aws:sqs:Queue queue11 deleting.. 
 -  aws:sqs:Queue queue11 deleted
```

**Comment by CyrusNajmabadi** [comment]
IMproved with https://github.com/pulumi/pulumi/pull/1629.  #closed

**Pull request merged**
