### PR TITLE
[codegen/dotnet] Fix codegen for functions with secret parameters

### LINKED ISSUE #10838: [codegen/dotnet] Generated code for functions with secret parameters fails to compile
### What happened?

With the change in https://github.com/pulumi/pulumi-terraform-bridge/pull/612 sensitive properties in datasources, resources and provider variables are all marked secret. However, when this is set for function inputs we get compilation failures in dotnet.

### Steps to reproduce

With the following change to the schema:
```
"gcp:kms/getKMSSecretCiphertext:getKMSSecretCiphertext": {
             "inputs": {
                 "description": "A collection of arguments for invoking getKMSSecretCiphertext.\n",
                 "properties": {
                     "cryptoKey": {
                        "type": "string"
                     },
                     "plaintext": {
                         "type": "string",
+                        "secret": true
                     }
                 },
                 "type": "object",
                 "required": [
                     "cryptoKey",
                     "plaintext"
                 ]
             },
             "outputs": {
                 "description": "A collection of values returned by getKMSSecretCiphertext.\n",
                 "properties": {
                     "ciphertext": {
                        "type": "string"
                     },
                     "cryptoKey": {
                         "type": "string"
                     },
                     "id": {
                         "type": "string",
                         "description": "The provider-assigned unique ID for this managed resource.\n"
                     },
                     "plaintext": {
-                        "type": "string"
+                        "type": "string",
+                        "secret": true
                     }
                 },
                 "type": "object",
                 "required": [
                     "ciphertext",
                     "cryptoKey",
                     "plaintext",
                     "id"
                 ]
             }
         },
```

Codegen generates the following dotnet code:
```
         /// <summary>
         /// The plaintext to be encrypted
         /// </summary>
         [Input("plaintext", required: true)]
-        public string Plaintext { get; set; } = null!;
+        private string? _plaintext;
+        public string? Plaintext
+        {
+            get => _plaintext;
+            set
+            {
+                var emptySecret = Output.CreateSecret(0);
+                _plaintext = Output.Tuple<string?, int>(value, emptySecret).Apply(t => t.Item1);
+            }
+        }
```

In Go

### Expected Behavior

Generate valid code.

### Actual Behavior

Generates code that doesn't compile:
```
         /// <summary>
         /// The plaintext to be encrypted
         /// </summary>
         [Input("plaintext", required: true)]
-        public string Plaintext { get; set; } = null!;
+        private string? _plaintext;
+        public string? Plaintext
+        {
+            get => _plaintext;
+            set
+            {
+                var emptySecret = Output.CreateSecret(0);
+                _plaintext = Output.Tuple<string?, int>(value, emptySecret).Apply(t => t.Item1);
+            }
+        }
```

### Output of `pulumi about`

_No response_

### Additional context

This blocks https://github.com/pulumi/pulumi-terraform-bridge/issues/599

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
The non-`Output<T>` returning functions take parameters as plain values, which cannot be made secrets. Before this change, .NET codegen was trying to convert the inputs into secrets (for any input property that is marked as a `secret` in the schema), but this would error during compilation because the plain types are not `Input<T>`.

Note: Arguably, for the `Output<T>` returning functions, we could force any secret input properties to be secrets since they are typed as `Input<T>`, and similarly, force the resulting `Output<T>` to be a secret if any of the output properties are marked as secret. But that is something we could consider doing subsequently, as it would be a change for all languages. Tracking this in #10841.

Fixes #10838

### CODE REVIEW

**Review by viveklak — APPROVED** [review]

**Comment by justinvp** [comment]
bors retry

**Comment by justinvp** [comment]
bors try

**Comment by justinvp** [comment]
bors merge

**Comment by justinvp** [comment]
bors merge

**Comment by justinvp** [comment]
bors merge

**Pull request merged**
