### PR TITLE
Remove extra tab that convert TS outputs in JSON file

### LINKED ISSUE #10776: Extra spacing in generated (`pulumi convert`ed) TypeScript projects
### What happened?

This is a minor thing, but when I run `pulumi convert` to generate a TypeScript program, the rendered `package.json` and `tsconfig.json` files have an extra level of indentation:  

image

Looks like they're tabs, too, so we should probably convert to spaces.

### Steps to reproduce

Run `pulumi convert --language typescript` on any project.

### Expected Behavior

Spacing that looks more like this:

image

### Actual Behavior

Described above.

### Output of `pulumi about`

```
CLI          
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Host     
OS       darwin
Version  12.5.1
Arch     x86_64
```

### Additional context

Just my thanks in advance! 🙌 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by mikhailshilkov**
# Description

Fixes #10776

Examples of generated files:

tsconfig.js:

```json
{
	"compilerOptions": {
		"strict": true,
		"outDir": "bin",
		"target": "es2016",
		"module": "commonjs",
		"moduleResolution": "node",
		"sourceMap": true,
		"experimentalDecorators": true,
		"pretty": true,
		"noFallthroughCasesInSwitch": true,
		"noImplicitReturns": true,
		"forceConsistentCasingInFileNames": true
	},
	"files": [
		"index.ts",
	]
}
```

package.json

```json
{
	"name": "simple-yaml",
	"devDependencies": {
		"@types/node": "^14"
	},
	"dependencies": {
		"typescript": "^4.0.0",
		"@pulumi/pulumi": "^3.0.0",
		"@pulumi/aws-native": "*"
	}
}
```

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

**Comment by mikhailshilkov** [comment]
bors merge

**Comment by mikhailshilkov** [comment]
bors retry

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
