### PR TITLE
Remove MaybeNull from Output/Input.Create to avoid spurious warnings

### PR DESCRIPTION
**Pull request by t0yv0**
Addresses https://github.com/pulumi/pulumi/issues/6295

### CODE REVIEW

**Comment by t0yv0** [comment]
Let me check if the user can promote `null` to Output<T> before and after.

**Comment by t0yv0** [comment]
Looks like the compiler rejects an attempt to pass null into Output.Create both before and after the change, so this is a no-op in that sense.

**Comment by mikhailshilkov** [comment]
> Looks like the compiler rejects an attempt to pass null into Output.Create both before and after the change

Hmm, how so? `Output.Create((string?)null);` is valid code, AFAIK.

**Comment by t0yv0** [comment]
```
	var mout = Output.Create<string>((string?)null);
	// warning CS8625: Cannot convert null literal to non-nullable reference type. 

```

It's valid for compilation but does generate a warning. I believe this warning stays before and after the PR.

**Comment by t0yv0** [comment]
And ```
	string? boom = null;
	var mout = Output.Create<string>(boom);

	// warning CS8604: Possible null reference argument for parameter 'value' in 'Output<string> Output.Create<string>(string value)'
```

**Comment by mikhailshilkov** [comment]
> `var mout = Output.Create<string>((string?)null);`

Are you missing `?` in the type? `var mout = Output.Create((string?)null);` gives me no warnings (and it shouldn't, it's a valid thing to do).

**Comment by t0yv0** [comment]
Ah, right, so that's the same as

```
	Output<string?> mout = Output.Create((string?)null);

```

right?

This gives me no warnings.

**Comment by mikhailshilkov** [comment]
Okay. Next question - why did we have `MaybeNull` in the first place? I'd love to understand what it solved and why we don't need this anymore.

**Comment by t0yv0** [comment]
#3399 introduced it. Any ideas?

**Review by mikhailshilkov — APPROVED** [review]
The best hypothesis I have is that the intention was to use `AllowNull` in those cases instead of `MaybeNull`. `MaybeNull` seems to be intended for return types, so our usage doesn't look valid. I don't quite understand when `AllowNull` would be needed - I'd appreciate an explanation if you have it, but otherwise the change LGTM.

**Comment by mikhailshilkov** [comment]
Btw, I'd still change-log this fix as the consequence is externally visible.

**Comment by t0yv0** [comment]
OK I dug into the `AllowNull` attribute a little bit. This attribute lets users to defeat the null-checker when "we know what we are doing". Specifically consider the following program that currently fails on Pulumi:

```
            string? foo = null;
            Output<string> mout = Output.Create<string>(foo);
            /// error CS8604: Possible null reference argument for parameter 'value' in 'Output<string> Output.Create<string>(string value)'
```

IN current version of Pulumi we would expect the user to fix this to:

```
            string? foo = null;
            Output<string?> mout = Output.Create<string?>(foo);
```

However, if we wanted to accept the original program, and say generate an output that resolves to null although it promises to be Output<string> with a non-nullable string, we could use AllowNull attribute. The AllowNull needs to propagate deeper into the SDK, here is a demonstration of how that might look like:

https://github.com/pulumi/pulumi/pull/6601

**Comment by t0yv0** [comment]
Now, I have some FP/F# bias so in my book that sounds like a bad idea to add AllowNull. I would vote for default behavior here. If necessary the user can defeat the null checker outside of the SDK - in the user code.

**Pull request merged**
