### PR TITLE
[display] Overwrite terminal contents

### LINKED ISSUE #11691: Intense CLI output flickering during `pulumi up`
### What happened?

This issue is related to https://github.com/pulumi/customer-support/issues/837 which shows intense flickering during `pulumi up`.

It appears since upgrading to 3.49.0, there's an increased flicker in the CLI output during a stack update. I've tried to reproduce the issue with some result (between `00:00:06s` and `00:00:10s`).

https://user-images.githubusercontent.com/1161681/208568301-87c244ca-68a0-4d61-b8db-7ef26221828c.mp4

### Steps to reproduce

Having a stack with a lot of resources (100s+ resources) could be a exacerbating factor.

### Expected Behavior

The terminal should refresh with little to no flicker.

### Actual Behavior

Very intense flicker as shown in the videos from the issue referenced above.

### Output of `pulumi about`

```
CLI          
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.22.0
aws         5.10.0
eks         1.0.0
kubernetes  3.22.2
kubernetes  3.20.2
nodejs      unknown

Host     
OS       debian
Version  11.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.12.1'

Current Stack: menfin/aws-ts-eks-grafana/dev

TYPE                                                        URN
pulumi:pulumi:Stack                                         urn:pulumi:dev::aws-ts-eks-grafana::pulumi:pulumi:Stack::aws-ts-eks-grafana-dev
pulumi:providers:aws                                        urn:pulumi:dev::aws-ts-eks-grafana::pulumi:providers:aws::default_5_22_0
custom:resource:VPC                                         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC::eks-grafana
pulumi:providers:aws                                        urn:pulumi:dev::aws-ts-eks-grafana::pulumi:providers:aws::default_5_10_0
custom:resource:EKS                                         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$custom:resource:EKS::eks-grafana
aws:ec2/vpc:Vpc                                             urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc::eks-grafana-vpc
aws:s3/bucket:Bucket                                        urn:pulumi:dev::aws-ts-eks-grafana::aws:s3/bucket:Bucket::my-terrif-bucket
aws:ec2/internetGateway:InternetGateway                     urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::eks-grafana-igw
aws:iam/role:Role                                           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$custom:resource:EKS$aws:iam/role:Role::eks-grafana-role
eks:index:Cluster                                           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster::eks-grafana-cluster
aws:ec2/securityGroup:SecurityGroup                         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/securityGroup:SecurityGroup::eks-grafana-public-sg-ssh
aws:ec2/routeTable:RouteTable                               urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::eks-grafana-rt
aws:iam/rolePolicyAttachment:RolePolicyAttachment           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$custom:resource:EKS$aws:iam/role:Role$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-grafana-role-policy-2
aws:iam/rolePolicyAttachment:RolePolicyAttachment           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$custom:resource:EKS$aws:iam/role:Role$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-grafana-role-policy-1
aws:iam/rolePolicyAttachment:RolePolicyAttachment           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$custom:resource:EKS$aws:iam/role:Role$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-grafana-role-policy-0
eks:index:ServiceRole                                       urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$eks:index:ServiceRole::eks-grafana-cluster-eksRole
aws:ec2/securityGroup:SecurityGroup                         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::eks-grafana-cluster-eksClusterSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-grafana-cluster-eksClusterInternetEgressRule
aws:iam/role:Role                                           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::eks-grafana-cluster-eksRole-role
aws:iam/rolePolicyAttachment:RolePolicyAttachment           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-grafana-cluster-eksRole-4b490823
aws:ec2/subnet:Subnet                                       urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::eks-grafana-public-subnet-ap-southeast-2c
aws:ec2/subnet:Subnet                                       urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::eks-grafana-private-subnet-ap-southeast-2c
aws:ec2/routeTableAssociation:RouteTableAssociation         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::eks-grafana-public-rt-assoc-ap-southeast-2c
aws:ec2/subnet:Subnet                                       urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::eks-grafana-private-subnet-ap-southeast-2a
aws:ec2/subnet:Subnet                                       urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::eks-grafana-public-subnet-ap-southeast-2b
aws:ec2/subnet:Subnet                                       urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::eks-grafana-private-subnet-ap-southeast-2b
aws:ec2/subnet:Subnet                                       urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::eks-grafana-public-subnet-ap-southeast-2a
aws:ec2/routeTableAssociation:RouteTableAssociation         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::eks-grafana-public-rt-assoc-ap-southeast-2b
aws:ec2/routeTableAssociation:RouteTableAssociation         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::eks-grafana-public-rt-assoc-ap-southeast-2a
aws:eks/cluster:Cluster                                     urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/cluster:Cluster::eks-grafana-cluster-eksCluster
pulumi:providers:kubernetes                                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$pulumi:providers:kubernetes::eks-grafana-cluster-provider
pulumi:providers:kubernetes                                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$pulumi:providers:kubernetes::eks-grafana-cluster-eks-k8s
aws:iam/openIdConnectProvider:OpenIdConnectProvider         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:iam/openIdConnectProvider:OpenIdConnectProvider::eks-grafana-cluster-oidcProvider
aws:ec2/securityGroup:SecurityGroup                         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::eks-grafana-cluster-nodeSecurityGroup
pulumi:providers:eks                                        urn:pulumi:dev::aws-ts-eks-grafana::pulumi:providers:eks::default
kubernetes:core/v1:Namespace                                urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$kubernetes:core/v1:Namespace::eks-grafana
kubernetes:storage.k8s.io/v1:StorageClass                   urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$kubernetes:storage.k8s.io/v1:StorageClass::eks-grafana-cluster-gp2
kubernetes:core/v1:ConfigMap                                urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$kubernetes:core/v1:ConfigMap::eks-grafana-cluster-nodeAccess
aws:ec2/securityGroupRule:SecurityGroupRule                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-grafana-cluster-eksClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-grafana-cluster-eksNodeIngressRule
eks:index:VpcCni                                            urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$eks:index:VpcCni::eks-grafana-cluster-vpc-cni
aws:ec2/securityGroupRule:SecurityGroupRule                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-grafana-cluster-eksExtApiServerClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-grafana-cluster-eksNodeClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-grafana-cluster-eksNodeInternetEgressRule
aws:iam/role:Role                                           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$custom:resource:EKS$aws:iam/role:Role::eks-grafana-ca-role
kubernetes:core/v1:ServiceAccount                           urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$kubernetes:core/v1:ServiceAccount::cluster-autoscaler
aws:eks/nodeGroup:NodeGroup                                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup::eks-grafana-cluster-ng
kubernetes:helm.sh/v3:Chart                                 urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart::eks-grafana-chart-cluster-autoscaler
kubernetes:policy/v1beta1:PodDisruptionBudget               urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart$kubernetes:policy/v1beta1:PodDisruptionBudget::kube-system/eks-grafana-chart-cluster-autoscaler-aws-cluster-autoscaler
kubernetes:rbac.authorization.k8s.io/v1:Role                urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::kube-system/eks-grafana-chart-cluster-autoscaler-aws-cluster-autoscaler
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding  urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::eks-grafana-chart-cluster-autoscaler-aws-cluster-autoscaler
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::kube-system/eks-grafana-chart-cluster-autoscaler-aws-cluster-autoscaler
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole         urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::eks-grafana-chart-cluster-autoscaler-aws-cluster-autoscaler
kubernetes:apps/v1:Deployment                               urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::kube-system/eks-grafana-chart-cluster-autoscaler-aws-cluster-autoscaler
kubernetes:core/v1:Service                                  urn:pulumi:dev::aws-ts-eks-grafana::custom:resource:VPC$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup$kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::kube-system/eks-grafana-chart-cluster-autoscaler-aws-cluster-autoscaler


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi

Dependencies:
NAME                VERSION
@pulumi/aws         5.22.0
@pulumi/eks         1.0.0
@pulumi/kubernetes  3.22.2
@pulumi/pulumi      3.48.0
@types/netmask      1.0.30
netmask             2.0.2
@types/node         18.11.10
```

### Additional context

* maybe related to https://github.com/pulumi/pulumi/issues/7823

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by pgavlin**
Instead of clearing the contents of the display with each frame,
overwrite its contents by clearing to the end of each line prior to a
newline. This should eliminate flickering in the interactive display.

This also eliminates a couple of off-by-one errors that were hampering
usability.

Fixes #11691, https://github.com/pulumi/customer-support/issues/837.

### CODE REVIEW

**Comment by pgavlin** [comment]
There are three commits here. The first contains the actual changes, the second updates the baselines, and the third contains the changelog.

**Comment by AaronFriel** [comment]
Building and running locally to get an idea of the change.

**Comment by pgavlin** [comment]
Added one more commit that hides the cursor in the interactive display, which should eliminate the last of the redraw artifacts.

**Comment by pgavlin** [comment]
> Building and running locally to get an idea of the change.

If you have a service dev stack, refreshing that stack is an excellent case study.

**Review by AaronFriel — APPROVED** [review]
Checked this branch with two terminal environments and two Pulumi programs: an EKS cluster and a pathological example of a docker-buildkit provider logging 100k+ lines and did not observe flickering.

This looks like a substantial improvement.

**Comment by pgavlin** [comment]
bors merge

**Pull request merged**
