### PR TITLE
Don't retry downloads on 403 and 404s responses

### LINKED ISSUE #10801: Don't retry on 403 when downloading a plugin
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

A 403 indicates that the server understood the request, but chooses not to fulfill it. We don't need to continue to retry, since there is no reason to believe that a rejected request will be accepted later.

Related to #10800

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

Fixes #10801

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]
LGTM

**Comment by Frassle** [comment]
LGTM but I wouldn't say this fixes https://github.com/pulumi/pulumi/issues/10801.

**Comment by iwahbe** [comment]
bors retry

**Comment by Frassle** [comment]
bors merge

**Pull request merged**
