### PR TITLE
Support clones from Azure DevOps

### PR DESCRIPTION
**Pull request by squaremo**
In general, go-git can't clone from Azure DevOps, because the latter requires the capabilities multi_ack and multi_ack_detailed, which aren't implemented. However, there's now a workaround, which boils down to this: pretend, for the initial clone, that those capabilities _are_ supported, and expect them not to be used.

(See https://github.com/go-git/go-git/pull/613 for more on this workaround.)

I tried this with a personal Azure DevOps account; an automated test would need either a reliably long-lived Azure DevOps repo, or a test server that can mimic Azure DevOps' particular capabilities. I'm open to suggestions!

### CODE REVIEW

**Comment by squaremo** [comment]
By the way, `go mod tidy` changes a loooot of things and makes me nervous. Is there something going on with that?

**Comment by abhinav** [comment]
> By the way, `go mod tidy` changes a loooot of things and makes me nervous. Is there something going on with that?

Try running `./scripts/tidy.sh`, not `go mod tidy`. scripts/tidy runs with `-compat=1.18`; the system `go mod tidy` is probably running with 1.19.

**Comment by RobbieMcKinstry** [comment]
Looks like we need two actions to get this in:
1. Run `make lint` and address the (potential) errors. I'm going off of the CI error message here.
2. Add a changelog entry.

**Comment by RobbieMcKinstry** [comment]
@squaremo did you make the changes to `go.sum` that you wanted to make? If so, one of us can merge with `bors r+`

**Pull request merged**
