### PR TITLE
Make convert more lenient

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Fixes https://github.com/pulumi/pulumi/issues/13117

This adds a new "--strict" flag to `pulumi convert` which defaults to false. When strict is NOT set we bind the PCL with the extra options of `SkipResourceTypechecking`, `AllowMissingVariables`, and `AllowMissingProperties`. This will change some errors to warnings in code generation.

The `strict` flag is sent over the gRPC interface to the Go/Node plugins for their `GenerateProject` methods as they have to do PCL binding plugin side currently.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Zaid-Ajaj — COMMENTED** [review]
This change will only make binding the root/main entry program lenient. The options `SkipResourceTypechecking`, `AllowMissingVariables` and `AllowMissingProperties` are _NOT_ propagated to the component program binder, see implementation of `ComponentProgramBinderFromFileSystem` where it uses `BindProgram` using a static set of options. 

The easiest way to propagate these through is extending `ComponentProgramBinderFromFileSystem` to accept extra options that are then added to the bind options when binding the component program

**Comment by Frassle** [comment]
> This change will only make binding the root/main entry program lenient.

Thanks for that insight! I'll get that fixed up.

**Comment by Frassle** [comment]
> The easiest way to propagate these through is extending ComponentProgramBinderFromFileSystem to accept extra options that are then added to the bind options when binding the component program

Found an even easier option. Just pass the parent binders settings down via `ComponentProgramBinderArgs`.

**Review by Zaid-Ajaj — APPROVED** [review]
Looks great now! The error in CI `error: unrecognized source "pcl"` maybe because the branch needs rebasing

**Comment by justinvp** [comment]
I rebased and force pushed.

**Comment by Frassle** [comment]
Ah no seems I missed a PULUMI_DEV check in https://github.com/pulumi/pulumi/pull/13118

**Comment by Frassle** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by Frassle** [comment]
bors cancel

Looks like there's a bug in `DetectProjectPathFrom` that this flagged up

**Comment by Frassle** [comment]
bors merge

**Pull request merged**
