### PR TITLE
Disable default completion command

### PR DESCRIPTION
**Pull request by EthanOrlander**
# Description

Fixes  [7841](https://github.com/pulumi/pulumi/issues/7841)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by emiliza** [comment]
Hi @EthanOrlander thanks for your contribution! 

Can you address the lint and test failures [here](https://github.com/pulumi/pulumi/runs/3501180671?check_suite_focus=true)?

**Comment by EthanOrlander** [comment]
Thanks @emiliza! This was failing because Cobra's CompletionOptions field for Command was added in release 1.2.0, and Pulumi is using 1.0.0. [I've made a PR](https://github.com/pulumi/pulumi/pull/7950) to upgrade the Cobra version. I've rebased this branch onto the upgraded branch.

**Pull request closed without merging**
