### PR TITLE
Update YAML invoke syntax for docs

### PR DESCRIPTION
**Pull request by aq17**
# Description

Fixes pulumi-yaml https://github.com/pulumi/pulumi-yaml/issues/399

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]
You'll need to regenerate our doc tests. Otherwise LGTM!

**Comment by aq17** [comment]
bors merge

**Comment by aq17** [comment]
bors retry

**Comment by aq17** [comment]
bors retry

**Pull request merged**
