### PR TITLE
Document issue

### PR DESCRIPTION
**Pull request by Harshalyadav**
# Description

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
Hey thanks for the suggestion but "as Code" is the correct phrasing for this, not "as a Code". I'm not 100% sure if "use" or "uses" is more correct for the other suggestion, but I think given the multiple objects it should be "uses" as you've suggested.
If you want to revert the "as a Code" change, I'll get someone extra to just double check my grammar thinking about "uses" and maybe that can be merged.

**Comment by Harshalyadav** [comment]
ok, I will change my push request "as a code" to "as code".

**Comment by abhinav** [comment]
@Harshalyadav Thanks for the fix! Please rebase your change and squash your commits. Our CI prefers a linear history.

**Comment by Harshalyadav** [comment]
@abhinav Ok, I rebase and squash my commit

**Comment by abhinav** [comment]
Thanks for the contribution @Harshalyadav!
To save time, we pulled your change into #12364.
Closing in favor of #12364.

**Pull request closed without merging**
