### PR TITLE
Use black code formatter for the python sdk

### LINKED ISSUE #8251: Use a formatter for our `python` code.
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

To have consistent code style, we should enforce a formatter on our python code. This would add a style linter to python, and prevent developers from needing to think about style. 

Prior art:
- Gofmt for our go code.

### Affected area/feature

The Python SDK.

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

The first commit consists of manual changes:
- Makefile
- requirments.txt
- ect

The second commit is the result of running `make format` in sdk/python. I also moved some comments around to fix lints. 

Fixes #8251

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]
LGTM

**Comment by t0yv0** [comment]
Just thikning out loud - this does NOT make pulumi wheel dependent on black right? Only dev-time dependency?

**Review by t0yv0 — APPROVED** [review]
Check in earlier rather than later a it impacts other PRs.

**Review by pgavlin — APPROVED** [review]
This is awesome.

**Comment by iwahbe** [comment]
This is purely a dev dependency. The Pulumi wheel does not depend on black.

**Pull request merged**
