### PR TITLE
Remove Prefix suffix on Pulumi.automation Package

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #6401

### CODE REVIEW

**Review by mikhailshilkov — APPROVED** [review]
Why not merge it to the feature-3.0 branch?

**Comment by mikhailshilkov** [comment]
Actually, we should get rid of `dotnet pack Pulumi.Automation/Pulumi.Automation.csproj` completely by changing [this line](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj#L6) to true

**Review by mikhailshilkov — CHANGES_REQUESTED** [review]
Actually, we should get rid of `dotnet pack Pulumi.Automation/Pulumi.Automation.csproj` completely by changing [this line](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj#L6) to true

**Comment by mikhailshilkov** [comment]
We should also copy the contents of [this file](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi.Automation/PublicAPI.Unshipped.txt) to `Shipped.txt`

**Comment by stack72** [comment]
All feedback fixed up @mikhailshilkov

**Pull request merged**
