### PR TITLE
[codegen/docs] - Improve resource doc titles

### PR DESCRIPTION
**Pull request by komalali**
Fixes: https://github.com/pulumi/docs/issues/4629

### CODE REVIEW

**Comment by komalali** [comment]
Looking into the downstream codegen issues.

**Comment by pgavlin** [comment]
That was fast :D

**Review by pgavlin — APPROVED** [review]

**Comment by lukehoban** [comment]
cc @davidwrede and @zchase for potential SEO impact (both positive and potentially negative?)

**Comment by zchase** [comment]
There shouldn't be a negative impact from this change. There can be some positive movement in our rankings for specific keywords but since we are just removing more "general" words from the title, I wouldn't expect a major shift. For example, we rank 8th for the term `aws_lambda_permission` and this change could help elevate the change, but probably by only a spot or two.

From an SEO UX perspective, I think cleaning up the titles is a net positive change. The title is fairly noisy in its current state so this should help clear up exactly what the pages are for.

**Comment by davidwrede** [comment]
+1 to everything @zchase said. :)

**Review by davidwrede — APPROVED** [review]

**Pull request merged**
