### PR TITLE
Reformat all Go code with gofmt 1.19 to avoid linter failures.

### PR DESCRIPTION
**Pull request by thomas11**
Also manually re-wrap some long lines because the "lll" linter now complains about them being longer than 120 chars.

# Description

Go 1.19 introduces changes to gofmt for some kinds of comments. These changes are not publicly announced in the Go changelog and may be a regression. Possibly related: https://github.com/golang/go/issues/52605

The  changing comments trip golangci-lint. Note that even using Go 1.18 with the latest golangci-lint, built on 1.19, fails.

Reformatting the affected comments with gofmt 1.19 fixes this on Go 1.19. Go 1.18 still works since its gofmt accepts the 1.19-style comments.

Related: #10317 

This PR is annoying because it touches so much code, possibly making merging other open PRs tricky. I'm putting it out there for review so we can discuss alternatives.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by AaronFriel** [comment]
I'll spare @stack72 and @jkisk the toil of reviewing here, as I'm the primary for issues like this this week. Thanks for taking this! Will take a look soon.

@Zaid-Ajaj if this is blocking your PRs or would cause trunk to fail overnight, you're welcome to review. I'd like to carefully review the comments and make fixups because it does look like it can mangle code snippets and pseudocode.

**Comment by thomas11** [comment]
@stack72, @AaronFriel I could use some pointers on investigating the workflow failures. Most, e.g. codegen/random, fail with

> ../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.26.1/pkg/tf2pulumi/il/plugin_info.go:148:18: assignment mismatch: 3 variables but workspace.GetPluginPath returns 2 values

**Comment by iwahbe** [comment]
> > ../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.26.1/pkg/tf2pulumi/il/plugin_info.go:148:18: assignment mismatch: 3 variables but workspace.GetPluginPath returns 2 values

This is a known issue right now, and unrelated to your PR.

**Comment by AaronFriel** [comment]
@thomas11 Once #10624 is in, I'll look at rebasing this and getting it in as a follow-up. That PR, 10624, starts to define practices for us to test against a matrix of language versions and determine which tests should run or not on each (implementing #6110).

**Comment by RobbieMcKinstry** [comment]
@abhinav Can we close this PR now that we've reformatted the remaining files?

**Comment by abhinav** [comment]
Yep! Closing.

**Pull request closed without merging**
