### PR TITLE
Remove the GitHub pull request template

### PR DESCRIPTION
**Pull request by lunaris**
Pull request descriptions are always important. In the case of this repository, they are doubly important since we use a merge queue configured to squash commits and use pull request descriptions as squashed commit messages. This means that the most beautiful commit messages in the world mean nothing if they don't make it uncontaminated into a pull request description.

Unfortunately, contamination is the name of the game with our current pull request template. While designed with good intentions -- helping contributors ensure that they have formatted, linted, tested, and described their code in a changelog entry, it comes with a serious downside. Its HTML comments and checklist entries make it into our Git commit history unless meticulously cleaned out by every contributor, making for an ugly commit log full of noise and bloat. Given that we now have tooled workflows to address these risks*, it's time to remove it and save our commit log from future corruption.

*The exception is the Pulumi Cloud API notice, but this commit argues that this checklist item is both uncommon and has been ineffective in helping address this risk.

### CODE REVIEW

**Review by tgummerer — APPROVED** [review]
I'm personally strongly in favor of this.  We should probably leave this open a while longer so everyone gets the chance to take a look before merging it.

**Comment by julienp** [comment]
I am also in favor of this.

Maybe we can have a bot post a message about PR guidelines. Or we could strip down the PR template to point to a section in contributing.md.

**Review by iwahbe — APPROVED** [review]
❤️

**Review by Frassle — APPROVED** [review]
+1

**Review by justinvp — APPROVED** [review]
👍

**Pull request merged**
