### PR TITLE
Delete CHANGELOG_PENDING.md

### PR DESCRIPTION
**Pull request by AaronFriel**

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors retry

**Comment by AaronFriel** [comment]
bors retry

**Comment by AaronFriel** [comment]
bors merge

**Review by dixler — APPROVED** [review]

**Comment by AaronFriel** [comment]
bors retry

**Pull request merged**
