### PR TITLE
Make ts-node and typescript peer dependencies

### PR DESCRIPTION
**Pull request by dmattia**
# Description

Fixes https://github.com/pulumi/pulumi/issues/8177
Related to https://github.com/pulumi/pulumi/issues/4876

Newer ts-node and typescript versions can make configurations not work with Pulumi at all right now. In my case, I am developing in a monorepo that uses newer versions of ts-node and typescript, and these older versions cause my code to not be able to run. See the more detailed descriptions I left in those two Issues linked above for what exactly is breaking

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

This is not an application code change

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [x] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

I'm not sure where to update this version, but this deserves probably a minor bump in the node sdk

### CODE REVIEW

**Comment by lukehoban** [comment]
It does seem like a good idea to allow these dependencies to be controlled by consumers of this library.  That said, I suspect this change as-is will break all existing Pulumi+TypeScript users, as nothing will provide the peer dependencies.  For new users, we would need to include versions of these dependencies in our templates.  But for existing users, this would require every one of them to make edits to their own package.json in order to adopt this.  I suspect we could not take a change like that until 4.0, unless we could figure out a way to avoid that breaking change.

Unfortunately, neither npm or yarn supports the ability to provide a default value, but allow consumers to override this, which is what we really want here to ensure this can be made more flexibile without a breaking change.  https://github.com/yarnpkg/berry/issues/1001 is tracking what appears to be the needed feature in yarn, but does not look to be imminent (and we likely couldn't rely on any new release of these tools as they wouldn't be widely adopted yet).  

@pgavlin @justinvp @dmattia Any thoughts on how we might be able to achieve this without a breaking change?  Or if not, is this something we should consider for 4.0?

**Comment by dmattia** [comment]
If anyone else using yarn v2 wants to use this fork, you can by setting a resolution to it in your top level `package.json` like:

```json
"resolutions": {
    "@pulumi/pulumi": "exec:./use-pulumi-fork.js"
  },
```

And then create a file `use-pulumi-fork.js` with the contents:

```javascript
/**
 * Script to force yarn v2 to use the dmattia/pulumi fork of the Pulumi NodeJS SDK.
 *
 * Because pulumi/pulumi does not have a package.json file in its root, yarn (and npm)
 * do not know how to import it as a dependency from a normal git reference.
 *
 * This script just points to the dmattia/pulumi Github repository and builds the node
 * archive from the `/sdk/nodejs` folder inside the fork.
 *
 * Pull Request to track progress of the fork: https://github.com/pulumi/pulumi/pull/8199
 */

const pathToRepo = path.join(execEnv.tempDir, 'repo');
const pathToSdkDir = path.join(pathToRepo, 'sdk/nodejs');
const pathToArchive = path.join(execEnv.tempDir, 'archive.tgz');

// Clone the repository
child_process.execFileSync(`git`, [
  `clone`,
  `git@github.com:dmattia/pulumi`,
  pathToRepo,
]);

// Install the dependencies
child_process.execFileSync(`yarn`, [`install`], {
  cwd: pathToSdkDir,
});

// Pack a specific workspace
child_process.execFileSync(`yarn`, [`pack`, `--out`, pathToArchive], {
  cwd: pathToSdkDir,
});

// Send the package content into the build directory
child_process.execFileSync(`tar`, [
  `-x`,
  `-z`,
  `--strip-components=1`,
  `-f`,
  pathToArchive,
  `-C`,
  execEnv.buildDir,
]);
```

**Comment by PupoSDC** [comment]
Hello!

I'm just giving this a nudge to try to see if thsi does not get forgotten ;) 

TS 3.7 is getting pretty outdated, and we are struggling quite a bit migrating some code to use pulumi as it uses features that 3.7 didn't have resulting in some cryptic errors that only show up once you do "pulumi up".

it would be great for DX if this could be merged at some point!

cheers!

**Comment by EvanBoyle** [comment]
related to https://github.com/pulumi/pulumi/issues/7184

**Comment by dmattia** [comment]
@EvanBoyle @lukehoban Could I get a clarification on why this PR was closed? This PR is certainly related to issue https://github.com/pulumi/pulumi/issues/7184, as I commented myself in https://github.com/pulumi/pulumi/issues/7184#issuecomment-983831283, as it is an attempted solution.

I've been using a fork of Pulumi with this change for a few months now (https://www.npmjs.com/package/@transcend-io/pulumi/v/1.0.5) and it gets around the problems #7184 mentions and is the only solution I have right now to make typechecking work with newer typescript/ts-node versions.

**Comment by dmattia** [comment]
Re-opened fixed up version in https://github.com/pulumi/pulumi/pull/10122

**Pull request closed without merging**
