### PR TITLE
[sdkgen/python] `_configure` now handles original prop names

### LINKED ISSUE #14151: Python SDK gen regression in supporting incorrectCase
### What happened?

During a routine bridge update (v3.60.1 to v3.61.0) for pulumi-gcp https://github.com/pulumi/pulumi-gcp/pull/1256 web server-py-old acceptance test started failing.

```
  TypeError: _configure() got an unexpected keyword argument 'initializeParams'
```

The line of interest is here:

https://github.com/pulumi/pulumi-gcp/blob/2e128d1f37edf38156e566dd5038c8b5aa1169b6/examples/webserver-py-old/__main__.py#L49-#L49

Note the code uses incorrectCase:

```
    boot_disk={
        "initializeParams": {
            "image": "debian-cloud/debian-11",
        },
    },

```

Fixing it to correct_case can work around the issue:

```
    boot_disk={
        "initialize_params": {
            "image": "debian-cloud/debian-11",
        },
    },
```

Related issues:

- https://github.com/pulumi/pulumi/pull/13825
- https://github.com/pulumi/home/issues/3125

### Example

See above.

### Output of `pulumi about`

Bridge v3.61.0 affected.

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #14239: Python SDK gen regression in supporting underscored kwargs
### What happened?

During a routine pulumi/pulumi update (v3.81.0 to v3.88.1) for pulumi-kubernetes https://github.com/pulumi/pulumi-kubernetes/pull/2607/files our Python acceptance tests started failing.

```
Traceback (most recent call last):
  File "./__main__.py", line 29, in <module>
    service = Service.get("kube-api", "kubernetes")
  File "/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/sdk/python/bin/pulumi_kubernetes/core/v1/Service.py", line 334, in get
    return Service(resource_name, opts=opts, __props__=__props__)
  File "/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/sdk/python/bin/pulumi_kubernetes/core/v1/Service.py", line 273, in __init__
    ServiceInitArgs._configure(_setter, **kwargs)
TypeError: _configure() got an unexpected keyword argument '__props__'
```

Note that all of our routine update PRs failed, with the next best version at v3.82.1 that doesn't result in test failures.

### Example

https://github.com/pulumi/pulumi-kubernetes/actions/runs/6419332278/job/17429320403?pr=2597

### Output of `pulumi about`

pulumi/pulumi v3.88 affected.

### Additional context

Related PRs/issues:

- https://github.com/pulumi/pulumi/issues/14151
- https://github.com/pulumi/pulumi/pull/14235

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Python SDK generation's `_configure` method now supports setters of the
property name based on its original name.

Now supports:
```python
Foo("my-foo", propName=10)
```

Instead of just:
```python
Foo("my-foo", prop_name=10)
```

Fixes #14151
Fixes #14239

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Comment by Frassle** [comment]
I'm not sure how I feel about this...
When I saw https://github.com/pulumi/pulumi/issues/14151 I considered it a programgen bug, we shouldn't have emitted a python program that uses the camelCase names.
Feels like the right fix is to fix that.

But it might _also_ make sense to make this change to add another place in the python SDK to try and handle both snake_case and camelCase names, like we do in property getters and resource options like ignore_changes. But it is a bit sad that we have so many places trying to handle both kinds rather than the SDK just being consistent that names are snake_case in python.

**Comment by Frassle** [comment]
Also I don't see how this fixes https://github.com/pulumi/pulumi/issues/14239?

**Review by Frassle — APPROVED** [review]
OK so turns out the bad example given here wasn't progamgen'd but manually written, so this was just a regression in property name support.

Given that, looks like this change covers it.
This regression is more good fuel for the argument that sdkgen shouldn't be handling defaults at all though, instead leaving that to providers.

**Comment by t0yv0** [comment]
> This regression is more good fuel for the argument that sdkgen shouldn't be handling defaults at all though, instead leaving that to providers.

IF you ticket this I will upvote it. At least have that as an option in sdkgen.

**Comment by Frassle** [comment]
> IF you ticket this I will upvote it. At least have that as an option in sdkgen.

https://github.com/pulumi/pulumi/issues/14253

**Pull request merged**
