### PR TITLE
Freeze v3.74.0

### PR DESCRIPTION
**Pull request by justinvp**

### CODE REVIEW

**Review by abhinav — APPROVED** [review]

**Review by dixler — APPROVED** [review]

**Comment by justinvp** [comment]
bors merge p=1

**Comment by abhinav** [comment]
bors cancel

Build has already failed.
image

**Comment by abhinav** [comment]
Will add another merge request once #13330 is running. Bors is taking fora bit to start up the build.

**Comment by abhinav** [comment]
bors merge p=1

**Comment by abhinav** [comment]
bors retry

**Comment by justinvp** [comment]
bors retry

**Pull request merged**
