### PR TITLE
[sdk/go] Add support for untagged outputs.

### LINKED ISSUE #4629: [Go SDK] Add serialization support for untyped fields
Add support for an untyped map field that looks something like this:

```go
type CustomResource struct {
    OtherFields pulumi.MapOutput `pulumi:""`
}
```

### PR DESCRIPTION
**Pull request by pgavlin**
With these changes, a resource struct may tag a field with the empty
string. If such a field is present, any resource outputs that were not
unmarshalled into other fields will be unmarshalled into this field,
which must be a `MapOutput`.

Fixes #4629.

### CODE REVIEW

**Comment by pgavlin** [comment]
Another approach would be to add a `MapOutput` field to `ResourceState` that always contains all of the resource's outputs besides its ID and URN. That would allow consumers to meaningfully operate on `Resource` values in a uniform fashion. It would make it slightly more difficult for libraries to add additional ID/URN-like metadata fields, however.

**Comment by pgavlin** [comment]
> I guess I'd just ask about frequency of use. This seems like an edge case, but do we imagine external consumers using this

The major benefit would be that this might enable libraries to more conveniently deal with resources in a generic fashion. At the moment, a package that wants to observe the outputs of an arbitrary resource needs to use reflection to iterate over its fields. Taking the approach I described would allow packages to observe the outputs of an arbitrary `Resource` without reflection.

Although I don't think that this is a common scenario, it would be nice to end up with one way to achieve this. If we take the approach implemented in this PR and add the suggested approach later, we'd end up with two similar but subtly different capabilities, and it might not be clear which to use when.

**Comment by lukehoban** [comment]
> It would make it slightly more difficult for libraries to add additional ID/URN-like metadata fields, however.

Curious - what's an example of a case where someone would (or we have yet encountered a need ourselves to) add a "ID/URN-like metadata field"?

**Comment by pgavlin** [comment]
> Curious - what's an example of a case where someone would (or we have yet encountered a need ourselves to) add a "ID/URN-like metadata field"?

`ApiVersion`, `Kind`, and `Metadata` on the CRD resource definition:
https://github.com/pulumi/pulumi-kubernetes/pull/1125/commits/5eab8861c567464cabb843ffce2bff2b81b6bc5e#diff-4d25f3574f7af6916dacde7a37f85982R37-R48

**Comment by lblackstone** [comment]
@pgavlin Anything left to do here, or is this good to merge?

**Comment by pgavlin** [comment]
This needs a CHANGELOG entry, but it's good to go other than that.

**Pull request merged**
