### PR TITLE
cli: Clean up `pulumi stack` output for non-deployed stacks

### PR DESCRIPTION
**Pull request by AaronFriel**
Rather than display some potentially confusing output, only show the update time and Pulumi version used to deploy it when those values are present.

Improves code readability by following current variable styling.

On an empty stack, the display now appears as:

```
$ pulumi stack
Current stack is dev:
    Owner: friel
Current stack resources (0):
    No resources currently in this stack
```

Instead of:

```
$ pulumi stack
Current stack is dev:
    Last update time unknown
    Pulumi version: ?
    Owner: friel
Current stack resources (0):
    No resources currently in this stack
```

### CODE REVIEW

**Review by susanev — APPROVED** [review]
thank you!!

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
Assuming the test failure here is a flake - will let bors sort it out.

**Pull request merged**
