### PR TITLE
Python Language Host Tests

### PR DESCRIPTION
**Pull request by swgillespie**
This PR is 100% test code. It brings to Python the "language host tests" that we use extensively in Node.

The basic idea behind these tests is that, because we have clean RPC interfaces between the language host and the components it talks to, we can mock out these interfaces and run the real language host on real programs. In particular, these tests provide an implementation of the resource monitor gRPC interface (normally implemented by the Pulumi engine) that is complete enough to test all of the major code paths of a language host without having to resort to real integration tests.

All of the machinery involved here is encapsulated by the `LanghostTest` class in `util.py`. This class derives from `unittest.TestCase` and provides a few methods, the most important of which being:

* `invoke`, called whenever the program being run invokes a data source
* `read_resource`, called whenever the program being run uses `Resource.get`
* `register_resource`, called whenever the program being run creates a resource
* `register_resource_outputs`, called whenever the program creates a component resource that has outputs.

`LanghostTest` provides default implementations of these methods. These methods are ultimately used to, at the start of the test, provide an implementation of the resource monitor gRPC interface that the language host will connect to. As the language being tested creates resources, it will call into our test case. At this point we can perform assertions, create resources with specific properties, throw exceptions, or do basically anything.

I am still in the process of writing new tests and adapting the ones that we have already written for Node. I'll probably keep adding to this PR as I write new ones. Some tests I write are failing; these tests are skipped and the skip reason is set to the bug number.

### CODE REVIEW

**Comment by swgillespie** [comment]
Not sure about reviewers again (I guess it boils down to people who care about python?) but @ellismg I imagine you might be interested in something similar for dotnet when the time comes. I've only written a few tests and they've done a good job so far of shaking out bugs.

**Comment by swgillespie** [comment]
I know what the problem is with these tests, I'll have a fix this afternoon.

**Comment by mmdriley** [comment]
Followed up with @swgillespie and asked if we could do this and put both "sides" of a given test in the same file. He's going to take a look.

**Comment by swgillespie** [comment]
Unfortunately, placing both "sides" of the test in the same file doesn't work for esoteric Python reasons, but I was able to place both "sides" of the test in the same directory in the most recent comment. I think this makes it a lot easier to follow tests.

I also added a `README.md` describing how this stuff works and how to use it.

**Comment by swgillespie** [comment]
Going to go ahead and merge this, let me know if there's anything anyone would like me to change.

**Pull request merged**
