### PR TITLE
[WIP] Initial Yarn v2 support

### PR DESCRIPTION
**Pull request by ringods**
# Current situation

Pulumi still has the following assumptions regarding the NodeJS language run time:

* the main entry point to invoke is `node`
* the Pulumi program is a single NodeJS project with the `node_modules` at the same level

Below are the commands as defined currently in the code:

Setup | What is executed? | Package install & pack
-------|------|-----
Node + NPM | `node` | `npm <command>`
Node + Yarn (PULUMI_PREFER_YARN) | `node` | `yarn <command>`

The commands from the column **What is executed?** are executed by the NodeJS language run time, not by core Pulumi. The commands from the column **Package install & pack** are executed by core Pulumi.

Looking at the current code, the package install is done by core Pulumi, checking for the existence of the `node_modules` folder afterwards.

# Proposal

This document describes a proposal to have full Yarn v2 support in Pulumi. While working on a solution, we will get better Yarn v1 support as a result too.

In general, an abstraction is needed around the concept of a Javascript runtime + a package manager for Javascript/Typescript modules. This abstraction should support the setups mentioned above. But the current Yarn support in Pulumi doesn't handle the following cases:

* [Yarn workspaces](https://yarnpkg.com/features/workspaces) (v1 & v2): multiple Javascript projects can be stored within a Git monorepo, usually as sub folders under a `packages` folder. Via Yarn, all the dependencies are stored in a single shared place to conserve on disk space. It is also much easier to have dependencies between the Javascript projects during development.
* [Yarn v2 Plug'n'Play](https://yarnpkg.com/features/pnp) (v2): PnP implements a totally new mechanism to retrieve and store the dependencies of a Javascript project. Gone is the `node_modules` folder. It is replaced by a cache location containing archives. At run time, modules are loaded via a composite ZIP file system.

Both features are orthogonal to each other and can be easily combined.

The assumptions from the first table are a problem for better NodeJS support. The NodeJS community has multiple package managers besides `npm`: Yarn v1, Yarn v2 and pnpm. I mention the two Yarn versions separately as v2 is substantially different.

With the proper abstraction around a Javascript run time and package manager, Pulumi is more ready for deno support as requested in #3838.

Zooming out from the current implementation, here are the real needs:

* the Pulumi NodeJS language run time must be able to start with the correct
dependencies
* check if an install of the Javascript dependencies was done correctly

For the implementation of the checks above, we should relay to the tools at hand, hence this overview of the commands to run:

Setup | What should be executed? | Package install & pack | Verify installation + parse output
----|----|----|----
Node + NPM | `node` | `npm <command>` | `npm list <pkg>`
Node + Yarn v1 (PULUMI_PREFER_YARN) | `node` | `yarn <command>` | `yarn why <pkg>`
Node + Yarn v2 (PULUMI_PREFER_YARN) | `yarn node` | `yarn <command>` | `yarn why <pkg>`

Yarn v2 introduced its way to start `node` with the correct dependencies: `yarn node`. This has support for the most simple case up to workspaces and Plug'n'Play support.

To verify the installation of the dependencies, we should refrain from hard coding a check for the `node_modules` folder. We should use the correct commands from the package manager at hand and parse the specific output. First, this supports the use of workspaces both in Yarn v1 and v2. Second, it is also the correct way to support PnP.

# Implementation

We know what to execute to get the Yarn v2 support working. The open question is how to implement this. Here is where some help or guide is needed.

Here are some findings from the code and some suggestions to implement the requirements:

* Go dependencies go from `github.com/pulumi/pulumi/pkg/**` to `github.com/pulumi/pulumi/sdk/**`
* I would place the NodeJS runtime abstraction under `sdk/nodejs/cmd/pulumi-language-nodejs`. Core Pulumi as well as the runtime can both use it.
* Refactor the current level of Yarn support to be fully backward compatible. The checks for `PULUMI_PREFER_YARN` and `PULUMI_EXPERIMENTAL` should be moved from `pkg` to `sdk` to become accessible.
* Add the Yarn v2 support behind the `PULUMI_EXPERIMENTAL` flag for the initial implementation.

# Not yet solved

An implementation of the above would integrate Pulumi and Yarn v2 better. There are still things to solve in subsequent tickets:

* Support for calculating the closure of an embedded Lambda function. This requires integration with the [Yarn PnP API](https://yarnpkg.com/advanced/pnpapi)
* The [`dist`](https://github.com/pulumi/pulumi/tree/master/sdk/nodejs/dist) scripts still invoke `node` directly, e.g. for dynamic providers. To be seen how to detect the correct environment.

# Related:

* #3586 
* #1868
* #3520
* #2980

This proposal and implementation has been discussed earlier today with @justinvp on a Zoom call.

### CODE REVIEW

**Comment by ringods** [comment]
@justinvp @stack72 today I have been working on getting that abstraction in. While working on it, I continue to bump into more and more code that has intricate assumption on `node_modules`. E.g. finding the Pulumi plugins is iterating over the `node_modules` folder in Go code to find the plugin binaries. I see the amount of work for this Yarn support increasing beyond the time I have available. 

The key message is: **I have to halt the work here as I my own priorities are in danger. **

I hope someone at Pulumi can take over and get this implemented. Yarn 2 will be released in a final version real soon now and I suspect that more people will start to use it. It is a major improvement over `npm` and `yarn v1`.

**Comment by justinvp** [comment]
> continue to bump into more and more code that has intricate assumption on `node_modules`

@ringods, Bummer! I was afraid that was going to be the case, but was still hopeful you could get a subset of things working that you care most about. Thanks for the initial work here!

**Comment by crubier** [comment]
Any news on this ?

**Comment by leezen** [comment]
If someone in the community would like to pick this up, that would be great! For now, I'm going to close out this PR given its age.

**Pull request closed without merging**
