### PR TITLE
Proposal: PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by komalali**
Adding a minimal PR template

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]
Looks great to me. We have labels for "type of change" but for outside contributors we do not expect them to assign label correct? So they should fill out the checkbox instead?

**Comment by stack72** [comment]
Personally, I'd love it if the user showed the behaviour before and after if this is a bug fix - it's kinda something we ask a lot to get context on the why

**Comment by lblackstone** [comment]
An alternative to consider to the type checkbox would be enforcing GH labels, which can be queried through the API. This can be useful for CHANGELOG automation or operational metrics.

**Comment by komalali** [comment]
@lblackstone @t0yv0 the current labels that would match the "type of change" checkboxes are:
- `impact/breaking`
- `kind/bug` -> (this is the closest to `bug-fix` but is not quite right)
- `kind/enhancement`

Are those the labels we want folks to use here? Or should we create a set of labels for PRs specifically?

**Comment by susanev** [comment]
do we have a contributing document? if so, it might be rad to link to it and add a checklist item for `I have read the contributing document` or similar

**Comment by lblackstone** [comment]
> Are those the labels we want folks to use here? Or should we create a set of labels for PRs specifically?

I think it would be worth standardizing on a set of labels here, and later rolling that out across our repos. Maybe create something like `pr/bug`, `pr/breaking`, `pr/enhancement`? @leezen and @infin8x might have ideas here as well.

**Comment by leezen** [comment]
I think sticking with `kind/bug` and `kind/enhancement` make sense. This way, we can easily associate labels between PRs and issues. We also already have a label `impact/breaking` so I think we're covered here across all our repos.

**Comment by pgavlin** [comment]
> do we have a contributing document? if so, it might be rad to link to it and add a checklist item for I have read the contributing document or similar

We do, but I'm pretty sure that it needs updating.

**Review by infin8x — APPROVED** [review]
Thanks @komalali for taking the lead on this!

**Comment by komalali** [comment]
Updated according to feedback and added a checklist item about updating the changelog

**Review by lblackstone — APPROVED** [review]

**Pull request merged**
