### PR TITLE
Use project schema to validate projects we load

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Moves the project schema file next to the project types.
Also makes Project use the schema when unmarshalling so that we only ever loaded valid schemas.
This should be particularly useful for validating the extensions to the project file for config support.

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
Need to think about this some more. Hooking unmarshal like this means the data itself doesn't get filled in...

**Review by Zaid-Ajaj — APPROVED** [review]
Commented-out code should go but otherwise lgtm

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
bors retry

**Comment by Frassle** [comment]
bors merge

**Pull request merged**
