### PR TITLE
Moving previewDigest to sdk/go/common/display, and exporting it. 

### LINKED ISSUE #9851: Make previewDigest into exported type PreviewDigest
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

To enable the parsing of the preview digest in other programs it would be nice to be able to reference the previewDigest type directly from other programs instead of having to copy/paste it. Can we export that in future versions. 

### Affected area/feature

pulumi/pkg

### PR DESCRIPTION
**Pull request by rshade**
# Description

This moves previewDigest to sdk/go/common/display, and exports it and dependent types.  

Fixes #9851

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]
Fine by me, just fix up the linter complaints.

**Comment by iwahbe** [comment]
I would prefer a change that did not result in the `sdk` depending on `pkg`. AFAIK the only types that are being used are `engine.ResourceChanges` and `deploy.StepOp`. 
- `engine.ResourceChanges` looks like it can be safely moved into the `sdk` (assuming `StepOp` can be moved). 
- `deploy.StepOp` is trickier, since it cannot be easily moved into the `sdk`. I recommend that we move the `StepOp` type (`type StepOp string`) to the `sdk` and redefine it in `pkg`: `type StepOp sdk.StepOp`. This keeps them closely bound but doesn't have the same lock in effect as exporting from `pkg`.

**Comment by Frassle** [comment]
> I would prefer a change that did not result in the sdk depending on pkg. AFAIK the only types that are being used are engine.ResourceChanges and deploy.StepOp.

Oh I did not notice that. Yes the transitive set of all types needed here all need to move to the SDK. We can't have the sdk depend on pkg.

> deploy.StepOp is trickier, since it cannot be easily moved into the sdk

Why? It doesn't look like it depends on much else.

**Comment by rshade** [comment]
So `pkg` can depend on `sdk` but not vice versa, or circular? Sorry, just making sure before I updating it.

**Comment by iwahbe** [comment]
>>deploy.StepOp is trickier, since it cannot be easily moved into the sdk
>
> Why? It doesn't look like it depends on much else.

I thought that `color` (which `StepOp` depends on via methods) was in `pkg`, but it is in `sdk`. In that case I think we can move `StepOp` to the `sdk`. Sorry for the confusion.

> So pkg can depend on sdk but not vice versa, or circular? Sorry, just making sure before I updating it.

`pkg` can and does depend on `sdk`. `sdk` does not (and should not) depend on `pkg`.

**Review by Frassle — APPROVED** [review]

**Pull request merged**
