### PR TITLE
Bring back auto-install plugins

### LINKED ISSUE #10216: `pulumi convert` fails when it can't find resource plugins
### What happened?

Running `pulumi convert` will fail if you don't have resource plugins already available in the plugin cache

### Steps to reproduce

- Create a new YAML project `pulumi new azure-yaml`
- Delete plugins from cache `pulumi plugin rm --all`
- `pulumi convert --language csharp --out dist`

Observe the following error:
```
error: could not load yaml program: failed to load YAML program, internal error: Pulumi.yaml:21,17-60: unable to resolve function name: internal error loading package "azure-native": no resource plugin 'pulumi-resource-azure-native' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure-native`; 
unable to resolve function name: internal error loading package "azure-native": no resource plugin 'pulumi-resource-azure-native' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure-native`, and 2 other diagnostic(s)
```

### Expected Behavior

Expected `pulumi convert` to run successfully and install the required resource plugins on demand

### Actual Behavior

Fails with an error message instead

### Versions used

Pulumi v3.36.0

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #10521: Dependencies of component providers aren't downloaded
Given the following YAML program, which uses the Synced Folder component (a package built from [pulumi-component-provider-ts-boilerplate](https://github.com/pulumi/pulumi-component-provider-ts-boilerplate)):

```
name: yaml-synced-folder-test
runtime: yaml

resources:
  bucket:
    type: aws:s3:Bucket

  bucket-folder:
    type: synced-folder:index:S3BucketFolder
    properties:
      path: ./site   # You'll need a folder with some files here.
      bucketName: ${bucket.bucket}
```

... the initial update fails because the provider's resource plugin wasn't downloaded:

```
pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/cnunciato/yaml-synced-folder-test/dev/previews/bbb32df0-7f6d-4640-97f7-ed34baa7b9d6

Downloading plugin: 38.06 MiB / 38.06 MiB [=========================] 100.00% 4s
[resource plugin synced-folder-0.0.8] installing
Downloading plugin: 126.54 MiB / 126.54 MiB [=======================] 100.00% 9s
[resource plugin aws-5.13.0] installing

     Type                                   Name                         Plan       Info
 +   pulumi:pulumi:Stack                    yaml-synced-folder-test-dev  create     
 +   ├─ aws:s3:Bucket                       bucket                       create     
 +   ├─ synced-folder:index:S3BucketFolder  bucket-folder                create     
     └─ pulumi:providers:aws                default_5_12_1                          1 error
 
Diagnostics:
  pulumi:providers:aws (default_5_12_1):
    error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.12.1 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.12.1`
```

This is presumably happening because the current version of pulumi-aws is `5.13` (which does get downloaded), whereas the latest synced-folder was built against `pulumi-aws@5.12.1`. The following is a snippet from my local `yarn.lock` that shows this:

```
"@pulumi/aws@^5.0.0":
  version "5.12.1"
  resolved "https://registry.yarnpkg.com/@pulumi/aws/-/aws-5.12.1.tgz#6fdae06c825e852392fc63f4dbe835626acbe36f"
  integrity sha512-QRuqXgNnDNWQZu0xcGHhbgLLF+dYyd9wt2dfsIy5UeP8nExaWmWv0DS4AhWO9KaaUGH+ifqsmX7RdfAzDmVBPw==
  dependencies:
    "@pulumi/pulumi" "^3.0.0"
    aws-sdk "^2.0.0"
    builtin-modules "3.0.0"
    mime "^2.0.0"
    read-package-tree "^5.2.1"
    resolve "^1.7.1"
```

To repro, ensure you don't have `5.12.1` installed already, then run `pulumi up`. I would expect Pulumi to download 5.12.1 and for the update to work without requiring an additional manual install.

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

This PR brings back #10530 (cc @AaronFriel)

Fixes #10521
Fixes #10216 

After debugging for ages, it turns out that the [package](https://github.com/checkly/pulumi-checkly/tree/main/sdk/nodejs) that caused the p0/revert of the original PRs were faulty in the sense that they didn't use latest codegen to generate the nodejs package. The generated package.json had
```json
{
    "pulumi": {
        "resource": true,
        "pluginDownloadURL": "https://github.com/checkly/pulumi-checkly/releases/download/v1.1.2"
    }
}
```
And couldn't auto install the third-party plugin because: 
 - Doesn't have a `name` which is now going to be required for third-party packages when the package name is not `@pulumi/{something}`(see change in pulumi-language-nodejs/main.go)
 - When `pulumi.name` is missing, `pulumi-language-nodejs/main.go` tried to "derive" the plugin name by simply removing the "@" sign from the package name but that is still is wrong because the plugin name was "checkly" and the derived plugin name was "checkly/pulumi" hence why a `packageJson.pulumi.name` is now required
 - Had `pluginDownloadURL` property instead of `server` which is not read anywhere by Pulumi except from the original schema.json itself, not the generated package.json file where it should be transformed to `server`
 - Third-party package used a very old version of tfgen v3.19.0 which is from February this year. 

I've confirmed that after installing the plugin via the install script added to the package _and_ adding a name to the `pulumi` section that the error no longer shows since now

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by AaronFriel — COMMENTED** [review]
Ah, I see what you mean, I'm out of date here. The codegen uses these keys already.

https://github.com/pulumi/pulumi/blob/2de7075ed95b6b860afabc58ce033d174123fc18/pkg/codegen/nodejs/gen.go#L2242-L2247

(Edited, disregard prior message.)

**Review by AaronFriel — APPROVED** [review]

**Review by iwahbe — APPROVED** [review]
LGTM

**Comment by AaronFriel** [comment]
bors retry

**Comment by AaronFriel** [comment]
bors retry

**Pull request merged**
