### PR TITLE
Rerun a full deployment for snapshot benchmarks

### PR DESCRIPTION
**Pull request by Frassle**
This was using subsets of the journal entries from a deploytest run to build up incremental snapshots. We're trying to remove Journal so this now just reruns the deployment with incrementally more resources each time and takes the final snapshots.

### CODE REVIEW

**Comment by pgavlin** [comment]
> We're trying to remove Journal

Why are we trying to remove `Journal`?

**Comment by Frassle** [comment]
> Pull Request / CI / Unit Test / pkg 2/3

This seems to be hitting runner resource limits now. Runs fine on my MacBook but keeps getting sigkilled in actions.

**Comment by pgavlin** [comment]
> Because using Journal for all our engine tests means we don't actually test the snapshot code we use in real deployments. We'd like to be able to write engine tests for bugs like https://github.com/pulumi/pulumi/issues/13736, but that means using the actual SnapshotManager.

Fair enough.

I would ask that we not remove `Journal` entirely:
1. There is value in being able to validate the sequence of snapshot operations, and IIRC we have tests that do so
2. There is value in having two implementations of the snapshot manager
3. `Journal` is a good basis for an actual journaling approach to snapshotting (and has been used as such in prototypes)

**Comment by Frassle** [comment]
Yeh looking like testing uses this far too much to feasibly change over. We'll look into other ways to increase testing of it.

**Pull request closed without merging**
