### PR TITLE
ci: Freeze v3.50.1 for release

### PR DESCRIPTION
**Pull request by iwahbe**

### CODE REVIEW

**Review by RobbieMcKinstry — APPROVED** [review]

**Comment by iwahbe** [comment]
bors retry

**Comment by RobbieMcKinstry** [comment]
@iwahbe I learned recently you can add priority to merges like this (i.e. ones you don't want to fail because they're in a batch with bad PRs).

```
bors r+ p=100
```

**Comment by iwahbe** [comment]
> @iwahbe I learned recently you can add priority to merges like this (i.e. ones you don't want to fail because they're in a batch with bad PRs).
> 
> ```
> bors r+ p=100
> ```

🤔 It looks like bors saw that.

**Comment by RobbieMcKinstry** [comment]
Yeah, which is weird because I'm certain I read in the docs that commands to bors must be prefixes on comments.

**Pull request merged**
