### PR TITLE
ci: Allow each build job to run goreleaser prep individually

### PR DESCRIPTION
**Pull request by AaronFriel**
This PR depends on #10763, as now that goreleaser prep script has a "local" mode that filters dependencies for the local target, we can run it on build steps.

This allows each build job to run in parallel a little bit more quickly.

### CODE REVIEW

**Review by justinvp — APPROVED** [review]

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge

**Pull request merged**
