### PR TITLE
[codegen] Rename the PCL package.

### PR DESCRIPTION
**Pull request by pgavlin**
It's just confusing that PCL lives in a package named `hcl2`.

### CODE REVIEW

**Comment by pgavlin** [comment]
Note that this rename is technically a breaking change, but it's a breaking change to an internal package. We'll need to update `pulumi-terraform-bridge` once this is in, as it consume the PCL package as part of `tf2pulumi`.

**Comment by pgavlin** [comment]
The codegen tests are failing because I `gofmt`'d the baselines 🤦

**Review by komalali — APPROVED** [review]
The codegen tests are failing now because of the break in the pulumi-terraform-bridge. We should make that change a fast-follow.

**Comment by pgavlin** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/pull/395

**Pull request merged**
