### PR TITLE
Add routine checks to pull request template

### PR DESCRIPTION
**Pull request by guineveresaenger**
# Description

This is a followup to #12860. Adds routine pre-commit tasks to the pull request checklist.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works
n/a

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by abhinav — APPROVED** [review]
Thanks!

**Comment by guineveresaenger** [comment]
bors merge

**Comment by abhinav** [comment]
Weird. Bors didn't merge.

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
