### PR TITLE
Freeze release v3.61.0

### PR DESCRIPTION
**Pull request by abhinav**

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12585** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12585" target="_blank">Graphite</a> 
    * **PR #12586** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12586" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12586?utm_source=stack-comment).

**Review by justinvp — APPROVED** [review]

**Comment by abhinav** [comment]
image
image


This is gonna time out.

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
