### PR TITLE
Adding try-catch to avoid complicated output register crash directly in python sdk

### PR DESCRIPTION
**Pull request by wuqunfei**

### CODE REVIEW

**Comment by wuqunfei** [comment]
https://github.com/pulumi/pulumi/pull/6196 this is the code example

**Comment by justinvp** [comment]
@wuqunfei, can you show an example Pulumi program where this is hit, and the output before/after? Thanks!

**Comment by leezen** [comment]
@wuqunfei Could you please take a look at Justin's question above?

**Comment by emiliza** [comment]
Closing due to inactivity. @wuqunfei if this is still needed - please open a new PR with the requested info from Justin

**Pull request closed without merging**
