### PR TITLE
Allow environment variables to have a null value

### LINKED ISSUE #6499: LocalWorkspaceOptions.EnvironmentVariables should allow null values
I'm seeing nullability warnings since `LocalWorkspaceOptions.EnvironmentVariables` is of type `IDictionary<string, string>` and not `IDictionary<string, string?>`.

I would expect it to be the latter since it maintains consistency with CLR types:

[Environment.SetEnvironementVariable](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-5.0#System_Environment_SetEnvironmentVariable_System_String_System_String_) accepts a nullable string as its value and [Environment.GetEnvironmentVariable](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=net-5.0#System_Environment_GetEnvironmentVariable_System_String_) returns a nullable string.

## Steps to reproduce

```csharp
programArgs.EnvironmentVariables = new Dictionary<string, string>
{
    // possible null reference assignment
    ["ARM_CLIENT_ID"] = Environment.GetEnvironmentVariable("AzureServicePrincipalId"),
};
```

If you agree, I can file a PR.

## Affected feature

 area/automation-api

### PR DESCRIPTION
**Pull request by MisinformedDNA**
Fixes #6499

### CODE REVIEW

**Comment by MisinformedDNA** [comment]
@justinvp @mikhailshilkov 

Do you guys want any changes? Should I note this in the CHANGELOG?

**Comment by mikhailshilkov** [comment]
LGTM overall

@komalali Do we want to do the same across all languages? E.g. TypeScript doesn't mark it as nullable either: https://github.com/pulumi/pulumi/blob/f9579b0a921201c0847005b9a9633aee4a5e3cfd/sdk/nodejs/x/automation/localWorkspace.ts#L614

**Comment by komalali** [comment]
LGTM. We do want this across languages but that shouldn't have to be @MisinformedDNA's cross to bear. An addition to the CHANGELOG will suffice 🙏🏽

**Review by mikhailshilkov — APPROVED** [review]
LGTM. Could you please add a changelog entry and we'll merge. Thank you!

**Comment by mikhailshilkov** [comment]
@MisinformedDNA Sorry to bother you again but there are conflicts in two files now. Could you please resolve them?

**Pull request merged**
