### PR TITLE
Edit example files to assume current codegen is correct

### PR DESCRIPTION
**Pull request by t0yv0**
In my local build I somehow get an error on `make test_fast` pointing to this diff. The PR resolves the error for me, but I am curious which way is right. The examples folder now has a mixture of sdk/v2 and sdk/v3 imports.

```
        helpers.go:71:
            	Error Trace:	helpers.go:71
            	            				gen_test.go:137
            	Error:      	Not equal:
            	            	expected: "// *** WARNING: this file was generated by test. ***\n// *** Do not edit by hand unless you're certain you know what you are doing! ***\n\npackage example\n\nimport (\n\t\"context\"\n\t\"reflect\"\n\n\t\"github.com/pulumi/pulumi-random/sdk/v2/go/random\"\n\t\"github.com/pulumi/pulumi/sdk/v2/go/pulumi\"\n)\n\ntype Pet struct {\n\tAge  *int              `pulumi:\"age\"`\n\tName *random.RandomPet `pulumi:\"name\"`\n}\n\n// PetInput is an input type that accepts PetArgs and PetOutput values.\n// You can construct a concrete instance of `PetInput` via:\n//\n//          PetArgs{...}\ntype PetInput interface {\n\tpulumi.Input\n\n\tToPetOutput() PetOutput\n\tToPetOutputWithContext(context.Context) PetOutput\n}\n\ntype PetArgs struct {\n\tAge  pulumi.IntPtrInput    `pulumi:\"age\"`\n\tName random.RandomPetInput `pulumi:\"name\"`\n}\n\nfunc (PetArgs) ElementType() reflect.Type {\n\treturn reflect.TypeOf((*Pet)(nil)).Elem()\n}\n\nfunc (i PetArgs) ToPetOutput() PetOutput {\n\treturn i.ToPetOutputWithContext(context.Background())\n}\n\nfunc (i PetArgs) ToPetOutputWithContext(ctx context.Context) PetOutput {\n\treturn pulumi.ToOutputWithContext(ctx, i).(PetOutput)\n}\n\nfunc (i PetArgs) ToPetPtrOutput() PetPtrOutput {\n\treturn i.ToPetPtrOutputWithContext(context.Background())\n}\n\nfunc (i PetArgs) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn pulumi.ToOutputWithContext(ctx, i).(PetOutput).ToPetPtrOutputWithContext(ctx)\n}\n\n// PetPtrInput is an input type that accepts PetArgs, PetPtr and PetPtrOutput values.\n// You can construct a concrete instance of `PetPtrInput` via:\n//\n//          PetArgs{...}\n//\n//  or:\n//\n//          nil\ntype PetPtrInput interface {\n\tpulumi.Input\n\n\tToPetPtrOutput() PetPtrOutput\n\tToPetPtrOutputWithContext(context.Context) PetPtrOutput\n}\n\ntype petPtrType PetArgs\n\nfunc PetPtr(v *PetArgs) PetPtrInput {\n\treturn (*petPtrType)(v)\n}\n\nfunc (*petPtrType) ElementType() reflect.Type {\n\treturn reflect.TypeOf((**Pet)(nil)).Elem()\n}\n\nfunc (i *petPtrType) ToPetPtrOutput() PetPtrOutput {\n\treturn i.ToPetPtrOutputWithContext(context.Background())\n}\n\nfunc (i *petPtrType) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn pulumi.ToOutputWithContext(ctx, i).(PetPtrOutput)\n}\n\ntype PetOutput struct{ *pulumi.OutputState }\n\nfunc (PetOutput) ElementType() reflect.Type {\n\treturn reflect.TypeOf((*Pet)(nil)).Elem()\n}\n\nfunc (o PetOutput) ToPetOutput() PetOutput {\n\treturn o\n}\n\nfunc (o PetOutput) ToPetOutputWithContext(ctx context.Context) PetOutput {\n\treturn o\n}\n\nfunc (o PetOutput) ToPetPtrOutput() PetPtrOutput {\n\treturn o.ToPetPtrOutputWithContext(context.Background())\n}\n\nfunc (o PetOutput) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn o.ApplyT(func(v Pet) *Pet {\n\t\treturn &v\n\t}).(PetPtrOutput)\n}\nfunc (o PetOutput) Age() pulumi.IntPtrOutput {\n\treturn o.ApplyT(func(v Pet) *int { return v.Age }).(pulumi.IntPtrOutput)\n}\n\nfunc (o PetOutput) Name() random.RandomPetOutput {\n\treturn o.ApplyT(func(v Pet) *random.RandomPet { return v.Name }).(random.RandomPetOutput)\n}\n\ntype PetPtrOutput struct{ *pulumi.OutputState }\n\nfunc (PetPtrOutput) ElementType() reflect.Type {\n\treturn reflect.TypeOf((**Pet)(nil)).Elem()\n}\n\nfunc (o PetPtrOutput) ToPetPtrOutput() PetPtrOutput {\n\treturn o\n}\n\nfunc (o PetPtrOutput) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn o\n}\n\nfunc (o PetPtrOutput) Elem() PetOutput {\n\treturn o.ApplyT(func(v *Pet) Pet { return *v }).(PetOutput)\n}\n\nfunc (o PetPtrOutput) Age() pulumi.IntPtrOutput {\n\treturn o.ApplyT(func(v *Pet) *int {\n\t\tif v == nil {\n\t\t\treturn nil\n\t\t}\n\t\treturn v.Age\n\t}).(pulumi.IntPtrOutput)\n}\n\nfunc (o PetPtrOutput) Name() random.RandomPetOutput {\n\treturn o.ApplyT(func(v *Pet) *random.RandomPet {\n\t\tif v == nil {\n\t\t\treturn nil\n\t\t}\n\t\treturn v.Name\n\t}).(random.RandomPetOutput)\n}\n\nfunc init() {\n\tpulumi.RegisterOutputType(PetOutput{})\n\tpulumi.RegisterOutputType(PetPtrOutput{})\n}\n"
            	            	actual  : "// *** WARNING: this file was generated by test. ***\n// *** Do not edit by hand unless you're certain you know what you are doing! ***\n\npackage example\n\nimport (\n\t\"context\"\n\t\"reflect\"\n\n\t\"github.com/pulumi/pulumi-random/sdk/v3/go/random\"\n\t\"github.com/pulumi/pulumi/sdk/v2/go/pulumi\"\n)\n\ntype Pet struct {\n\tAge  *int              `pulumi:\"age\"`\n\tName *random.RandomPet `pulumi:\"name\"`\n}\n\n// PetInput is an input type that accepts PetArgs and PetOutput values.\n// You can construct a concrete instance of `PetInput` via:\n//\n//          PetArgs{...}\ntype PetInput interface {\n\tpulumi.Input\n\n\tToPetOutput() PetOutput\n\tToPetOutputWithContext(context.Context) PetOutput\n}\n\ntype PetArgs struct {\n\tAge  pulumi.IntPtrInput    `pulumi:\"age\"`\n\tName random.RandomPetInput `pulumi:\"name\"`\n}\n\nfunc (PetArgs) ElementType() reflect.Type {\n\treturn reflect.TypeOf((*Pet)(nil)).Elem()\n}\n\nfunc (i PetArgs) ToPetOutput() PetOutput {\n\treturn i.ToPetOutputWithContext(context.Background())\n}\n\nfunc (i PetArgs) ToPetOutputWithContext(ctx context.Context) PetOutput {\n\treturn pulumi.ToOutputWithContext(ctx, i).(PetOutput)\n}\n\nfunc (i PetArgs) ToPetPtrOutput() PetPtrOutput {\n\treturn i.ToPetPtrOutputWithContext(context.Background())\n}\n\nfunc (i PetArgs) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn pulumi.ToOutputWithContext(ctx, i).(PetOutput).ToPetPtrOutputWithContext(ctx)\n}\n\n// PetPtrInput is an input type that accepts PetArgs, PetPtr and PetPtrOutput values.\n// You can construct a concrete instance of `PetPtrInput` via:\n//\n//          PetArgs{...}\n//\n//  or:\n//\n//          nil\ntype PetPtrInput interface {\n\tpulumi.Input\n\n\tToPetPtrOutput() PetPtrOutput\n\tToPetPtrOutputWithContext(context.Context) PetPtrOutput\n}\n\ntype petPtrType PetArgs\n\nfunc PetPtr(v *PetArgs) PetPtrInput {\n\treturn (*petPtrType)(v)\n}\n\nfunc (*petPtrType) ElementType() reflect.Type {\n\treturn reflect.TypeOf((**Pet)(nil)).Elem()\n}\n\nfunc (i *petPtrType) ToPetPtrOutput() PetPtrOutput {\n\treturn i.ToPetPtrOutputWithContext(context.Background())\n}\n\nfunc (i *petPtrType) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn pulumi.ToOutputWithContext(ctx, i).(PetPtrOutput)\n}\n\ntype PetOutput struct{ *pulumi.OutputState }\n\nfunc (PetOutput) ElementType() reflect.Type {\n\treturn reflect.TypeOf((*Pet)(nil)).Elem()\n}\n\nfunc (o PetOutput) ToPetOutput() PetOutput {\n\treturn o\n}\n\nfunc (o PetOutput) ToPetOutputWithContext(ctx context.Context) PetOutput {\n\treturn o\n}\n\nfunc (o PetOutput) ToPetPtrOutput() PetPtrOutput {\n\treturn o.ToPetPtrOutputWithContext(context.Background())\n}\n\nfunc (o PetOutput) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn o.ApplyT(func(v Pet) *Pet {\n\t\treturn &v\n\t}).(PetPtrOutput)\n}\nfunc (o PetOutput) Age() pulumi.IntPtrOutput {\n\treturn o.ApplyT(func(v Pet) *int { return v.Age }).(pulumi.IntPtrOutput)\n}\n\nfunc (o PetOutput) Name() random.RandomPetOutput {\n\treturn o.ApplyT(func(v Pet) *random.RandomPet { return v.Name }).(random.RandomPetOutput)\n}\n\ntype PetPtrOutput struct{ *pulumi.OutputState }\n\nfunc (PetPtrOutput) ElementType() reflect.Type {\n\treturn reflect.TypeOf((**Pet)(nil)).Elem()\n}\n\nfunc (o PetPtrOutput) ToPetPtrOutput() PetPtrOutput {\n\treturn o\n}\n\nfunc (o PetPtrOutput) ToPetPtrOutputWithContext(ctx context.Context) PetPtrOutput {\n\treturn o\n}\n\nfunc (o PetPtrOutput) Elem() PetOutput {\n\treturn o.ApplyT(func(v *Pet) Pet { return *v }).(PetOutput)\n}\n\nfunc (o PetPtrOutput) Age() pulumi.IntPtrOutput {\n\treturn o.ApplyT(func(v *Pet) *int {\n\t\tif v == nil {\n\t\t\treturn nil\n\t\t}\n\t\treturn v.Age\n\t}).(pulumi.IntPtrOutput)\n}\n\nfunc (o PetPtrOutput) Name() random.RandomPetOutput {\n\treturn o.ApplyT(func(v *Pet) *random.RandomPet {\n\t\tif v == nil {\n\t\t\treturn nil\n\t\t}\n\t\treturn v.Name\n\t}).(random.RandomPetOutput)\n}\n\nfunc init() {\n\tpulumi.RegisterOutputType(PetOutput{})\n\tpulumi.RegisterOutputType(PetPtrOutput{})\n}\n"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -9,3 +9,3 @@
            	            	
            	            	-	"github.com/pulumi/pulumi-random/sdk/v2/go/random"
            	            	+	"github.com/pulumi/pulumi-random/sdk/v3/go/random"
            	            	 	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
            	Test:       	TestGeneratePackage/External_resource_schema
            	Messages:   	example/pulumiTypes.go
```

### CODE REVIEW

**Comment by t0yv0** [comment]
Hm so first of all this file is generated code so I should no the editing it. Interesting.

``` // *** WARNING: this file was generated by test. *** ```

I'd like to understand what generates it.

Second I wonder why the test failure is only on my local and not on CI perhaps my build environment is not quite right.

**Comment by mikhailshilkov** [comment]
Hmm, I would expect to see v2 there based on https://github.com/pulumi/pulumi/blob/59686ab3ad640de8c3eac300877940a1b894db98/pkg/codegen/internal/test/testdata/external-resource-schema/schema.json#L69.

I wonder why you get v3.

**Comment by t0yv0** [comment]
Let me spew-debug a bit.

**Comment by stack72** [comment]
@t0yv0 the issue is that you have pulumi-random locally - you just need to remove that and ensure the correct version is installed and all will be ok 

pulumi plugin rm resource random <version to remove>

**Comment by t0yv0** [comment]
My pulumi-random plugin was v2.x and removing didn't seem to help. But there's a good idea here I can attempt a more hermetic build

**Comment by t0yv0** [comment]
Yes that was related to my global environment pollution. `nix-shell --pure` created a sandbox where `make test_fast` is working 🎉

**Pull request closed without merging**
