### PR TITLE
Update PULL_REQUEST_TEMPLATE.md referencing the new changelog tool

### LINKED ISSUE #10732: Update PR template to include prompt to use new changelog tool
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We have a new tool to do changelogs. we should update our PR prompt to ask users to use it.

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #10732 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]
LGTM!

We also need the associated change to the changelog job.

**Comment by dixler** [comment]
@iwahbe opened https://github.com/pulumi/pulumi/issues/10743

**Comment by dixler** [comment]
bors merge

**Review by kpitzen — APPROVED** [review]

**Comment by AaronFriel** [comment]
bors retry

**Pull request merged**
