### PR TITLE
[automation/dotnet] Fix EventLogWatcher failing to read events after an exception was thrown

### PR DESCRIPTION
**Pull request by vipentti**
Discovered this while trying to preview some code which threw an exception. Instead of propagating the actual exception to the caller, the following exception was thrown

```
System.IO.IOException : The process cannot access the file '<temp>\automation-logs-preview-bc4fcvtm.ayq\eventlog.txt' 
because it is being used by another process.
```

This error seems to only occur on Windows.

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]
Awesome thanks for this!

I wonder what's up with this tests not failing on CI or maybe it's not running on CI? Checking.

**Comment by vipentti** [comment]
@t0yv0 The problem only occurs when event-log is used, which by default only happens during preview, which was not previously used in the error propagation test cases so I think that's why it was not happening in CI.

**Comment by t0yv0** [comment]
Gotcha so we needed the test change to repro. Awesome. Thanks again for this.

**Comment by vipentti** [comment]
The problem should be reproducible by removing the `FileShare.ReadWrite` and running the tests on a Windows machine.

**Pull request merged**
