### PR TITLE
Add a migrate package for migrating to and from differently-versioned API types

### PR DESCRIPTION
**Pull request by swgillespie**
There's a lot of code in this PR but I promise that most of the code are for tests 😄 .

This PR creates a new `migrate` subpackage of `apitypes` that is responsible for migrating API types from one version to another. This package is immediately used in this PR to only use the `V2` deployment, resource, and checkpoint API types in the CLI. Any use of the V1 deployment, resource, and checkpoint APIs are immediately projected into V2 in the process of deserializing the API types into engine data structures.

Because the service is not yet ready to accept V2 deployments yet, and because V2 deployments don't have any additional semantics yet (i.e. the fix for https://github.com/pulumi/pulumi/issues/1521), V2 deployments are coerced again back to V1 so that they can be sent to the service. This is temporary until the service is ready to understand these new versions.

Also of note is that this PR does not project V2 checkpoints back to V1 before saving them on-disk in the fire and forget case. Everything works fine, but any CLI that operates on the on-disk V2 checkpoint must be this commit or newer in order to understand the new format.

### CODE REVIEW

**Comment by chrsmith** [comment]
I'll need to think about it a bit more, but I think this is the right approach. Let me make sure I understand the implications though.

We still keep using whatever internal / `engine` package data structures we used to. The `apitype` package only comes into play when we need to marshal some data into the service, which requires us to convert the data somehow.

Previously we were converting it to untyped things, e.g. `Deployment`. Then we used `DeploymentV1`. And now we have a `apitype/migration` package to assist with switching to `DeploymentV2`. Right?

Do we expect to keep the older versions of these structs in the repo? (We would have to to avoid breaking the dependency the service has on them, but in the past we've talked about maybe moving the apitypes into a separate repo so this would be less of a pain.)

I'll need to think about it a bit more, but I think this is the right approach. Let me make sure I understand the implications though.

We still keep using whatever internal / `engine` package data structures we used to. The `apitype` package only comes into play when we need to marshal some data into the service, which requires us to convert the data somehow.

> but any CLI that operates on the on-disk V2 checkpoint must be this commit or newer in order to understand the new format.

Do you know what the error experience is here? Is it something like "Unable to read checkpoint, as it was written using a new version of Pulumi" or similar? If the experience is the CLI panicing and/or just using incorrect/corrupted data, then we probably want to do better.

**Comment by swgillespie** [comment]
> We still keep using whatever internal / engine package data structures we used to. The apitype package only comes into play when we need to marshal some data into the service, which requires us to convert the data somehow.

Yes. The engine still uses `resource.State` to represent resources, which gets marshaled to/from apitypes as necessary.

> Previously we were converting it to untyped things, e.g. Deployment. Then we used DeploymentV1. And now we have a apitype/migration package to assist with switching to DeploymentV2. Right?

Yeah. `apitype/migration` is useful for forwards compatibility (a CLI can freely convert V1 checkpoints and deployments to V2 at-will) and backwards compatibility (the service can migrate V2 checkpoints and deployments to V1 so that it can write e.g. display code against one version of a resource instead of having to write it for each version). 

I figured I'd make a package out of this because it's super easy to get this sort of code wrong. I wrote all of the tests in this PR because I screwed up pretty much every function the first time I wrote it. It's really easy to e.g. omit a field. I liked the idea of having it in once well-tested place.

> Do we expect to keep the older versions of these structs in the repo? (We would have to to avoid breaking the dependency the service has on them, but in the past we've talked about maybe moving the apitypes into a separate repo so this would be less of a pain.)

I think we need to keep them in this repo for as long as we intend to support them. This package makes it really easy to migrate up and down versions, so there's no pressing need right now for us to break support for old versions as long as we are able to migrate to newer ones.

> Do you know what the error experience is here? Is it something like "Unable to read checkpoint, as it was written using a new version of Pulumi" or similar?

This is the error message we issue from the CLI:

https://github.com/pulumi/pulumi/blob/57ae7289f38372bd62d8d333f274d19c55153fad/tests/stack_test.go#L187

Fire-and-forget issues a slightly worse error message (something like "failed to load checkpoint: unrecognized version").

After this commit, if you send a V2 deployment to the service by editing the `version` field of a deployment, you get this bad error message:

```
$ pulumi stack import --file test.json
error: could not import deployment: import unsuccessful: status failed
```

This is temporary because the service is rejecting the V2 deployment where the CLI recognizes it.

>  If the experience is the CLI panicing and/or just using incorrect/corrupted data, then we probably want to do better.

Not on my watch! 😄

**Comment by swgillespie** [comment]
@chrsmith any objections to merging this?

**Comment by hausdorff** [comment]
Tagging `kubernetes/inner-dev-loop` because this affects parallelism, which is critical for the upcoming "kube moment"

**Comment by swgillespie** [comment]
I'm going to go ahead and merge this - please let me know if there are any changes anyone would like me to make.

**Pull request merged**
