### PR TITLE
Refactor out Python virtualenv shim

### PR DESCRIPTION
**Pull request by AaronFriel**
This code is duplicated here and in Pulumi Cloud, in template instantiation. Moving the shim to a
public function helps clean up this code duplication.

### CODE REVIEW

**Comment by AaronFriel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/15071?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #15056** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/15056?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #15071** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/15071?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/15071?utm_source=stack-comment).

**Comment by Frassle** [comment]
> This code is duplicated here and in Pulumi Cloud, in template instantiation.

I think I'd actually prefer that. Long term we'd like to get rid of this workaround and that probably means changing this to a grpc request to the language runtime for what the default runtime options should be. That's probably not appropriate to be pulled into Cloud as a library, plus this whole thing is also just begging the question of why Cloud is doing it's own template instantiations instead of letting `new` deal with it, but that's probably a more involved conversation than anyone's going to make time for now.

**Comment by AaronFriel** [comment]
@Frassle I think that moving this code to a single location is the first step to refactoring it to be part of the InstallDependencies or other setup stage of the Python language host.

I.e.:

1. Consolidate all of these locations to call this Fixup
2. Add support in the Python language host to perform this defaulting, ship that - it's effectively a no-op because the Fixup and lang host do the same thing.
3. Make the Fixup a no-op and mark it deprecated, verify nothing breaks
4. Clean up callers to the Fixup.

**Comment by Frassle** [comment]
> 2. Add support in the Python language host to perform this defaulting, ship that - it's effectively a no-op because the Fixup and lang host do the same thing.
> 3. Make the Fixup a no-op and mark it deprecated, verify nothing breaks

This is _heavily_ dependent on what the language host replacement looks like. I strongly suspect it won't be part of InstalDependencies and while be a fundamentally new part of the control flow for `new` and only `new`. So anyone else (like Cloud) trying to use this fixup will just be stuck on the fixup that we'll then be wanting to delete because the cli now has a proper fix.

**Comment by AaronFriel** [comment]
Would we not want to move external callers (Pulumi Cloud) to use this shared implementation so we can roll out fixes/changes and deprecate it eventually?

**Comment by lunaris** [comment]
Closing this for now as it sounds like we need more discussion on this before considering a path forward.

**Pull request closed without merging**
