### PR TITLE
Start policy packs in parallel

### LINKED ISSUE #14454: Investigate parallelizing exuction of policy packs
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Policy packs are being run sequentially.  Given that these usually take some time (a couple of seconds) to execute, the time to run them adds up quickly.  Investigate whether they can be run at least partly in parallel to speed up the execution of `pulumi {preview,up}`.

### PR DESCRIPTION
**Pull request by tgummerer**
Currently we start up and thus compile policy packs one by one.  When multiple policy packs need to be loaded, this increases the start up time substantially.  In previous tests plugins took ~1-3s to start up, so having multiple of these the time adds up quickly.

Loading them in parallel will help reduce the startup time here.

Fixes #14454

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Frassle — COMMENTED** [review]
Does this not play havoc with the UX given you'll have multiple instance of npm/pip installing things in parallel writing to the same terminal?

**Comment by tgummerer** [comment]
> Does this not play havoc with the UX given you'll have multiple instance of npm/pip installing things in parallel writing to the same terminal?

Yeah good point.  I pushed up a commit that avoids doing the installation step in parallel, where npm/pip installing is being run, but that still loads the policies in a goroutine.  This won't result in much of a performance improvement when policies need to be installed, though that should be the much less common case, as I'd expect users to usually have the policies cached locally already, and they only need to be run.

**Review by Frassle — COMMENTED** [review]
This looks reasonable, but do we have any tests that actually load multiple policy packs to ensure this parallel load doesn't race anything?

**Comment by tgummerer** [comment]
> This looks reasonable, but do we have any tests that actually load multiple policy packs to ensure this parallel load doesn't race anything?

I'm actually struggling to find any tests that load even a single policy pack, so I'm gonna look into adding tests.

**Comment by tgummerer** [comment]
I added a few tests here, though they are all integration tests.  I felt like that made most sense, but I'd be curious to hear if anyone has other ideas on how to test this.

**Review by Frassle — APPROVED** [review]

**Pull request merged**
