### PR TITLE
Don't retry plugin write errors

### PR DESCRIPTION
**Pull request by Frassle**
# Description

No point retrying errors due to writing the plugin to a temporary file. This splits the error tracking up so we only retry read errors.

Fixes https://github.com/pulumi/pulumi/issues/10310

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
> I have added tests that prove my fix is effective or that my feature works

I'd really like to re-write the plugin code to use something like `io/fs.FS` or https://github.com/spf13/afero to make testing this possible.

**Review by iwahbe — APPROVED** [review]
I would probably move this to its own function and introducing a 
```go
type readWriteError interface {
  error
  readError() error
  writeError() error
  asError() error { readError() or writeError() }
}
```
abstraction to wrap the concept. 

I think that is more a style preference, and you may take it or leave it. 

The code looks good and I appreciate the clarifying comment. LGTM.

**Comment by Frassle** [comment]
> I think that is more a style preference, and you may take it or leave it.

I'd normally lean towards not adding an abstraction for a single use. I don't think this is going to crop up anywhere else (where else do we do downloads) so I'll just keep it local for now.

**Comment by mikhailshilkov** [comment]
I fixes the retry part - but do we still need to address the write "file too large" aspect of #10310?

**Comment by Frassle** [comment]
Yeh I'll leave the issue open to look into that aspect

**Pull request merged**
