### PR TITLE
Print PolicyPacks run as part of update summary

### PR DESCRIPTION
**Pull request by hausdorff**
Fixes pulumi/pulumi-policy#69.

### CODE REVIEW

**Comment by hausdorff** [comment]
It's worth noting that this actually will still print a "policy summary" after a `destroy`. It is debatable that we should do so, since (perhaps obviously) we do not validate resource definitions before they are destroyed. I chose not to implement this since it seemed like more trouble than it was worth, and it doesn't hurt to know which policy packs are being loaded when you run `pulumi` in general.

**Comment by hausdorff** [comment]
The output looks like this:

Screen Shot 2019-09-27 at 2 51 20 PM

**Comment by nesl247** [comment]
Since this is being done, would it not be useful to also list if the pack had any rules that applied?

**Comment by hausdorff** [comment]
Right now we don't distinguish between rules that apply and don't—instead, the whole policy pack applies (and is therefore listed here), or it doesn't (and therefore is not). I think that accomplishes your request. Does it?

**Comment by CyrusNajmabadi** [comment]
Tiny bit of bikeshedding.  I like that the resource summary is last.  Woudl you be opposed to ordering your policy-pack info befor the resource summary?

**Comment by lukehoban** [comment]
> It's worth noting that this actually will still print a "policy summary" after a destroy. It is debatable that we should do so, since (perhaps obviously) we do not validate resource definitions before they are destroyed

It does seem quite misleading to print that these policies were “run” if they weren’t.

**Comment by hausdorff** [comment]
@lukehoban they _are_ run, but no resource definitions are validated against them because there are no resource definitions to update.

**Pull request merged**
