### PR TITLE
Temporarily revert support for projects in the Self-Managed backend

### PR DESCRIPTION
**Pull request by justinvp**
Temporarily reverting this to keep master in a releasable state while we finalize the design.

As it was, the syntax `pulumi stack select foo/bar` could mean fundamentally different things based on what backend you're logged into. In the Service backend, the `foo` is the org. In the Self-Managed backend, the `foo` would be the project name. Moreover, in the Service backend, there is one "fully-qualified" name, and all the others are just shorthands. But this wouldn't be true in the Self-Managed backend where `bar` represents a fundamentally different stack than `foo/bar`. This makes it hard to explain what stack identities are. Self-Managed has been a pure subset of what Service supported in terms of stack identities. If we went with this design, it would be a partially overlapping, but inconsistent subset/superset.

We're discussing some design alternatives that would make stack identities in the Self-Managed backend more consistent with the Service backend, and will reintroduce the changes with the adjusted design soon.

### CODE REVIEW

**Review by abhinav — APPROVED** [review]

**Comment by justinvp** [comment]
bors merge p=1

**Comment by abhinav** [comment]
Superseded by https://github.com/pulumi/pulumi/pull/12066

**Comment by abhinav** [comment]
Accidentally closed the wrong PR

**Pull request merged**
