### PR TITLE
Always read and write nodejs runtime options from/to the environment

### LINKED ISSUE #6057: [Automation API] Improve the experience for unhandled promise rejections for nodejs inline programs
Here's a minimal repro for an error we're seeing:

```ts
const run = async () => {
    // This is our pulumi program in "inline function" form
    const pulumiProgram = async () => {
        //Promise.reject(new Error("rejected promise"))
        const engineVersion = gcp.container.getEngineVersions().then((v) => v.latestMasterVersion);
        return {
            engv: engineVersion
        };
    };

    // Create our stack 
    const args: InlineProgramArgs = {
        stackName: "dev1",
        projectName: "inlineNode",
        program: pulumiProgram
    };

    // create (or select if one already exists) a stack that uses our inline program
    const stack = await LocalWorkspace.createOrSelectStack(args);

    console.info("updating stack...");
    try {
        const upRes = await stack.up({ onOutput: console.info });
        console.log(`update summary: \n${JSON.stringify(upRes.summary.resourceChanges, null, 4)}`);
    }
    catch (e){
        console.log(e)
        process.exit(1)
    }
};

run().catch(err => {
    console.log("there was an error")
    console.log(err)
    console.log("error logged")
});
```

Which results in:

```
Evans-MBP:inlineProgram-ts evanboyle$ yarn start
yarn run v1.22.10
$ tsc && node ./bin/index.js
updating stack...
Updating (dev1)


View Live: https://app.pulumi.com/EvanBoyle/inlineNode/dev1/updates/23




resetting options
{
  project: 'inlineNode',
  stack: 'dev1',
  parallel: 2147483647,
  engineAddr: '127.0.0.1:51858',
  monitorAddr: '127.0.0.1:51860',
  dryRun: false
}
    pulumi:pulumi:Stack inlineNode-dev1 running 

    pulumi:pulumi:Stack inlineNode-dev1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack inlineNode-dev1 running error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack inlineNode-dev1 **failed** 2 errors
 
Diagnostics:
  pulumi:pulumi:Stack (inlineNode-dev1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:124:15)
        at Object.getMonitor (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:206:13)
        at /Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:123:40
        at Generator.next (<anonymous>)
        at fulfilled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
 
Resources:
    1 unchanged

Duration: 1s


CommandError: code: 255
 stdout: Updating (dev1)

View Live: https://app.pulumi.com/EvanBoyle/inlineNode/dev1/updates/23


    pulumi:pulumi:Stack inlineNode-dev1 running 
    pulumi:pulumi:Stack inlineNode-dev1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack inlineNode-dev1 running error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack inlineNode-dev1 **failed** 2 errors
 
Diagnostics:
  pulumi:pulumi:Stack (inlineNode-dev1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:124:15)
        at Object.getMonitor (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:206:13)
        at /Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:123:40
        at Generator.next (<anonymous>)
        at fulfilled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
 
Resources:
    1 unchanged

Duration: 1s


 stderr: 
 err?: 

    at Object.createCommandError (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/pulumi/x/automation/errors.js:71:17)
    at ChildProcess.<anonymous> (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/pulumi/x/automation/cmd.js:63:40)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  commandResult: CommandResult {
    stdout: 'Updating (dev1)\n' +
      '\n' +
      'View Live: https://app.pulumi.com/EvanBoyle/inlineNode/dev1/updates/23\n' +
      '\n' +
      '\n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 running \n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 running error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 **failed** 2 errors\n' +
      ' \n' +
      'Diagnostics:\n' +
      '  pulumi:pulumi:Stack (inlineNode-dev1):\n' +
      '    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      '        at requireTestModeEnabled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:124:15)\n' +
      '        at Object.getMonitor (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:206:13)\n' +
      '        at /Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:123:40\n' +
      '        at Generator.next (<anonymous>)\n' +
      '        at fulfilled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)\n' +
      '        at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
      '    error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      ' \n' +
      'Resources:\n' +
      '    1 unchanged\n' +
      '\n' +
      'Duration: 1s\n' +
      '\n',
    stderr: '',
    code: 255,
    err: undefined
  }
}
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by EvanBoyle**
Fixes https://github.com/pulumi/pulumi/issues/6059 Fixes https://github.com/pulumi/pulumi/issues/6041. 

See https://github.com/pulumi/pulumi/issues/6059 for more detail on why this is necessary. TLDR; is that nodejs package resolution can result in multiple copies of a given package in the `node_modules` tree, and thus multiple runtime options variables that can get out of sync (specifically for automation API where the lifetime of runtime options is managed manually). 

In order for settings to be shared appropriately in the instance where an inline program and a provider sdk dependency both bring in different copies of `@pulumi/pulumi`, we must read and write settings via the environment and avoid caching values.

### CODE REVIEW

**Review by komalali — APPROVED** [review]

**Review by pgavlin — COMMENTED** [review]
Can we add some tests that are specific to this scenario? Even if it's just setting some config and then reading the appropriate envvar.

**Comment by komalali** [comment]
@EvanBoyle any chance you could add some tests and close this out this week?

**Comment by EvanBoyle** [comment]
@pgavlin good catch, I had actually forgotten that this should apply to config as well. I updated the config code to always read/write from the environment as well. 

I also added some settings tests that round trip some mutations to options and config and then check the resulting environment variables. 

Our node config module already has [some extensive tests](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tests/config.spec.ts) that lend additional confidence to this change.

**Review by komalali — APPROVED** [review]
LGTM, thanks for adding those tests!

**Pull request merged**
