### PR TITLE
use a lockfile to prevent concurrent access to config file

### LINKED ISSUE #15240: integration TestConstructComponentConfigureProviderPython is flaky
```
=== FAIL: integration TestConstructComponentConfigureProviderPython (82.07s)
    io.go:432: + set -euo pipefail
    io.go:432: + DONEFILE=.done
    io.go:432: ++ git rev-parse HEAD:./
    io.go:432: + EXPECTED_HASH=49c728ddf88a9e2e54f2c3b12774c4bee13ad097
    io.go:432: + BUILD=false
    io.go:432: + '[' -f .done ']'
    io.go:432: + echo 'Setup not marked done'
    io.go:432: Setup not marked done
    io.go:432: + BUILD=true
    io.go:432: ++ git status --porcelain .
    io.go:432: + output=
    io.go:432: + '[' -z '' ']'
    io.go:432: + echo 'Directory is clean'
    io.go:432: Directory is clean
    io.go:432: + true
    io.go:432: + setup_nodejs
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
    io.go:432: + setup_python
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: + i=0
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + builds[$***i***]=120
    io.go:432: + echo 'Started setup_nodejs with PID 120'
    io.go:432: Started setup_nodejs with PID 120
    io.go:432: + i=1
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + setup_nodejs
    io.go:432: + builds[$***i***]=121
    io.go:432: + echo 'Started setup_python with PID 121'
    io.go:432: Started setup_python with PID 121
    io.go:432: + i=2
    io.go:432: + for build_pid in "$***builds[@]***"
    io.go:432: + echo 'Waiting for 120'
    io.go:432: Waiting for 120
    io.go:432: + wait 120
    io.go:432: + setup_python
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
    io.go:432: 
    io.go:432: real	0m0.013s
    io.go:432: user	0m0.015s
    io.go:432: sys	0m0.000s
    io.go:432: + for build_pid in "$***builds[@]***"
    io.go:432: + echo 'Waiting for 121'
    io.go:432: Waiting for 121
    io.go:432: + wait 121
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: 
    io.go:432: real	0m0.017s
    io.go:432: user	0m0.000s
    io.go:432: sys	0m0.015s
    io.go:432: + echo 49c728ddf88a9e2e54f2c3b12774c4bee13ad097
    program.go:1906: sample: construct_component_configure_provider\python
    program.go:1911: pulumi: D:\a\pulumi\pulumi\bin\pulumi.exe
    command.go:34: **** Invoke 'C:\hostedtoolcache\windows\Python\3.11.7\x64\python.exe -m venv venv' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\python-venv.20240124-140004.9b651.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\venv\Scripts\python.exe -m pip install -r requirements.txt' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
Traceback (most recent call last):
  File "D:\a\pulumi\pulumi\scripts\go-test.py", line 99, in <module>
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\virtualenv-pip-install.20240124-140028.95b90.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\venv\Scripts\python.exe -m pip install -e D:\a\pulumi\pulumi\sdk\python\env\src' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\virtualenv-pip-install-package.20240124-140033.1982a.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\venv\Scripts\python.exe -m pip install -e D:\a\pulumi\pulumi\pkg\codegen\testing\test\testdata\methods-return-plain-resource\python' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\virtualenv-pip-install-package.20240124-140037.e83d4.log
    program.go:2056: projdir: C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557
    program.go:1321: Initializing project (dir C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557; stack p-it-fv-az1388--python-f9683ea7)
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe login' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-login.20240124-140038.ee6ec.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack init moolumi/p-it-fv-az1388--python-f9683ea7' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-stack-init.20240124-140038.07791.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe config set-all --plaintext proxy=FromEnv' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:106: Command completed without output
    program.go:1488: Performing primary preview and update
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe preview --non-interactive --diff' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-preview-initial.20240124-140045.221c9.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe up --non-interactive --yes --skip-preview --event-log C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-events.json' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-update-initial.20240124-140053.34c2e.log
    program.go:1498: Roundtripping checkpoint via stack export and stack import
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack export --file stack.json' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:106: Command completed without output
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack import --file stack.json' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:83: Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack import --file stack.json' failed: exit status 0xffffffff
error: constructing deployment for upload: serializing resources: failed to encrypt secret value: [404] Not Found: Stack 'p-it-fv-az1388--python-f9683ea7' not found

    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-stack-import.20240124-140054.dc37b.log
    program.go:1446: Destroying stack
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:83: Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' failed: exit status 0xffffffff
Destroying (moolumi/p-it-fv-az1388--python-f9683ea7)

error: could not deserialize deployment: [404] Not Found: Stack 'p-it-fv-az1388--python-f9683ea7' not found

    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-destroy.20240124-140055.39407.log
    program.go:1256: 
        	Error Trace:	D:/a/pulumi/pulumi/pkg/testing/integration/program.go:1256
        	            				D:/a/pulumi/pulumi/pkg/testing/integration/program.go:1267
        	Error:      	Received unexpected error:
        	            	[D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview] did not succeed after 1 tries
        	Test:       	TestConstructComponentConfigureProviderPython
    program.go:841: 
        	Error Trace:	D:/a/pulumi/pulumi/pkg/testing/integration/program.go:841
        	            				D:/a/pulumi/pulumi/tests/integration/integration_python_acceptance_test.go:239
        	Error:      	Received unexpected error:
        	            	running test preview, update, and edits: empty preview + update: exit status 0xffffffff
        	Test:       	TestConstructComponentConfigureProviderPython

DONE 5 tests, 1 failure in 120.930s
    sp.check_call(args, shell=False)
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gotestsum', '--jsonfile', 'D:\\a\\pulumi\\pulumi\\test-results\\f6382d3c-d203-49f0-8096-caf3e34d2f8c.json', '--packages', 'github.com/pulumi/pulumi/tests/integration', '--', '-count=1', '-cover', '-tags=all xplatform_acceptance', '-timeout', '1h', '-parallel=4', '-shuffle=off', '-p=1', '-race=false', '-run', '^(TestParentRename_issue13179|TestJSONOutput|TestConstructComponentConfigureProviderPython|TestEmptyNodeJS|TestRotatePassphrase)$', '-coverprofile=D:/a/pulumi/pulumi/coverage/go-test-75bf57d8.cov', '-coverpkg=github.com/pulumi/pulumi/pkg/v3/...,github.com/pulumi/pulumi/sdk/v3/...,github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...,github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...,github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...']' returned non-zero exit status 1.
make: *** [Makefile:140: gotestsum/tests/integration] Error 1
::warning Retrying command
cd tests/integration && python 'D:/a/pulumi/pulumi/scripts/go-test.py' -count=1 -cover -tags="all xplatform_acceptance" -timeout 1h -parallel=2 -shuffle=off -p=1 -race=false  $***OPTS*** $***PKGS***
warning: no packages being tested depend on matches for pattern github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...
warning: no packages being tested depend on matches for pattern github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...
warning: no packages being tested depend on matches for pattern github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...
heartbeat
Running: gotestsum --jsonfile D:\a\pulumi\pulumi\test-results\af055029-eb4d-49c5-a772-9a183f8c4f47.json --packages github.com/pulumi/pulumi/tests/integration -- -count=1 -cover -tags=all xplatform_acceptance -timeout 1h -parallel=2 -shuffle=off -p=1 -race=false -run ^(TestParentRename_issue13179|TestJSONOutput|TestConstructComponentConfigureProviderPython|TestEmptyNodeJS|TestRotatePassphrase)$ -coverprofile=D:/a/pulumi/pulumi/coverage/go-test-08c7e61f.cov -coverpkg=github.com/pulumi/pulumi/pkg/v3/...,github.com/pulumi/pulumi/sdk/v3/...,github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...,github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...,github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...
heartbeat
heartbeat
✖  integration (26.921s) (coverage: 5.4% of statements in github.com/pulumi/pulumi/pkg/v3/..., github.com/pulumi/pulumi/sdk/v3/..., github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/..., github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/..., github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...)
```

From https://github.com/pulumi/pulumi/actions/runs/7640630391/job/20817655285

### PR DESCRIPTION
**Pull request by tgummerer**
Since os.Rename isn't atomic on all platforms, currently invoking multiple pulumi commands concurently isn't 100% safe.  Introduce a file mutex to make sure the operation is actually parallel safe.

Fixes #15240 (maybe)

### CODE REVIEW

**Comment by Frassle** [comment]
> Since os.Rename isn't atomic on all platforms,

It's atomic on all platforms as long as the files are on the same device. And the files in question here are in the same folder so definitely the same device.

**Review by Frassle — APPROVED** [review]

**Review by Frassle — CHANGES_REQUESTED** [review]
Actually before merging this can we build a race test, have a load of go routines fighting to set and get config and make sure you always get an fully written file back.

**Comment by tgummerer** [comment]
We do seem to have such a test here: https://github.com/pulumi/pulumi/blob/31dbc79469482974702f0c12d080e76da6e3797e/sdk/go/common/workspace/creds_test.go#L40

But I guess it's kind of hard to actually trigger this, and maybe we never saw it fail because of retries?

**Comment by Frassle** [comment]
> But I guess it's kind of hard to actually trigger this, and maybe we never saw it fail because of retries?

Grim. Maybe just bump the number up a bit till it's fairly consistent to fail without the locks on Windows?

**Comment by tgummerer** [comment]
D'oh, this is a unit test, and we're only running those on Linux, never on Windows.  Since the thing is atomic on Linux, that just works.  Gonna try to maybe make this an "integration test", so we can run it on Windows as well, and see if I can get it to fail there.  Running all the unit tests on Windows looks like quite a bit more work.

**Comment by tgummerer** [comment]
I'm actually not managing to get the test to fail even on Windows.  There's a limit of how many goroutines can be added and the issue is not triggering before that limit is reached.  So I'm not sure if the Go docs are lying, and it's actually atomic on Windows (at least on the version CI is running), or if there's another reason we can't seem to trigger it.

**Comment by tgummerer** [comment]
Given that I'm not managing to make this fail on Windows at all, it seems unlikely that this is actually an issue anywhere in practice. I think this was always a red herring for 404's from the service, and it's not worth making this more complex if we don't need to.

**Pull request closed without merging**
