### PR TITLE
fix: Prevent a deadlock on provider error in py automation api

### LINKED ISSUE #11594: Deadlock on provider error with python automation api
### What happened?

We're building a pythin CLI tool embedding pulumi to deploy a k8s infrastructure, mostly using helm and a few raw pulumi-kubernetes resource objects.

Since we started working on this project we had seemingly random occurences where on error, the process would hang indefinitely (longer than 20 minutes at least). An additional interrupt would kill the process with a backtrace similar to this one:

```
  File "/usr/lib/python3.9/threading.py", line 1415, in _shutdown
    atexit_call()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.9/threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.9/threading.py", line 1049, in _wait_for_tstate_lock                                                                                                                      
    elif lock.acquire(block, timeout):                                                                                                                                                             
  File "/home/lta/.cache/pex/pex-Sc5RmFhbUqEEbfSaL4v-BuOTkSg/bin/mainstack/src/project/pulumi.py", line 117, in _interrupt_handler                                                                 
    self.app.close(1)                                                                                                                                                                              
  File "/home/lta/.cache/pex/pex-Sc5RmFhbUqEEbfSaL4v-BuOTkSg/lib/third_party/python/cement/core/foundation.py", line 1046, in close                                                                
    sys.exit(self.exit_code)                                     
```

I haven't been taking the time to investigate until recently, because in our use case this is annoying but not exactly blocking while we're still in the development phase.

2 days ago I started investigating this more seriously, and I almost lost my mind, as I was not familiar with either asyncio, grpc or the pulumi sdk internals.

Getting back to the point, it appears that when there's an error on the provider side of things, the pulumi process stops and the `_cmd.run_pulumi_cmd` function raises a `Command Error`, which terminates the main thread.

The thing is, a ThreadExecutorPool never terminates and remains running, which prevents the program from exiting, the main thread being stuck trying to acquire the lock in a cleanup function. Using `strace` on the process shows that there are still timers running as well as regular attempts to connect (via IPv6?) to `ffff:127.0.0.1`

Since pulumi silences the asyncio logging, it's not initally obvious but there are some `grpc.RpcError` which are never handled and never cause the `LanguageServer` to stop its event loop.

To be honest, I'm not really sure how come those exceptions never bubble up to the `LanguageServer.Run` method :-/ I'm actually very curious about that.

Nevertheless, it seems installing an exception handler on the loop allow to fetch those unhandled `RpcError` and terminate the loop, which in turn allows the program to actually exit with an error as appropriate. 

I'll send a PR with a *naive*? fix shortly

### Steps to reproduce

Using the automation API, with an inline program, deploy an HelmRelease on a kubernetes cluster with incorrect values that will fail on the kubernetes side.

Most helm chart allow to configure the `resources` of a deployment. I used this to consistently reproduce:

```yaml
resources:
  requests:
    cpu: 100asd
```

### Expected Behavior

I'd except to receive an exception that would terminate the problem

### Actual Behavior

The exception is raised, but the program never finished and is stuck trying to acquire a lock

### Output of `pulumi about`

Automation API, no easy way to do this.

- stock Python 3.9.2 from debian
- pulumi 3.43.1 (the latest 3.48.0 exhibits the same behavior)

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by elthariel**
# Description

The rationale behind this change is explained in the linked issue. I haven't worked on the Checklist below, as I'd like to get an eye with more pulumi knownledge on the issue beforehand.

Also, reproducing deadlocks in unit tests is always quite tricky, so I'd rather not do it until I'm sure this is the proper approach

Fixes #11594

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by justinvp — APPROVED** [review]
LGTM. Thanks, @elthariel! I'll get it merged after the acceptance tests have run.

**Comment by elthariel** [comment]
I've noticed in the tests that there was a lint error, so I've updated my PR to fix the issue. I hope it doesn't mess with the acceptance tests

**Comment by justinvp** [comment]
No worries, I'll re-run

**Comment by elthariel** [comment]
That's weird. It doesn't seems like it ran the tests again. At least I don't see anything in the actions tab

**Comment by justinvp** [comment]
> That's weird. It doesn't seems like it ran the tests again.

Strange. Not sure why. (We've been tweaking how our CI is setup, so there may be some kinks to work out still). In any case, I ran the linter locally on your branch and it LGTM.

**Comment by justinvp** [comment]
bors merge

**Pull request merged**
