### PR TITLE
Check worktree is clean before releasing

### PR DESCRIPTION
**Pull request by komalali**
# Description

* Adds `lint` step as required before release.
* Adds a new job `check-clean-worktree` to ensure the git work tree is clean before releasing.

I elected to add a separate job for this step to avoid doing it 8 times as part of build-and-test.

I unfortunately don't know how to test this without a release. However, this is already a part of the `master` workflow: https://github.com/pulumi/pulumi-aws/blob/master/.github/workflows/master.yml#L68-L69

Fixes https://github.com/pulumi/pulumi/issues/8092

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by pgavlin — CHANGES_REQUESTED** [review]
> I elected to add a separate job for this step to avoid doing it 8 times as part of build-and-test.

I don't think that this is going to give the results that we want: I think that this is only going to check that the worktree is clean immediately after cloning the repository, which will always be true. I think that we're going to need to do this as part of each leg after building, as that is where we can end up leaving the worktree dirty.

**Comment by pgavlin** [comment]
(I think that checking for a clean worktree is pretty quick, so I don't think we'll notice the overhead of rerunning it)

**Comment by komalali** [comment]
>I think that we're going to need to do this as part of each leg after building, as that is where we can end up leaving the worktree dirty.

Thanks you for clarifying! That makes way more sense 😅

**Review by pgavlin — APPROVED** [review]

**Comment by komalali** [comment]
Unrelated test failure captured in https://github.com/pulumi/pulumi/issues/8061#issuecomment-929700982

**Pull request merged**
