### PR TITLE
[cli] Add the ability to protect resources via pulumi stack protect

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #6242

[asciicast](https://asciinema.org/a/jCigBkgTNY5qDV3zTuiClRgzW)

### CODE REVIEW

**Review by infin8x — APPROVED** [review]

**Review by komalali — COMMENTED** [review]
I have a general question. Am I understanding correctly that this command doesn't do anything if the resource isn't already protected? Then what is this command doing? And should it return an error if the resource isn't already protected with the resource option?

**Comment by stack72** [comment]
@komalali this follows *exactly* the implementation of the unprotect - it uses the same func and just passed the opposite

It has a super specific use case...

The customer who has been using this hasn't complained about the output so I wasn't sure of pulling at that thread but happy to it you think we should check it out? (Note: it's an easy change)

**Comment by komalali** [comment]
@stack72 since this is now a public command that other folks are likely to see, I think it's worth doing our due diligence to make sure we don't confuse people. I realize that this is more of a `undo unprotect` rather than an actual `protect` but it is a little odd.

If it's not entirely straightforward I'm okay to leave it as is, but if it's easy that'd be nice.

**Comment by stack72** [comment]
Great point!

So one thought on the experience here

When a user passes '--all' - I will keep a list of the resources it can't protect (and unprotect by fixing the only one) and then I'll print an error saying unable to protect (or unprotect) the following urns
- *urn1
- *urn2
Etc

Sound ok?

**Comment by komalali** [comment]
Yup sounds great! Maybe we just want to print a warning about the resources we couldn't protect/unprotect rather than an error in the `--all` case, but we should definitely error when there's a `pulumi state protect <resource>` and that resource doesn't have the correct resource option set.

**Comment by stack72** [comment]
It'll be with you in the morning ;)

**Comment by stack72** [comment]
So @komalali / @infin8x I spent the morning looking at making the change to error if the resource wasn't actually able to be protected / unprotected (due to the existing state). The way the function runs is that we don't save the state on a resource by resource basis so if we error out then we are not changing any resources. This is due to how `runTotalStateEdit` works - I think we may be pulling at a thread here to refactor how all of this would work...

My thoughts for this would be as follows:

1. We accept the current workflow (where we don't error) and we open an issue to follow up in the area. Technically it's not a breaking change - it's introducing better error handling and would allow us to deliver the value to the user now
2. We update the text on the command help to point out that we will only change eligible resources (ie. if we run protect then the resource won't be updated if already updated). We can also update the user message to suggest all eligible resources have been updated
3. We can add some diagnostics messages to suggest which resources have been changed

Thoughts?  

Paul

**Comment by komalali** [comment]
Sure, that's fine with me. Looks like @infin8x already approved the PR too so perhaps my usability trepidations are unwarranted 🤷

**Comment by stack72** [comment]
> Sure, that's fine with me. Looks like @infin8x already approved the PR too so perhaps my usability trepidations are unwarranted 🤷

I defo don't think that's the case at all! You made some great points on it - things we need to follow up and fix IMO

**Comment by infin8x** [comment]
100% agree. Should've left a note with my approval - y'all are still much more familiar with the CLI ergonomics than I am, and I'll defer to you on making sure we ship the best experience.

**Comment by stack72** [comment]
closing this out

**Pull request closed without merging**
