### PR TITLE
Adds TPL based runTask to Deployment

### PR DESCRIPTION
**Pull request by yreynhout**
Not entirely sure how useful this is to have in the library, but it's something I keep embedding in my own codebase.

### CODE REVIEW

**Comment by yreynhout** [comment]
Hi @mikhailshilkov - pretty much done from my point of view - just didn't know whether it was deemed a useful addition or not. Your call to be honest.

**Comment by mikhailshilkov** [comment]
Great! Do you mind rebasing on the latest and adding a short node to CHANGELOG.md?

**Comment by yreynhout** [comment]
Sure, no problem

**Comment by yreynhout** [comment]
@mikhailshilkov done.

**Pull request merged**
