### PR TITLE
deps(pkg): Upgrade to pulumi-java v0.8.0

### PR DESCRIPTION
**Pull request by abhinav**
Upgrades to the most recent release of pulumi-java.
This release changes the code generator to generate build.gradle files
compatible with Gradle 8.0 -- which is the default on GitHub now.
This should help resolve broken downstream codegen tests.

Steps taken to generate this change:

    cd pkg
    go get github.com/pulumi/pulumi-java/pkg@v0.8.0
    cd ..

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12327** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12327" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12327?utm_source=stack-comment).

**Review by dixler — APPROVED** [review]

**Comment by dixler** [comment]
bors merge

**Comment by abhinav** [comment]
This will fail to merge. This updates some dependencies which have some new deprecated APIs.

```
  Running [/home/runner/golangci-lint-1.51.2-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=pkg --config ../.golangci.yml ./...] in [/home/runner/work/pulumi/pulumi/pkg] ...
  Error: SA1019: loggingpb.ListLogEntriesRequest is deprecated: Please use types in: cloud.google.com/go/logging/apiv2/loggingpb  (staticcheck)
  Error: SA1019: loggingpb.LogEntry is deprecated: Please use types in: cloud.google.com/go/logging/apiv2/loggingpb  (staticcheck)
  Error: SA1019: "google.golang.org/genproto/googleapis/logging/v2" is deprecated: Please use types in: cloud.google.com/go/logging/apiv2/loggingpb. Please read https://github.com/googleapis/google-cloud-go/blob/main/migration.md for more details.  (staticcheck)

```

**Comment by dixler** [comment]
bors cancel

**Comment by abhinav** [comment]
https://github.com/googleapis/google-cloud-go/blob/main/migration.md says that this switch is safe but I think it makes sense to do that separately.

**Comment by abhinav** [comment]
Migration of logging API tracked in #12328

**Comment by abhinav** [comment]
Merging with higher priority because this will unbreak some builds.

**Comment by abhinav** [comment]
bors merge p=1

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
(merging because this was green and unbreaks some codegen.)

**Comment by abhinav** [comment]
From the failed codegen test:

```
go: downloading github.com/pulumi/pulumi-java/pkg v0.7.1
```

That's not right

**Comment by abhinav** [comment]
Okay, I figured it out.
Downstream providers have their own dependency on pulumi-java via their dependency on pu/pu.
So they won't pick up the new version automatically until pu/pu releases with the new version,
and then they all update their dependency on pu/pu's new release to pick up the transitive update to pu-java.

I think it might be easier to change the codegen tests to include a pu-java replacement, the same way we do a pu-terraform-bridge replacement during the test.

**Comment by abhinav** [comment]
Oh. 🤦 
Doesn't matter what version we're using here; it won't regenerate the build.gradle in those repositories.
Reverting that override change.

**Comment by abhinav** [comment]
Will land despite codegen failures per approval from and @justinvp @Zaid-Ajaj @Frassle

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
