### PR TITLE
Fix cloudBackendReference.String

### PR DESCRIPTION
**Pull request by Frassle**
# Description

`cloudBackendReference.String` didn't use the same logic for infering the default owner as `cloudBackend.ParseStackReference`. This was partically evident during `pulumi stack select` where if you had two stacks "user/foo" and "org/bar" then `stack ls` would print them as:
```
foo
org/bar
```

If you then set the workspace default-org `stack ls` would still print them in the same way. But when passing "foo" to `ParseStackReference` it would pick up the implicit owner of "org" not "user" (because the default-org is set), and then you'd get a an error that the stack you selected didn't exist.

`String` now matches `ParseStackReference` and checks if a default-org is set and elides that name, not the user name if so.

Fixes https://github.com/pulumi/pulumi/issues/9018

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
> Are there any scenarios when this can break users?

I don't think so, its only going to change for people using `org set-default` and I think the only difference that could effect people is `pulumi stack --show-name` will print differently but it should print in a way that is now parseable.

**Comment by Frassle** [comment]
>  Do you want to add some tests for `String()`?

Testing these parts of the system is really awkward right now, but I plan on changing this around some more as part of the backend work and should be able to add tests then.

**Comment by mikhailshilkov** [comment]
> Testing these parts of the system is really awkward right now,

Could you expand on this? I guess I'm naive but why not create a `cloudBackendReference` and call a `String()` on it?

**Comment by Frassle** [comment]
> Could you expand on this? I guess I'm naive but why not create a cloudBackendReference and call a String() on it?

Because that needs a whole `cloudBackend` as well. I've got plans to simplify references such that that won't be needed.

**Review by mikhailshilkov — APPROVED** [review]
LGTM

**Pull request merged**
