### PR TITLE
Debug print incoming protos

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
Huh I thought everywhere already logged these.

**Comment by t0yv0** [comment]
Perhaps I'm not sure where to look? How do you look at these?

Sharing this without intention to merge as debug help for @dixler

**Comment by t0yv0** [comment]
If I recall correctly, the default stuff I saw printed in the logs is a lossy form it does not distinguish if "true" is a boolean or string literal "true" and it caused some insanity for our debugging; this form is very explicit.

**Comment by Frassle** [comment]
Ah right yeh a few lines down from your change there's:
```
logging.V(9).Infof("Unmarshaling property for RPC[%s]: %s=%v", opts.Label, key, v)
```
but that's the value after unmarshaling, not the protobuf value.

I think there's value in tidying this up so we can see the proto value and the unmarshaled value.

Maybe changing that logging to something like:
```
protoValue := props.Fields[key]
logging.V(9).Infof("Unmarshaling property for RPC[%s]: %s=%v", opts.Label, key, proto.MarshalTextString(protoValue))
v, err := UnmarshalPropertyValue(pk, protoValue, opts)
		if err != nil {
			return nil, err
		} else if v != nil {
			logging.V(9).Infof("Unmarshaled property for RPC[%s]: %s=%v", opts.Label, key, v)
...
```

**Comment by t0yv0** [comment]
Closing in favor of https://github.com/pulumi/pulumi/pull/10193

**Pull request closed without merging**
