### PR TITLE
Reword step failure message prefix during an `update`

### PR DESCRIPTION
**Pull request by ellismg**
The text "Plan applied failed: " is pretty inscrutable given our
current system. While both "plan" and "apply" are concepts inside the
the implementation of the CLI, we usually talk in terms of `preview`
and `update`. I suspect there are some cases where this prefix is not
100% technically correct, and if there's a better short way of saying
something more correct, I would love to adopt that instead, but as is,
I would really love to get rid of the "Plan apply failed" text in our
system, it pains me every time I read it.

### CODE REVIEW

**Comment by ellismg** [comment]
Opening this because I think we need to do something here, but I am not wed to the exact text. As long as it doesn't contain words we don't normally use (like `plan` and `apply`) I would be happy.

**Comment by ellismg** [comment]
Here's one example where I attempt to delete an S3 bucket that still has items in it:

>    error: Plan apply failed: deleting urn:pulumi:matt::pulumi-service::aws:s3/bucket:Bucket::checkpoint-bucket: error deleting S3 Bucket (checkpoint-bucket-f5e21ab): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
    	status code: 409, request id: 25548BCE6BE84884, host id: 5FmMRlOqB+Gmt09rLLJq5eMwGAM6RMRV4j54ChXwxCbTixA74G5x2ZQHruECCtlwTZ7kIy30qSU=

> My recollection was that in context this is more about the update/destroy/preview operation failing than about the “resource operation”.

By this do you mean a message about the /overall/ "update", "preview" or "destroy" operation?  This is not used there.  Here's the full output from the overall update:

```
Destroying (matt):

     Type                 Name                 Status                  Info
     pulumi:pulumi:Stack  pulumi-service-matt  **failed**              1 error
 -   └─ aws:s3:Bucket     checkpoint-bucket    **deleting failed**     1 error
 
Diagnostics:
  aws:s3:Bucket (checkpoint-bucket):
    error: Plan apply failed: deleting urn:pulumi:matt::pulumi-service::aws:s3/bucket:Bucket::checkpoint-bucket: error deleting S3 Bucket (checkpoint-bucket-f5e21ab): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
    	status code: 409, request id: 5732624E1934FBC2, host id: pMeeJ8iqupjVdEgdUIid+uNZOM9LBt5DZLiahGaIlSm/9GlSLZy6FabYnubeYwd1O1LE2GU9DmM=
 
  pulumi:pulumi:Stack (pulumi-service-matt):
    error: update failed
 
Permalink: [elided]
```

These errors are generate per step, so the failing application of any step will generate them.  They are tied to a specific resource.

**Comment by lukehoban** [comment]
Yeah - my recollection was indeed wrong.  This shows up for individual resource operations, not full deployments.

There's another example here: https://github.com/pulumi/pulumi-kubernetes/issues/667

Looking at these:
1. I honestly wonder if it would be better to just leave off this layer of wrapping altogether?
2. If we are going to keep a layer of wrapping, shouldn't it be lowercased?
3. If we are going to keep it, either `resource operation failed` or `operation failed` (or, if it were possible to include the kind of resource `delete failed`/`update failed`)

**Comment by pgavlin** [comment]
> I honestly wonder if it would be better to just leave off this layer of wrapping altogether?

This seems like the right path forwards. We already inform the user that the update/preview failed, so this message seems redundant.

**Comment by pgavlin** [comment]
@lukehoban any reservations on taking this?

**Comment by lukehoban** [comment]
Happy to take it - but sounds like we had agreed above that we may as well go further and remove this wrapping altogether?

**Comment by pgavlin** [comment]
Let's take this as-is and follow up on the additional step of removing the wrapping altogether.

**Comment by pgavlin** [comment]
Ehh, now that I see again how simple this change is I'm going to go ahead and remove the wrapping.

**Pull request merged**
