### PR TITLE
Un-experiment update plans

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Also adds a new prompt "yes with generated plan" for updates, this only shows up if you don't already have "--plan" set and lets you run the update with the plan generated by the automatic preview.

If running in experimental mode (PULUMI_EXPERIMENTAL=true) this option doesn't show up because the current behavior in that mode is to use the plan passed in or if none was passed in to use the one from preview.

Fixes https://github.com/pulumi/pulumi/issues/9687

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
Want to check that the experimental tests in https://github.com/pulumi/examples/actions/workflows/cron.yml are looking ok before going ahead and merging this. Last few days failed because of gcp auth issues.

**Comment by mikhailshilkov** [comment]
Should we ship this in multiple steps?

1. Add the CLI option but only if the experimental flag is set.
2. Let more internal folks test it on their workflows.
3. Prepare all the docs changes.
4. Remove the experimental option.

cc @lukehoban on product review and rollout plan here.

**Comment by Frassle** [comment]
> Add the CLI option but only if the experimental flag is set.

So the behavior currently is that if the experimental flag is set then "yes" uses the plan from preview. I think we should probably keep that actually, such that under experimental this option doesn't show up because it's what "yes" does anyway.

I wanted to make this option show up for _everyone_ though so that we'd start getting more users just see it wonder what it does and give it a try.

**Comment by mikhailshilkov** [comment]
> if the experimental flag is set then "yes" uses the plan from preview

Ah, I forgot about this then. I thought the flag only enables extra CLI options. Could you please extend the PR description to mention full delta between the current and the new behavior?

**Comment by Frassle** [comment]
After ideation we have a new plan for how to expose this, so I'm closing this PR off.

**Pull request closed without merging**
