### PR TITLE
Don't print large integers in scientfic notation

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Fixes https://github.com/pulumi/pulumi/issues/13016

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Zaid-Ajaj — APPROVED** [review]

**Comment by Frassle** [comment]
Looks like tests timed out

bors retry

**Comment by Frassle** [comment]
Looks like tests timed out

bors retry

**Comment by justinvp** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
