### PR TITLE
Move assets and archives to their own package

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

This PR is motivated by https://github.com/pulumi/pulumi/pull/15145.

`resource.*` should be built on top of `property.Value`,[^1] which means that `resource`
needs to be able to import `property.Value`, and so `property` cannot import
`resource`. Since Assets and Archives are both types of properties, they must be moved out
of `resource`.

[^1]: For example: https://github.com/pulumi/pulumi/blob/a1d686227cd7e3c70c51bd772450cb0cd57c1479/sdk/go/common/resource/resource_state.go#L35-L36

## Open Question

This PR moves them to their own sub-folders in `resource`. Should `asset` and `archive`
live somewhere more high level, like `sdk/go/property/{asset,archive}`?

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [ ] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Comment by Frassle** [comment]
Being a _very_ clearly core part of the public API my feeling is these shouldn't really be anywhere in "sdk/go/common" (y'all know my opinions on that folder).

It's very awkward that there's the PropertyValue model for Asset&Archive but also the Pulumi Program model for them as well. Ideally we'd just have the one model to represent this data, but well hard to unify these now.

I'd not think it worth it moving them into their own module just for the sake of better name spacing though?

**Comment by iwahbe** [comment]
> Being a _very_ clearly core part of the public API my feeling is these shouldn't really be anywhere in "sdk/go/common" (y'all know my opinions on that folder).
> 
> It's very awkward that there's the PropertyValue model for Asset&Archive but also the Pulumi Program model for them as well. Ideally we'd just have the one model to represent this data, but well hard to unify these now.
> 
> I'd not think it worth it moving them into their own module just for the sake of better name spacing though?

I hadn't finished the PR (or description). I have since copied my first commit description (I wish GH would surface those) into the PR description. This is the important part:

> resource.* should be built on top of property.Value, which means that resource
needs to be able to import property.Value, and so property cannot import
resource. Since Assets and Archives are both types of properties, they must be moved out
of resource.

**Comment by Frassle** [comment]
Oh module loops 😞 

I still have concerns about this being the right approach.

1. Are we going to break significant usage by moving these types?
2. Should these go somewhere outside sdk/go/common like we're planning on moving PropertyValue up to /sdk/go/pulumi?
3. Should we (like with PropertyValue) just copy these to somewhere new, with the plan to just delete the current ones when we delete the old PropertyValue?

**Comment by Frassle** [comment]
> sdk/go/property/

This looks tempting to me, although not 100% sure about "property" as the module name. Alternative names could be "protocol", "schema", "types". Something to get across that this is the core value type system we use in Pulumi. PropertyValue is finding its way to more and more places so it's less and less _strictly_ just resource properties.

**Comment by iwahbe** [comment]
> Oh module loops 😞

😞 

> 1. Are we going to break significant usage by moving these types?

No. I have left a skeleton `resource/assets.go` to maintain full backwards compatibility. This is not a breaking change.

> 2. Should these go somewhere outside sdk/go/common like we're planning on moving PropertyValue up to /sdk/go/pulumi?

Probably, but I'm not sure where/how. Unlike `resource.PropertyValue`, assets and archives have mixed their representation with associated logic, so I'm not sure where we can cleanly extract them to. I'm trying to avoid moving serialization logic into `sdk/go/pulumi`, but it seems like `Asset` and `Archive` are designed to carry that with them. We could break of the (de)serialization functions, but I wasn't sure what the re-action would be (and it's a breaking change).

> 3. Should we (like with PropertyValue) just copy these to somewhere new, with the plan to just delete the current ones when we delete the old PropertyValue?

I wanted to rewrite `resource.PropertyValue` with improved (and thus different) semantics. I don't have such a desire for assets and archives. This was just a copy+paste based move, so I don't think we need to keep two implementations.

**Comment by Frassle** [comment]
Hmm all a bit grim, lemme think about it a bit.

**Comment by iwahbe** [comment]
@Frassle any thoughts here?

**Review by Frassle — APPROVED** [review]
I don't like it but short of an SDK fork I can't think of any way to do this better right now.

**Pull request merged**
