### PR TITLE
Build the windows build on GHA rather than AppVeyor

### PR DESCRIPTION
**Pull request by stack72**
This will only build PRs in that environment - Publish will still happen in AppVeyor for the time being

### CODE REVIEW

**Comment by stack72** [comment]
@lukehoban the GHA now does exactly what AppVeyor does - I'd like to drive this forward to use GHA for the PR builds. The publish of the Windows package will not move from AppVeyor for the time being

Thoughts?

**Comment by leezen** [comment]
I'm curious if you are able to repro https://github.com/pulumi/pulumi/issues/3981 in a GHA build?

**Comment by stack72** [comment]
@leezen nope - I am not even able to reproduce it in AppVeyor - I would need to look through the code and find out why it's not reproducible for us in Windows builds...

**Comment by stack72** [comment]
ok @lukehoban *now* this is ready for review :) This moves us away from AppVeyor (the the cost of running it) and we get exactly the same build results that AppVeyor gave us

The Python issue needs to be investigated separately

**Pull request merged**
