### PR TITLE
Handle invalid UTF-8 characters before RPC calls

### PR DESCRIPTION
**Pull request by lblackstone**
Several users reported cases where error messages would
cause a panic if they contained accented characters. I wasn't
able to reproduce this failure locally, but tracked down the
panic to logging gRPC calls. The Message field is typed as
a string, which requires all of the characters to be valid UTF-8.

This change runs each log string through the strings.ToValidUTF8
function, which will replace any invalid characters with the
"unknown" character. This should prevent the the logger from
panicking.

Fix https://github.com/pulumi/pulumi/issues/4044
Fix https://github.com/pulumi/pulumi/issues/4342
Fix https://github.com/pulumi/pulumi/issues/4580

### CODE REVIEW

**Comment by pgavlin** [comment]
So this fixes the panic, but the characters still won't be rendered properly, right? Can you give an example of the output with this change when the message contains characters from a non-UTF8 code page?

**Comment by lblackstone** [comment]
I wasn't able to reproduce the error locally, but it should render like this:
```
Identification des projets � restaurer...
```

I tried setting that error message directly in the same places from the panic stack in #4580, and also tried changing the code page to a bunch of different languages. It may be specific to Windows, because all three of those reports seem to be on Windows machines.

**Comment by pgavlin** [comment]
> It may be specific to Windows, because all three of those reports seem to be on Windows machines.

I believe that is the case. From the reports, it sounds like these issues are due to messages that are encoded using a non-UTF8 code page:
- #4044:
  > So luckily there is a workaround by switching the codepage to UTF-8 (chcp 65001). Executing pulumi up after that seems to do the trick.
- #4342: 
  >  error: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: Unable to encode the output with cp1252 encoding. Unsupported characters are discarded.

We should accept this change, since it does fix the panic, but it doesn't solve the UX issue of improper rendering of characters. We should file an issue for followup. I think the fix is to detect the code page in use on Windows and transcode the output of other tools into UTF-8.

**Comment by mikhailshilkov** [comment]
@lblackstone What needs to be released for this, the CLI or a provider?

**Comment by lblackstone** [comment]
CLI, I think. @pgavlin?

**Comment by pgavlin** [comment]
Yep, that's right

**Pull request merged**
