### PR TITLE
Adding support for Azure Storage backend.

### PR DESCRIPTION
**Pull request by davidobrien1985**
This change will add support for Azure Storage account backend for GitHub Actions.
Use by setting the following environment variables.

```
PULUMI_BACKEND: "azurestorage"
AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
```

### CODE REVIEW

**Comment by lukehoban** [comment]
I was thinking we would just allow a `PULUMI_BACKEND` and pass that literally to the login command. Then it could be used for any backend you need (Azure blob, S3, GCS, etc). The user could construct the appropriate url shape for a Pulumi backend. Is that possible (and perhaps even easier?).

**Comment by davidobrien1985** [comment]
Right, yeah, that might make it easier for the user.

```
PULUMI_BACKEND: ${{ secrets.PULUMI_BACKEND }}
AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
```

For `PULUMI_BACKEND` values follow https://www.pulumi.com/docs/intro/concepts/state/#self-managed-backend

**Comment by davidobrien1985** [comment]
How is this released @lukehoban ? The CI build for this seems to be tied to the actual pulumi binary release. Can this be released independently?

**Comment by lukehoban** [comment]
> How is this released @lukehoban ? The CI build for this seems to be tied to the actual pulumi binary release. Can this be released independently?

Currently it’s released with all versioned releases of the Pulumi CLI. We want versions to stay aligned between these two.

**Comment by davidobrien1985** [comment]
@lukehoban fair enough. Do you expect me to update the changelog or will that be done by someone on your end?

**Comment by praneetloke** [comment]
@davidobrien1985 I'll open a separate PR with your changes for this. That way, the PR build can run. Thank you for opening this PR!

**Comment by praneetloke** [comment]
Closing this in favor of #4243.

**Pull request closed without merging**
