### PR TITLE
Fix deletes not being show in `refresh` when using json output

### PR DESCRIPTION
**Pull request by same-id**
Introduced in https://github.com/pulumi/pulumi/pull/16146

@lukehoban

### CODE REVIEW

**Comment by same-id** [comment]
Actually I'm pretty sure that we additionally need to update `same`s as well:

```
if refresh && ((m.Op == deploy.OpUpdate && m.DetailedDiff != nil) || m.Op == deploy.OpDelete || m.Op == deploy.OpSame) {
```

Otherwise all same resources are still shown as `update` and `--show-sames` flag does not work.

Any thought?

**Comment by lunaris** [comment]
Hi @same-id; thanks for raising this. Sorry for being slow -- we are currently working hard on some internal concerns but I intend to take a look at this as soon as possible :pray:

**Comment by same-id** [comment]
@lunaris thanks

Adding my slack message for more context:
https://pulumi-community.slack.com/archives/C84L4E3N1/p1722512361281309

**Comment by same-id** [comment]
Thanks, still I'm not sure about this PR as a contributor

It does fix a bug, and is a good step forward, but it seems that the entire `--json` flow is poorly defined/handled - at least from my perspective, you can see more in my slack message - pasting it here:

> Is there any way to run pulumi refresh with a plan?
> I want to show a nice textual preview of what pulumi refresh would do in some GHA workflow , and then apply it after an approval from a different person.
> From engineering perspective, previewing a refresh and then applying it to the state should be even easier than previewing a pulumi update because it just involves updating the state file - but to my amazement there is no normal way to do it.
> I tried fiddling with json output for pulumi refresh but I am not sure what this feature is good for:
> It neither gives a nice textual diff / summary of what changed - so I have to parse it additionally to display it
> It does not output the updated stack state which can be them simply manually uploaded using stack import.
> Would love to get some assistance on this.
> (P.S. pulumi refresh --json gives weird outputs - I don’t see deletions, and it shows same resources as updates)

**Comment by lunaris** [comment]
I think `refresh` with plans is not something we've considered yet, and it would definitely need some thinking to be a proper feature. I'd like to merge the changes here regardless since they fix an issue as you say, and perhaps open an issue for the refresh plans feature.

**Review by lunaris — APPROVED** [review]

**Pull request merged**
