### PR TITLE
[auto/dotnet] Bump YamlDotNet to 11.1.1

### LINKED ISSUE #6914: Bump YamlDotNet to latest version
The version used by [sdk/dotnet/Pulumi.Automation/Pulumi.Automation](https://github.com/pulumi/pulumi/blob/c0b5339cf376408e81c30e63bd09c2e6a21500bf/sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj#L40) does not load when the dotnet host application already uses a later version. This is due to some breaking changes in the YamlDotNet api surface ([here](https://github.com/aaubry/YamlDotNet/commit/315c368f0b8762003df2ceace0030f471c72a401#diff-9651828a920e4d22069eb3a3bb34e1716c93055f968b0aeea7f14b6e6ce34c5e) and [here](https://github.com/aaubry/YamlDotNet/commit/669841428bf962e8e6a64c6719aedd6edf006d9b#diff-9651828a920e4d22069eb3a3bb34e1716c93055f968b0aeea7f14b6e6ce34c5e)).

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #6914.

### CODE REVIEW

**Comment by gitfool** [comment]
@orionstudt PTAL

**Review by mikhailshilkov — APPROVED** [review]
LGTM. @orionstudt okay to merge?

**Comment by orionstudt** [comment]
LGTM!

**Comment by mikhailshilkov** [comment]
@gitfool Could you please rebase to get rid of the conflict and I'll merge asap? Thank you!

**Comment by gitfool** [comment]
@mikhailshilkov rebased.

**Pull request merged**
