### PR TITLE
[codegen/python] Rename conflicting ResourceArgs classes

### PR DESCRIPTION
**Pull request by justinvp**
Python resource constructor overloads were [recently](https://github.com/pulumi/pulumi/pull/6525) added that accept a `<Resource>Args` class for input properties, as
an alternative to the other constructor overload that accepts keyword arguments. The name of the new args class is the
name of the resource concatenated with an `Args` suffix.

Some providers (e.g. Kubernetes, Azure Native, and Google Native) have input types with the same name as resources in
the same module, which results in two different `<Resource>Args` classes in the same module.

When you try to use the new args class with the constructor, e.g.:

```python
pulumi_kubernetes.storage.v1.StorageClass(
            resource_name='string',
            args=pulumi_kubernetes.storage.v1.StorageClassArgs(...),
            opts=pulumi.ResourceOptions(...),
)
```

You run into an error, because `pulumi_kubernetes.storage.v1.StorageClassArgs` is actually referring to the existing
input type rather than the intended `StorageClassArgs` class for the constructor arguments.

Having the duplicate classes hasn't broken existing usage of the input type because we "export" all the input types for
a module _after_ all the resources and resource args classes are exported, so the input type just ends up "overwriting"
the duplicate resource args class.

Other languages don't have this problem because the input type is either in it's own module/namespace (e.g. Node.js and
.NET) or a different name is used for the input type (Go). But with Python, the input types and resources are all
available in the same module.

To address this for Python, when there is an input type in the same module with the same name as the resource, the args
class for the resource will be emitted as `<Resource>InitArgs` instead of `<Resource>Args`.

Technically, renaming the type is a breaking change, but since this functionality is so new and since the way one would generally try to import it is broken anyway, it seems worth doing.

Alternatively, I considered making this a schema flag that the codegenerator could look at, where all the `<Resource>Args` in a package would be emitted as `<Resource>InitArgs` -- but this would break anyone using the new args class (when there isn't a conflicting input type).

The downside to this approach is that if a provider ever adds a conflicting type in the future, or even an existing type that ends up being used as an input in the future, then the resource args class will get renamed from `<Resource>Args` to `<Resource>InitArgs`. But I suspect this is a rare occurrence and if it does ever happen, at that point we can decide whether it's an acceptable change.

Fixes https://github.com/pulumi/pulumi-kubernetes/issues/1571

## Reference

Last week I checked all our provider schemas to see which types and resources had the same tokens. Here's what I found:

```
azure-native: azure-native:cognitiveservices:PrivateEndpointConnection
azure-native: azure-native:compute:SshPublicKey
azure-native: azure-native:compute:VirtualMachineScaleSetExtension
azure-native: azure-native:datafactory:ManagedPrivateEndpoint
azure-native: azure-native:dataprotection:BackupInstance
azure-native: azure-native:dataprotection:BackupPolicy
azure-native: azure-native:dataprotection:BackupVault
azure-native: azure-native:delegatednetwork:ControllerDetails
azure-native: azure-native:devices:PrivateEndpointConnection
azure-native: azure-native:digitaltwins:PrivateEndpointConnection
azure-native: azure-native:healthcareapis:PrivateEndpointConnection
azure-native: azure-native:insights:ActionGroup
azure-native: azure-native:logic:IntegrationServiceEnvironment
azure-native: azure-native:machinelearning:CommitmentPlan
azure-native: azure-native:network:ApplicationSecurityGroup
azure-native: azure-native:network:Endpoint
azure-native: azure-native:network:ExpressRouteCircuitAuthorization
azure-native: azure-native:network:ExpressRouteCircuitConnection
azure-native: azure-native:network:ExpressRouteCircuitPeering
azure-native: azure-native:network:InboundNatRule
azure-native: azure-native:network:LocalNetworkGateway
azure-native: azure-native:network:NatGateway
azure-native: azure-native:network:NatRule
azure-native: azure-native:network:NetworkSecurityGroup
azure-native: azure-native:network:PrivateLinkService
azure-native: azure-native:network:PublicIPAddress
azure-native: azure-native:network:Route
azure-native: azure-native:network:RouteFilterRule
azure-native: azure-native:network:RouteTable
azure-native: azure-native:network:SecurityRule
azure-native: azure-native:network:ServiceEndpointPolicy
azure-native: azure-native:network:ServiceEndpointPolicyDefinition
azure-native: azure-native:network:Subnet
azure-native: azure-native:network:VirtualHubRouteTableV2
azure-native: azure-native:network:VirtualNetworkGateway
azure-native: azure-native:network:VirtualNetworkPeering
azure-native: azure-native:network:VirtualNetworkTap
azure-native: azure-native:network:VpnConnection
azure-native: azure-native:providerhub:ResourceTypeRegistration
azure-native: azure-native:recoveryservices:PrivateEndpointConnection
azure-native: azure-native:streamanalytics:Function
azure-native: azure-native:streamanalytics:Input
azure-native: azure-native:streamanalytics:Output
azure-native: azure-native:synapse:PrivateEndpointConnection
google-native: google-native:cloudbuild/v1:Build
google-native: google-native:compute/alpha:Reservation
google-native: google-native:compute/beta:Reservation
google-native: google-native:compute/v1:Reservation
google-native: google-native:sqladmin/v1beta4:SslCert
google-native: google-native:storage/v1:BucketAccessControl
google-native: google-native:storage/v1:ObjectAccessControl
kubernetes: kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration
kubernetes: kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfigurationList
kubernetes: kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration
kubernetes: kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfigurationList
kubernetes: kubernetes:admissionregistration.k8s.io/v1beta1:MutatingWebhookConfiguration
kubernetes: kubernetes:admissionregistration.k8s.io/v1beta1:MutatingWebhookConfigurationList
kubernetes: kubernetes:admissionregistration.k8s.io/v1beta1:ValidatingWebhookConfiguration
kubernetes: kubernetes:admissionregistration.k8s.io/v1beta1:ValidatingWebhookConfigurationList
kubernetes: kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition
kubernetes: kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinitionList
kubernetes: kubernetes:apiextensions.k8s.io/v1beta1:CustomResourceDefinition
kubernetes: kubernetes:apiextensions.k8s.io/v1beta1:CustomResourceDefinitionList
kubernetes: kubernetes:apiregistration.k8s.io/v1:APIService
kubernetes: kubernetes:apiregistration.k8s.io/v1:APIServiceList
kubernetes: kubernetes:apiregistration.k8s.io/v1beta1:APIService
kubernetes: kubernetes:apiregistration.k8s.io/v1beta1:APIServiceList
kubernetes: kubernetes:apps/v1:ControllerRevision
kubernetes: kubernetes:apps/v1:ControllerRevisionList
kubernetes: kubernetes:apps/v1:DaemonSet
kubernetes: kubernetes:apps/v1:DaemonSetList
kubernetes: kubernetes:apps/v1:Deployment
kubernetes: kubernetes:apps/v1:DeploymentList
kubernetes: kubernetes:apps/v1:ReplicaSet
kubernetes: kubernetes:apps/v1:ReplicaSetList
kubernetes: kubernetes:apps/v1:StatefulSet
kubernetes: kubernetes:apps/v1:StatefulSetList
kubernetes: kubernetes:apps/v1beta1:ControllerRevision
kubernetes: kubernetes:apps/v1beta1:ControllerRevisionList
kubernetes: kubernetes:apps/v1beta1:Deployment
kubernetes: kubernetes:apps/v1beta1:DeploymentList
kubernetes: kubernetes:apps/v1beta1:StatefulSet
kubernetes: kubernetes:apps/v1beta1:StatefulSetList
kubernetes: kubernetes:apps/v1beta2:ControllerRevision
kubernetes: kubernetes:apps/v1beta2:ControllerRevisionList
kubernetes: kubernetes:apps/v1beta2:DaemonSet
kubernetes: kubernetes:apps/v1beta2:DaemonSetList
kubernetes: kubernetes:apps/v1beta2:Deployment
kubernetes: kubernetes:apps/v1beta2:DeploymentList
kubernetes: kubernetes:apps/v1beta2:ReplicaSet
kubernetes: kubernetes:apps/v1beta2:ReplicaSetList
kubernetes: kubernetes:apps/v1beta2:StatefulSet
kubernetes: kubernetes:apps/v1beta2:StatefulSetList
kubernetes: kubernetes:auditregistration.k8s.io/v1alpha1:AuditSink
kubernetes: kubernetes:auditregistration.k8s.io/v1alpha1:AuditSinkList
kubernetes: kubernetes:authentication.k8s.io/v1:TokenRequest
kubernetes: kubernetes:authentication.k8s.io/v1:TokenReview
kubernetes: kubernetes:authentication.k8s.io/v1beta1:TokenReview
kubernetes: kubernetes:authorization.k8s.io/v1:LocalSubjectAccessReview
kubernetes: kubernetes:authorization.k8s.io/v1:SelfSubjectAccessReview
kubernetes: kubernetes:authorization.k8s.io/v1:SelfSubjectRulesReview
kubernetes: kubernetes:authorization.k8s.io/v1:SubjectAccessReview
kubernetes: kubernetes:authorization.k8s.io/v1beta1:LocalSubjectAccessReview
kubernetes: kubernetes:authorization.k8s.io/v1beta1:SelfSubjectAccessReview
kubernetes: kubernetes:authorization.k8s.io/v1beta1:SelfSubjectRulesReview
kubernetes: kubernetes:authorization.k8s.io/v1beta1:SubjectAccessReview
kubernetes: kubernetes:autoscaling/v1:HorizontalPodAutoscaler
kubernetes: kubernetes:autoscaling/v1:HorizontalPodAutoscalerList
kubernetes: kubernetes:autoscaling/v2beta1:HorizontalPodAutoscaler
kubernetes: kubernetes:autoscaling/v2beta1:HorizontalPodAutoscalerList
kubernetes: kubernetes:autoscaling/v2beta2:HorizontalPodAutoscaler
kubernetes: kubernetes:autoscaling/v2beta2:HorizontalPodAutoscalerList
kubernetes: kubernetes:batch/v1:CronJob
kubernetes: kubernetes:batch/v1:CronJobList
kubernetes: kubernetes:batch/v1:Job
kubernetes: kubernetes:batch/v1:JobList
kubernetes: kubernetes:batch/v1beta1:CronJob
kubernetes: kubernetes:batch/v1beta1:CronJobList
kubernetes: kubernetes:batch/v2alpha1:CronJob
kubernetes: kubernetes:batch/v2alpha1:CronJobList
kubernetes: kubernetes:certificates.k8s.io/v1:CertificateSigningRequest
kubernetes: kubernetes:certificates.k8s.io/v1:CertificateSigningRequestList
kubernetes: kubernetes:certificates.k8s.io/v1beta1:CertificateSigningRequest
kubernetes: kubernetes:certificates.k8s.io/v1beta1:CertificateSigningRequestList
kubernetes: kubernetes:coordination.k8s.io/v1:Lease
kubernetes: kubernetes:coordination.k8s.io/v1:LeaseList
kubernetes: kubernetes:coordination.k8s.io/v1beta1:Lease
kubernetes: kubernetes:coordination.k8s.io/v1beta1:LeaseList
kubernetes: kubernetes:core/v1:Binding
kubernetes: kubernetes:core/v1:ConfigMap
kubernetes: kubernetes:core/v1:ConfigMapList
kubernetes: kubernetes:core/v1:Endpoints
kubernetes: kubernetes:core/v1:EndpointsList
kubernetes: kubernetes:core/v1:EphemeralContainers
kubernetes: kubernetes:core/v1:Event
kubernetes: kubernetes:core/v1:EventList
kubernetes: kubernetes:core/v1:LimitRange
kubernetes: kubernetes:core/v1:LimitRangeList
kubernetes: kubernetes:core/v1:Namespace
kubernetes: kubernetes:core/v1:NamespaceList
kubernetes: kubernetes:core/v1:Node
kubernetes: kubernetes:core/v1:NodeList
kubernetes: kubernetes:core/v1:PersistentVolume
kubernetes: kubernetes:core/v1:PersistentVolumeClaim
kubernetes: kubernetes:core/v1:PersistentVolumeClaimList
kubernetes: kubernetes:core/v1:PersistentVolumeList
kubernetes: kubernetes:core/v1:Pod
kubernetes: kubernetes:core/v1:PodList
kubernetes: kubernetes:core/v1:PodTemplate
kubernetes: kubernetes:core/v1:PodTemplateList
kubernetes: kubernetes:core/v1:ReplicationController
kubernetes: kubernetes:core/v1:ReplicationControllerList
kubernetes: kubernetes:core/v1:ResourceQuota
kubernetes: kubernetes:core/v1:ResourceQuotaList
kubernetes: kubernetes:core/v1:Secret
kubernetes: kubernetes:core/v1:SecretList
kubernetes: kubernetes:core/v1:Service
kubernetes: kubernetes:core/v1:ServiceAccount
kubernetes: kubernetes:core/v1:ServiceAccountList
kubernetes: kubernetes:core/v1:ServiceList
kubernetes: kubernetes:discovery.k8s.io/v1:EndpointSlice
kubernetes: kubernetes:discovery.k8s.io/v1:EndpointSliceList
kubernetes: kubernetes:discovery.k8s.io/v1beta1:EndpointSlice
kubernetes: kubernetes:discovery.k8s.io/v1beta1:EndpointSliceList
kubernetes: kubernetes:events.k8s.io/v1:Event
kubernetes: kubernetes:events.k8s.io/v1:EventList
kubernetes: kubernetes:events.k8s.io/v1beta1:Event
kubernetes: kubernetes:events.k8s.io/v1beta1:EventList
kubernetes: kubernetes:extensions/v1beta1:DaemonSet
kubernetes: kubernetes:extensions/v1beta1:DaemonSetList
kubernetes: kubernetes:extensions/v1beta1:Deployment
kubernetes: kubernetes:extensions/v1beta1:DeploymentList
kubernetes: kubernetes:extensions/v1beta1:Ingress
kubernetes: kubernetes:extensions/v1beta1:IngressList
kubernetes: kubernetes:extensions/v1beta1:NetworkPolicy
kubernetes: kubernetes:extensions/v1beta1:NetworkPolicyList
kubernetes: kubernetes:extensions/v1beta1:PodSecurityPolicy
kubernetes: kubernetes:extensions/v1beta1:PodSecurityPolicyList
kubernetes: kubernetes:extensions/v1beta1:ReplicaSet
kubernetes: kubernetes:extensions/v1beta1:ReplicaSetList
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1alpha1:FlowSchema
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1alpha1:FlowSchemaList
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1alpha1:PriorityLevelConfiguration
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1alpha1:PriorityLevelConfigurationList
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1beta1:FlowSchema
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1beta1:FlowSchemaList
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1beta1:PriorityLevelConfiguration
kubernetes: kubernetes:flowcontrol.apiserver.k8s.io/v1beta1:PriorityLevelConfigurationList
kubernetes: kubernetes:meta/v1:Status
kubernetes: kubernetes:networking.k8s.io/v1:Ingress
kubernetes: kubernetes:networking.k8s.io/v1:IngressClass
kubernetes: kubernetes:networking.k8s.io/v1:IngressClassList
kubernetes: kubernetes:networking.k8s.io/v1:IngressList
kubernetes: kubernetes:networking.k8s.io/v1:NetworkPolicy
kubernetes: kubernetes:networking.k8s.io/v1:NetworkPolicyList
kubernetes: kubernetes:networking.k8s.io/v1beta1:Ingress
kubernetes: kubernetes:networking.k8s.io/v1beta1:IngressClass
kubernetes: kubernetes:networking.k8s.io/v1beta1:IngressClassList
kubernetes: kubernetes:networking.k8s.io/v1beta1:IngressList
kubernetes: kubernetes:node.k8s.io/v1:RuntimeClass
kubernetes: kubernetes:node.k8s.io/v1:RuntimeClassList
kubernetes: kubernetes:node.k8s.io/v1alpha1:RuntimeClass
kubernetes: kubernetes:node.k8s.io/v1alpha1:RuntimeClassList
kubernetes: kubernetes:node.k8s.io/v1beta1:RuntimeClass
kubernetes: kubernetes:node.k8s.io/v1beta1:RuntimeClassList
kubernetes: kubernetes:policy/v1:PodDisruptionBudget
kubernetes: kubernetes:policy/v1:PodDisruptionBudgetList
kubernetes: kubernetes:policy/v1beta1:PodDisruptionBudget
kubernetes: kubernetes:policy/v1beta1:PodDisruptionBudgetList
kubernetes: kubernetes:policy/v1beta1:PodSecurityPolicy
kubernetes: kubernetes:policy/v1beta1:PodSecurityPolicyList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:ClusterRole
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBindingList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:Role
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:RoleBinding
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:RoleBindingList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1:RoleList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:ClusterRole
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:ClusterRoleBinding
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:ClusterRoleBindingList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:ClusterRoleList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:Role
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:RoleBinding
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:RoleBindingList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1alpha1:RoleList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:ClusterRole
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:ClusterRoleBinding
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:ClusterRoleBindingList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:ClusterRoleList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:Role
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:RoleBinding
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:RoleBindingList
kubernetes: kubernetes:rbac.authorization.k8s.io/v1beta1:RoleList
kubernetes: kubernetes:scheduling.k8s.io/v1:PriorityClass
kubernetes: kubernetes:scheduling.k8s.io/v1:PriorityClassList
kubernetes: kubernetes:scheduling.k8s.io/v1alpha1:PriorityClass
kubernetes: kubernetes:scheduling.k8s.io/v1alpha1:PriorityClassList
kubernetes: kubernetes:scheduling.k8s.io/v1beta1:PriorityClass
kubernetes: kubernetes:scheduling.k8s.io/v1beta1:PriorityClassList
kubernetes: kubernetes:settings.k8s.io/v1alpha1:PodPreset
kubernetes: kubernetes:settings.k8s.io/v1alpha1:PodPresetList
kubernetes: kubernetes:storage.k8s.io/v1:CSIDriver
kubernetes: kubernetes:storage.k8s.io/v1:CSIDriverList
kubernetes: kubernetes:storage.k8s.io/v1:CSINode
kubernetes: kubernetes:storage.k8s.io/v1:CSINodeList
kubernetes: kubernetes:storage.k8s.io/v1:StorageClass
kubernetes: kubernetes:storage.k8s.io/v1:StorageClassList
kubernetes: kubernetes:storage.k8s.io/v1:VolumeAttachment
kubernetes: kubernetes:storage.k8s.io/v1:VolumeAttachmentList
kubernetes: kubernetes:storage.k8s.io/v1alpha1:CSIStorageCapacity
kubernetes: kubernetes:storage.k8s.io/v1alpha1:CSIStorageCapacityList
kubernetes: kubernetes:storage.k8s.io/v1alpha1:VolumeAttachment
kubernetes: kubernetes:storage.k8s.io/v1alpha1:VolumeAttachmentList
kubernetes: kubernetes:storage.k8s.io/v1beta1:CSIDriver
kubernetes: kubernetes:storage.k8s.io/v1beta1:CSIDriverList
kubernetes: kubernetes:storage.k8s.io/v1beta1:CSINode
kubernetes: kubernetes:storage.k8s.io/v1beta1:CSINodeList
kubernetes: kubernetes:storage.k8s.io/v1beta1:CSIStorageCapacity
kubernetes: kubernetes:storage.k8s.io/v1beta1:CSIStorageCapacityList
kubernetes: kubernetes:storage.k8s.io/v1beta1:StorageClass
kubernetes: kubernetes:storage.k8s.io/v1beta1:StorageClassList
kubernetes: kubernetes:storage.k8s.io/v1beta1:VolumeAttachment
kubernetes: kubernetes:storage.k8s.io/v1beta1:VolumeAttachmentList
```

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
This change makes sense to me.

It's a bit unfortunate that every language has a unique way to deal with this problem. For example, I'd love to get rid of `Inputs` and `Outputs` namespaces in .NET one day, but it seems unlikely that we want to do this.

> Alternatively, I considered making this a schema flag that the codegenerator could look at, where all the <Resource>Args in a package would be emitted as <Resource>InitArgs

Having a distinct name would be ideal, I guess, but it seems indeed to be too late for that. We probably shipped the existing names in all providers by now...

> But I suspect this is a rare occurrence and if it does ever happen, at that point we can decide whether it's an acceptable change.

Will we be able to detect this automatically?

**Review by lblackstone — APPROVED** [review]

**Comment by justinvp** [comment]
> Will we be able to detect this automatically?

How does the schema breaking change detector work? I assume it's comparing an old vs. new schema? It should be possible to detect such cases when either a new type is added with the same token as an existing resource, or a new resource is added with the same token as an existing type.

**Comment by mikhailshilkov** [comment]
@justinvp That's a good idea, this should be possible indeed.

**Comment by justinvp** [comment]
I opened https://github.com/pulumi/pulumi/issues/7270 to track updating the schema breaking change detector.

**Pull request merged**
