### PR TITLE
[automation/dotnet] Add ReadDiscard OperationType

### LINKED ISSUE #6485: [automation/dotnet] Discarded resources cause errors after destroy
I have two stacks, one of them uses a StackReference to the other. When
destroying the stack which utilizes the StackReference, the StackReference ends up
being discarded, which causes a 'System.Text.Json.JsonException: Invalid operation type: discard'
thrown by the C# Automation API after the destroy has been successfully completed.

<details>
<summary>Stacktrace</summary>

```
Unhandled exception. System.Text.Json.JsonException: Invalid operation type: discard
   at Pulumi.Automation.Serialization.Json.ResourceChangesJsonConverter.ConvertToOperationType(String opType)
   at Pulumi.Automation.Serialization.Json.ResourceChangesJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader& reader, JsonSerializerOptions options)
   at Pulumi.Automation.Serialization.Json.MapToModelJsonConverter`2.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnReadEnumerable(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Pulumi.Automation.WorkspaceStack.GetHistoryAsync(HistoryOptions options, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.GetInfoAsync(CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.DestroyAsync(DestroyOptions options, CancellationToken cancellationToken)
```

</details>

## Expected behavior

Stack is destroyed successfully without errors.

## Current behavior

An error is thrown if the history contains a discarded resource.

## Steps to reproduce

I have managed to reproduce the problem with the following setup.

Create the following directory structure:

```
discard_issue/
|
+---automation/
|   |   automation.csproj
|   |   Program.cs
|   |
+---stack-a/
|   |   Program.cs
|   |   Pulumi.yaml
|   |   stack-a.csproj
|   |
+---stack-b/
|   |   Program.cs
|   |   Pulumi.yaml
|   |   stack-b.csproj
```

Setup projects as shown in the collapsible sections below.

Once the projects have been setup navigate to `automation/` and run the
following:

```bash
# Run update first
dotnet run

# Once the projects have been updated, run destroy
# This triggers the error
dotnet run destroy

# NOTE: Running destroy again works fine, as the resources
# have been destroyed successfully during the previous destroy
dotnet run destroy
```

Setup instructions:

<details>
<summary>automation setup</summary>

`automation/automation.csproj`

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi.Automation" Version="2.23.0-alpha.1614820957" />
  </ItemGroup>

</Project>
```

`automation/Program.cs`

Replace `<ORGANIZATION>` with the proper organization.

```csharp
using System;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using Pulumi.Automation;

namespace discard_issue
{
    class Program
    {
        static async Task Main(string[] args)
        {
            bool destroy = args.Length > 0 && args[0] == "destroy";

            var stackName = "dev";
            var organization = "<ORGANIZATION>";

            if (destroy)
            {
                // Destroy projects in reverse order
                await DestroyProject("stack-b", stackName);
                await DestroyProject("stack-a", stackName);
            }
            else
            {
                await UpdateProject("stack-a", stackName, new Dictionary<string, ConfigValue>()
                {
                });

                await UpdateProject("stack-b", stackName, new Dictionary<string, ConfigValue>()
                {
                    // point the reference to the stack-a created above
                    { "Ref", new ConfigValue($"{organization}/stack-a/{stackName}") }
                });
            }
        }

        static async Task<WorkspaceStack> GetStack(string project, string stackName)
            => await LocalWorkspace.CreateOrSelectStackAsync(new LocalProgramArgs(stackName, GetProjectDirectory(project)));

        static async Task UpdateProject(string project, string stackName, Dictionary<string, ConfigValue> config)
        {
            var stack = await GetStack(project, stackName);

            await stack.SetConfigAsync(config);

            await stack.UpAsync(new UpOptions { OnOutput = Console.WriteLine });
        }

        static async Task DestroyProject(string project, string stackName)
        {
            var stack = await LocalWorkspace.CreateOrSelectStackAsync(
                new LocalProgramArgs(stackName, GetProjectDirectory(project))
            );

            await stack.DestroyAsync(new DestroyOptions { OnOutput = Console.WriteLine });
        }

        static string GetProjectDirectory(string project)
        {
            var source = GetSourceDirectory();

            return Path.GetFullPath(Path.Combine(source, "..", project));

            static string GetSourceDirectory()
            {
                var executingDir = new DirectoryInfo(Assembly.GetExecutingAssembly().Location).Parent.FullName;
                return Path.GetFullPath(Path.Combine(executingDir, "..", "..", ".."));
            }
        }
    }
}
```
</details>

<details>
<summary>stack-a setup</summary>

`stack-a/Program.cs`

stack-a creates an Azure ResourceGroup and outputs its name.

```csharp
using System.Collections.Generic;
using System.Threading.Tasks;

class Program
{
    static Task<int> Main() => Pulumi.Deployment.RunAsync(() =>
    {
        return new Dictionary<string, object?>()
        {
            { "SomeOutput", "SomeOutputValue" }
        };
    });
}
```

`stack-a/Pulumi.yaml`

```yaml
name: stack-a
runtime: dotnet
description: stack-a
```

</details>

<details>
<summary>stack-b setup</summary>

`stack-b/Program.cs`

stack-b utilizes StackReference to the stack-a and simply outputs the same output value.

```csharp
using System.Threading.Tasks;
using System.Collections.Generic;
using Pulumi;

class Program
{
    static Task<int> Main() => Deployment.RunAsync(() =>
    {
        var config = new Config();
        var stackRef = new StackReference(config.Require("Ref"));

        return new Dictionary<string, object?>()
        {
            { "SomeOutput", stackRef.GetOutput("SomeOutput") }
        };
    });
}
```

`stack-b/Pulumi.yaml`

```yaml
name: stack-b
runtime: dotnet
description: stack-b
```

</details>

<details>
<summary>stack-{a,b} both have the same csproj</summary>

`stack-{a,b}/stack-{a,b}.csproj`

Both stack-a and stack-b have similiar csproj file with the following content:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi" Version="2.22.0" />
  </ItemGroup>

</Project>
```

</details>

### PR DESCRIPTION
**Pull request by vipentti**
Added an additional LocalWorkspaceTests to run the testscenario from
#6485. However, this requires setting `PULUMI_TEST_ORG` environment
variable prior to running the tests (for those of us without access to the
`pulumi-test` organization)

Fixes #6485

### CODE REVIEW

**Review by komalali — CHANGES_REQUESTED** [review]
Hey @vipentti thanks for adding this. As you noticed, we're missing some `OperationType`s from our list here. I actually just updated the [nodejs list](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts#L652) which is why you're hitting a conflict now. Could I please ask you to remove the change from `stack.ts` to resolve the conflict and ideally include the additional `OperationType`s to this PR.

**Comment by vipentti** [comment]
Removed the changes to `stack.ts` and added the missing `OperationType`s

**Review by komalali — APPROVED** [review]

**Pull request merged**
