### PR TITLE
Reintroduce type splitting in NodeJS codegen.

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
# Description

This commit reintroduces the changes that were reverted in https://github.com/pulumi/pulumi/pull/11534. This time, we hide the feature behind language-specific config in the schema, and default it to off.

At this time, providers should not enable the feature until https://github.com/pulumi/pulumi/issues/11560 has been addressed.

**Note to reviewers:** Observe that this change does not edit the codegen tests. This demonstrates the these changes do not impact the generated code (because the feature introduced here is off by default). 

Fixes https://github.com/pulumi/pulumi/issues/11557

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by RobbieMcKinstry** [comment]
Marking as draft until CI completes. I expect it to be otherwise ready, but no sense reviewing it before then.

**Comment by RobbieMcKinstry** [comment]
We know why CI is failing, and I made a PR to fix it. In the meantime, we can go ahead with code review.

**Comment by RobbieMcKinstry** [comment]
> Wondering perhaps this feature does not belong on the main branch perhaps until that's addressed?

We can do that instead. My concern is that when we do eventually merge from the branch back into `master`, the PR will be massive. That doesn't inconvenience me (I can keep rebasing as needed) but it might be tough for reviewers.

**Comment by RobbieMcKinstry** [comment]
Converting back into draft for now based on that comment.

**Comment by t0yv0** [comment]
I've used a stacked PR technique in cases like this but it does still get unwieldy.. Really depends on how the team decides to handle these situations 🙏

**Comment by RobbieMcKinstry** [comment]
Yeah, that makes a lot of sense. I'll go with a stacking PRs approach and give that a try.

**Comment by lunaris** [comment]
Superseded by #16193

**Pull request closed without merging**
