### PR TITLE
[cli] Add otel export to convert-trace

### PR DESCRIPTION
**Pull request by pgavlin**
These changes add support for converting a trace file into OpenTelemetry spans and sending them to a collector for further processing.

### CODE REVIEW

**Comment by pgavlin** [comment]
This seems to be most useful when paired with the Jaeger all-in-one image running locally:

```console
$ docker run --rm --name jaeger -p 16686:16686 -p 4317:4317 jaegertracing/all-in-one:1.54
$ OTEL_SERVICE_NAME=pulumi OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4317 pulumi convert-trace --otel --ignore-log-spans [trace file]
converting trace...
dialing collector...
exporting spans for trace [trace ID]...
shutting down...
$ open http://localhost:16686/trace/[trace ID]
```

**Review by PollRobots — APPROVED** [review]
LGTM

**Comment by justinvp** [comment]
Nice! Can you add some tests?

**Comment by pgavlin** [comment]
> Nice! Can you add some tests?

I can, yes. Wasn't aware that we wanted coverage for debug-only commands

**Comment by justinvp** [comment]
We do. Even for experimental/debug commands. If it's shipping in the product, it needs tests.

**Comment by pgavlin** [comment]
> We do. Even for experimental/debug commands. If it's shipping in the product, it needs tests.

Roger that. I’ll come up with a way to test this.

**Pull request merged**
