### PR TITLE
[pcl/binder] Simplify invoke signature logic based on existence of an output-versioned invoke

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

This PR simplifies the binding process of a function invoke when determining whether its return type should be `Output<T>` or `Promise<T>`. The former will be chosen when the function emits an output-versioned invoke during SDK-gen, otherwise the return type is `Promise<T>`

The logic before used a heuristic where the binder only _conservatively_ chooses output-verioned invokes: when the input args are primitive and satisfy a promise-based invoke, then the invoke becomes a promise. This heuristic leads to a panic https://github.com/pulumi/pulumi-terraform-bridge/issues/1159 because parts of typescript program-gen assumed output-versioned invokes (which they should) but the binder chose the promise-version. 

I added a test program which is a minimum repro of the original program in https://github.com/pulumi/pulumi-terraform-bridge/issues/1159 after being converter from TF to PCL

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
Merging has failed because there are some diffs where program-gen is now preferring output-versioned invokes instead of promise-y ones. I will re-gen the test programs and retry the merge

**Comment by Zaid-Ajaj** [comment]
Closing because preferring output-versioned invokes break go program-gen and the original issue was to fix a panic in typecript program-gen

**Pull request closed without merging**
