### PR TITLE
Improve `bors` merge reliability: Windows smoke tests are advisory and run with reduced parallelism

### PR DESCRIPTION
**Pull request by AaronFriel**
The `continue-on-error` flag is set to true whenever the matrix platform contains "windows" for smoke tests. This does mean these jobs will allow failures and proceed, however this should substantially reduce the false negatives due to the behavior of the CI platform. Per the response from GitHub support ticket on my account:

> I've confirmed that our engineering team has an open backlog item focused around "protecting" the provisioning service in cases of resource starvation. I believe this will address your exact concerns so that high resource consumption does not result in an abandoned job.
> 
> In the meantime, there unfortunately is not much capability exposed for affecting priority on the VM. Until improvements are implemented, our team still recommends trying to reduce load on the CPU at the point(s) in the workflow where the job consistently is getting abandoned.

I hope that setting this option, reducing Windows test parallelism, and setting timeouts appropriately will help improve CI reliability. 

Our CI jobs typically complete in 35 minutes, any longer indicates high likelihood that the runner has failed.

### CODE REVIEW

**Comment by Frassle** [comment]
There's literally zero value in running advisory tests in an automatic system unless we're going to write another system to collect and analyse the reasons for failures post-merge.
I don't think we're going to do that so suggestion: remove windows tests from bors completely, keep them for PR smoke tests (because humans will look at those and can hit retry on the individual jobs)

**Comment by AaronFriel** [comment]
PR tests are purely advisory as well, it means there is no constraint on them being merged.

It seems we're back to square one here: running Windows tests on a cron.

**Comment by Frassle** [comment]
> PR tests are purely advisory as well

Yes but a human has a chance to see those. If I'm looking at my PR and see a red windows I _should_ check it out. I'll admit given the high noise due to job failures it's likely people won't be very diligent about it, but there's at least some chance. Nobody but nobody is going to check bors jobs after every merge to see if the Windows test was red or not.

**Comment by AaronFriel** [comment]
I'd rather they run on every merge just so there is data if we need to do a regression. It *may* give us a data point to look at more quickly than a bisect. Odds are that it won't, but I wonder what's the harm in it.

There is a third option, @danielrbradley has been looking at using larger runners in another repo. It'll raise our CI costs above zero, but perhaps it's worth combining this change with one that runs the windows jobs on a larger runner, to see if that's a viable option?

We can then revisit the `staging` jobs in a week and see if a larger runner is worth paying for the rest of the year.

**Comment by danielrbradley** [comment]
@AaronFriel testing the new runner for the next AWS Java release FYI: https://github.com/pulumi/pulumi-aws/pull/2232

**Review by Frassle — APPROVED** [review]
This is all very lame but seems better than doing nothing right now

**Comment by AaronFriel** [comment]
bors merge

**Pull request merged**
