### PR TITLE
deps: Upgrade to pgregory.net/rapid v0.5

### PR DESCRIPTION
**Pull request by abhinav**
The 0.5 release of rapid exposes a generics-based API
instead of `interface{}` and casting everywhere.
This makes for much cleaner usage.

There are a handful of cases where strongly typed generators,
e.g. `Generator[bool]`, need to be turned into `interface{}` (`any`),
which is doable with `AsAny()`.

API changes:
The only non-test changes to the SDK package are in
go/common/resource/testing, which contains testing utiltiies.
Functions that previously returned the old, untyped `Generator`
now return a strongly typed `Generator[T]`.

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12197** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12197" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12197?utm_source=stack-comment).

**Comment by abhinav** [comment]
> Downstream Codegen Tests / CI Codegen / Test aws Downstream (pull_request) Failing after 2m

https://github.com/pulumi/pulumi/issues/12115

**Review by justinvp — APPROVED** [review]

**Comment by abhinav** [comment]
upload-artifact failed. will retry.

**Comment by abhinav** [comment]
bors retry

**Pull request merged**
