### PR TITLE
Fix usage of getters and setters in Lambda callback functions

### LINKED ISSUE #16541: Function Serialization fails for object with getter syntax
### What happened?

I was trying to create a CallbackFunction (love it btw!) and found an error serializing an object that is using the [`get` syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get), see example below.

To be more specific, I want to interact with my database from a lambda using the library https://www.npmjs.com/package/postgres which uses a getter in their [queue.js](https://github.com/porsager/postgres/blob/master/src/queue.js#L8) where I noticed this error.
I can't use a Pulumi postgres provider unfortunately, as the deployment runner has no network access to this database.

I search the issues and looked through [area/callback-functions issues](https://github.com/pulumi/pulumi/labels/area%2Fcallback-functions) but didn't find a ticket for this.

### Example

```ts
import { lambda } from "@pulumi/aws";

new lambda.CallbackFunction("getter-test", {
  callback: async () => {
    const x = {
      get getter() {
        return 42;
      },
    };
    console.log(x);
  },
  policies: []
});
```

Output of `pulumi up`:
```
...

Diagnostics:
  pulumi:pulumi:Stack (censored):
    error: Error serializing 'async()=>{const x={get getter(){retu ...': example.ts(1,205)
    
    'async()=>{const x={get getter(){retu ...': example.ts(1,205): which could not be serialized because
      Unexpected missing variable in closure environment: getter
    
    Function code:
      async()=>{const x={get getter(){return 42}};console.log(x)}
```

### Output of `pulumi about`

```
❯ pulumi about
CLI          
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       amazon
Version  2
Arch     x86_64

This project is written in nodejs: executable='/home/linuxbrew/.linuxbrew/bin/node' version='v22.3.0'

...
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by linkvt**
Fixes #16541 

Hi,

this is an attempt to fix #16541 , feedback is greatly appreciated!

I was not able to test if the result works as expected, I just adjusted the code and manually created a test snapshot from the mocha console output until I thought it looked right.

Could someone tell me...
1. how to actually build the `@pulumi/pulumi` package and how to test the fixes quickly?
2. how to create a snapshot for a new closure test?
3. if there is a quick way to write the TypeScript code in this project, set breakpoints and run tests against it?
   - I plan to investigate the pnpm bundling bug of the `CallbackFunction` but working on this and testing the code is extremely tedious right now as I do not know your secrets (yet 😀)
   - I didn't find these infos in the `CONTRIBUTING.md` and other READMEs
   - I am very familiar with TypeScript and the nodejs tooling, but no clue how everything is stitched together in this repo
   - feel free to send me a Slack message in the Pulumi Community or suggesting another communication channel

Thanks!

fyi @julienp

### CODE REVIEW

**Comment by julienp** [comment]
Thank you for creating the PR! I ran the tests and it all looks good.

> 1. how to actually build the `@pulumi/pulumi` package and how to test the fixes quickly?

```bash
cd sdk/nodejs
make build install
```

This will build and install the nodejs language runtime (not strictly necessary for changes in *.ts files) and the nodejs SDK `@pulumi/pulumi`. The install makes `@pulumi/pulumi` available to yarn link. To test it in a local project, install it there using `yarn link @pulumi/pulumi`.

If you prefer to use a different package manager, you can probably run `pnpm link` or `npm link` from `sdk/nodejs/bin` instead.

> 2. how to create a snapshot for a new closure test?

Unfortunately, I think for closures this is a manual process. Usually our snapshot tests have a way to re-generate snapshots, but not in this case.

> 3. if there is a quick way to write the TypeScript code in this project, set breakpoints and run tests against it?

No, our nodejs test infrastructure is not the most "ergonomic". The tests require the code to first be built (via make build), and are then run with the make targets:

* make unit_tests
* make test_auto # automation API
* make test_integration # includes the closure tests

For the closure tests, you should be able to debug them with `node --inspect-brk 'bin/tests/runtime/closure-integration-tests.js'` (again requires `make build` after each change)

Please don't hesitate to ask if you get stuck on anything related to this, happy to help!

**Review by julienp — APPROVED** [review]

**Comment by julienp** [comment]
@linkvt could you please rebase your changes to the latest `master` of the repo? We reworked some of our CI setup recently, and this PR is blocked due to a bug in our CI jobs that we since fixed.

**Comment by linkvt** [comment]
Thank you very much for the detailed explanation!  

I also rebased the branch to the current master 😀

**Comment by linkvt** [comment]
I was able to confirm that the fix works as expected:
grafik

**Comment by julienp** [comment]
Thank, awesome work!

**Pull request merged**
