### PR TITLE
Clean up use of pkg/errors in sdk/go/auto

### PR DESCRIPTION
**Pull request by Frassle**
Next little bit of removing pkg/errors, remove the few uses in sdk/go/auto.

### CODE REVIEW

**Review by abhinav — APPROVED** [review]

**Comment by abhinav** [comment]
```
Error: go/auto/git.go:117:21: undefined: errors.Wrap
Error: go/auto/git.go:133:22: undefined: errors.Wrap
Error: go/auto/local_workspace.go:94:24: undefined: errors.Wrap
Error: go/auto/local_workspace.go:99:21: undefined: errors.Errorf
Error: go/auto/local_workspace.go:113:17: undefined: errors.Wrapf
```

**Comment by Frassle** [comment]
Huh yeh odd, seems my ide decided to just not check the files on save

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
bors retry

**Comment by Frassle** [comment]
bors retry

**Pull request merged**
