### PR TITLE
Refactor the backend package.

### PR DESCRIPTION
**Pull request by pgavlin**
The primary goal of this refactoring is to simplify the interface
that a Pulumi backend must implement in order to provide better clarity
and separation of concerns. The new interface is centered around the set
of operations necessary for persistence rather than the set of behaviors
required of a stack (e.g. statefile storage vs. running an update or
preview). The former functionality is captured by a new interface,
`backend.Client`, and the latter is captured in the concrete type
`cli.Backend.` Implementers of `backend.Client` should not perform
console I/O--that is the purview of `cli.Backend`.

These changes lay the groundwork for concurrency control, project/org
support, etc. in the filestate backend.

### CODE REVIEW

**Comment by pgavlin** [comment]
Note: it is in no way urgent to land these changes, though I would like to get some eyes on them ASAP. This is a pretty substantial refactoring, so I do expect it to take some time to work through. I'd also like to do some more manual testing with these changes to ensure that e.g. PaC works as expected.

These changes would be code negative if not for the added tests :D

**Comment by pgavlin** [comment]
There are also probably a number of intermediate steps we could take to make these changes less risky (e.g. add the `Client` interface but only consume it internally from the existing backends). I am open to any and all suggestions here.

**Comment by pgavlin** [comment]
(also: this includes the changes from https://github.com/pulumi/pulumi/pull/5887)

**Comment by lblackstone** [comment]
> There are also probably a number of intermediate steps we could take to make these changes less risky (e.g. add the `Client` interface but only consume it internally from the existing backends). I am open to any and all suggestions here.

I think the overall refactoring looks solid, but it would be good to split these changes up more granularly. There's a lot going on in this PR, and it's difficult to understand all of the implications. I like the idea of creating the new `Client` interface and then switching over the current implementations in separate PRs.

Another good first step would be splitting any nonfunctional refactoring (moves, renaming) into a separate PR that lands first.

**Comment by pgavlin** [comment]
> I like the idea of creating the new Client interface and then switching over the current implementations in separate PRs.

Something like this is very doable.

> Another good first step would be splitting any nonfunctional refactoring (moves, renaming) into a separate PR that lands first.

I'm not sure that this applies to much (any?) of this PR. 😬

**Comment by lblackstone** [comment]
> I'm not sure that this applies to much (any?) of this PR. 😬

I wasn't sure if e.g., `pkg/backend/apply.go → pkg/backend/cli/apply.go` could be done separately?

**Comment by pgavlin** [comment]
> I wasn't sure if e.g., pkg/backend/apply.go → pkg/backend/cli/apply.go could be done separately?

Ah, that case might be doable.

**Comment by squaremo** [comment]
@pgavlin `git rebase master` shows quite a few, and large, conflicts. Is it worth salvaging, or having another go? Otherwise, might be good to close it, to take it off the radar.

**Comment by Frassle** [comment]
I've got https://github.com/pulumi/pulumi/issues/2055 assigned to me to refactor these. It's not currently a huge priority but something we keep chipping away at. I'd rather do it in small steps rather than trying to take a large PR like this that tries to rework it all at once.

**Comment by lunaris** [comment]
I'm going to close this given that it's quite old at this point and if we did pick it up, we'd likely tackle it in chunks as mentioned. We can use this as a source/inspiration if we need though!

**Pull request closed without merging**
