### PR TITLE
Prepare release v3.54.0

### PR DESCRIPTION
**Pull request by abhinav**
Preps release v3.54.0.
This has new features, so it's not a minor release.

### CODE REVIEW

**Review by dixler — APPROVED** [review]

**Comment by abhinav** [comment]
We're conducting science:
Will bors wait for the build to be green before attempting the merge?

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
We've decided to let bors validate the merge commit in parallel to the PR.

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
bors merge p=1

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge

**Pull request merged**
