### PR TITLE
Fix invalid cast in analyzer_plugin.go

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Fixes https://github.com/pulumi/pulumi/issues/11140

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by ringods — APPROVED** [review]
LGTM

**Comment by Frassle** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
bors retry

**Comment by Frassle** [comment]
bors retry

**Pull request merged**
