### PR TITLE
Update .version

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
Bump the next release version to v3.50.0 to prepare for release.

### CODE REVIEW

**Review by Zaid-Ajaj — APPROVED** [review]

**Comment by RobbieMcKinstry** [comment]
Thanks for the review! I'm going to grab breakfast/lunch before coming back to cut the release.

**Review by AaronFriel — APPROVED** [review]
lgtm

**Comment by RobbieMcKinstry** [comment]
Dammit, my bad! I accidentally pushed (the follow-on PR) to this branch.

**Pull request merged**
