### PR TITLE
Conformance test for provider pre-release versions

### PR DESCRIPTION
**Pull request by Frassle**
Noticed this issue while doing SDK gen for parameterised providers, but figured it deserved its own conformance test. Check that if a provider has a pre-release semver that the _exact_ version can be reported by the generated SDK. This already just works for NodeJS, but Python needed a fix to write the version to `_utilities.py` rather than trying to unconvert the pypi version from the package.

Also needed to make the conformance test checks for `GetProgramDependencies` even weaker (which is fine, they are just a very basic sanity check) because the provider reports a version of "3.0.0-alpha.1.internal" while the python version is "3.0.0a1+internal".

### CODE REVIEW

**Review by lunaris — APPROVED** [review]
LGTM; do we need the empty `README.md`s or can we remove them/add a line to them that explains what the folder is testing/there for, perhaps?

**Comment by Frassle** [comment]
> do we need the empty README.mds or can we remove them/add a line to them that explains what the folder is testing/there for, perhaps?

I'll do that as a pass over all the conformance providers in another PR.

**Comment by justinvp** [comment]
This looks close to addressing https://github.com/pulumi/pulumi/issues/16212

**Comment by Frassle** [comment]
> This looks close to addressing https://github.com/pulumi/pulumi/issues/16212

Yes, I want to merge this as is asap for param providers with it constrained for just SupportPack SDKs but we should take a look to see if its ok to just add a check to do this for RespectSchemaVersion SDKs as well.

**Pull request merged**
