### PR TITLE
[cli] Abstract out terminal interactions

### PR DESCRIPTION
**Pull request by pgavlin**
Replace direct interaction with the terminal with an abstraction. This
abstraction is tightly constrained to the capabilities needed for the
CLI's display. Using this abstraction allows for straightforward testing
of the interactive renderers.

### CODE REVIEW

**Comment by pgavlin** [comment]
Stacks on top of https://github.com/pulumi/pulumi/pull/11200

**Comment by pgavlin** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors cancel

**Comment by pgavlin** [comment]
bors merge

**Comment by pgavlin** [comment]
bors retry

**Pull request merged**
