### PR TITLE
Freeze release v3.60.0

### PR DESCRIPTION
**Pull request by abhinav**
Freezes release v3.60.0 (#12525)
by starting the draft release for the next minor.

Refs #12520

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12527** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12527" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12527?utm_source=stack-comment).

**Review by RobbieMcKinstry — APPROVED** [review]

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
image

retrying

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
