### PR TITLE
Update gocloud.dev to 0.27.0.

### LINKED ISSUE #7251: Provide a credential-free way of using pulumi with Azure Blob storage as a custom pulumi backend
Right now, we have the following options to authenticate against Azure Blob Storage, when using it as a custom pulumi backend:
- `AZURE_STORAGE_KEY `
- `AZURE_STORAGE_SAS_TOKEN`

Both are credentials that need to be stored/handled securely. 
You can implement this securely by adding Azure Key Vault and store the secret in it. 
Another option is to retrieve one of the secrets by using e.g. Azure CLI/Azure SDK and don't even store it in AKV.

In my opinion all this could be much easier. 
You could provide Azure Cli authentication for BlobStorage (`AZURE_STORAGE_AUTH_VIA_CLI`)
You already provide a similar option for AKV to use AzureCli as an authentication method (`AZURE_KEYVAULT_AUTH_VIA_CLI`).

Pros:
- Consistent way of using a secret provider (AKV) and custom pulumi backend (Azure Storage)
- Easy comprehensible and less code which is more beginner friendly
- Providing out of the box best practices when it comes to authentication against Azure Services
- Better developer experience by just using Pulumi and your language of choice instead of adding addtional tools/libraries inside or outside of pulumi like Azure SDK or Azure Cli. Azure Cli imo should only be used once for authentication. So imo you create a by far better developer experience when you try to avoid media breaks (using different tools/platforms than pulumi). You already went into the right direction with "pulumi automation".

I hope that make sense and does help.

### PR DESCRIPTION
**Pull request by ekini**
# Description

Allow "storage_account" query parameter in the storage backend URL to use Azure CLI authentication. 

Run go mod tidy.

Fixes #7251

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

## Summary

The feature I've been personally waiting for quite long. Currently if you want to use Azure Blob storage as the backend, you have to set the env vars `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY` which is annoying even with utilities like `direnv`. In addition to that, the backend URL set in Pulumi.yaml can't fully define the storage backend as it doesn't have the storage account in it.

This PR fixes the above and makes it use CLI auth as well.

First time contributing to this repo, please point out everything I might have missed.
The doc PRs will come next.

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

**Comment by Frassle** [comment]
Thanks for this!

**Comment by Frassle** [comment]
@AaronFriel looks like issues with the job templates?

**Comment by AaronFriel** [comment]
@Frassle this usually indicates we need to run `make tidy`, I tried to make the error more apparent but it's buried in the logs:


```
  Traceback (most recent call last):
    File "./scripts/get-job-matrix.py", line 611, in <module>
      main()
    File "./scripts/get-job-matrix.py", line 608, in main
      args.func(args)
    File "./scripts/get-job-matrix.py", line 447, in generate_matrix
      matrix = get_matrix(
    File "./scripts/get-job-matrix.py", line 390, in get_matrix
      pkg_tests = run_list_tests(item.package_dir, tags)
    File "./scripts/get-job-matrix.py", line 167, in run_list_tests
      raise Exception(message) from err
  Exception: Failed to list tests in package dir 'tests/integration', usually this implies a Go compilation error. Check that `make lint` succeeds.
```

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
bors retry

**Pull request merged**
