### PR TITLE
Add pulumi-language-nodejs to LINT_GOLANG_PKGS

### PR DESCRIPTION
**Pull request by Frassle**

### CODE REVIEW

**Review by abhinav — APPROVED** [review]

**Comment by Frassle** [comment]
bors merge

**Review by RobbieMcKinstry — APPROVED** [review]

**Comment by RobbieMcKinstry** [comment]
bors retry

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
bors merge

**Pull request merged**
