### PR TITLE
ci: Freeze v3.43.0 for release

### PR DESCRIPTION
**Pull request by AaronFriel**
This will freeze the draft release v3.43.0 so that we may release it without pausing any work in progress.

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]

**Comment by AaronFriel** [comment]
bors merge p=-1

**Comment by AaronFriel** [comment]
bors merge p=-1

**Comment by AaronFriel** [comment]
bors cancel

**Comment by AaronFriel** [comment]
bors merge

**Pull request merged**
