### PR TITLE
feat: enable imports from nodejs provider resources

### PR DESCRIPTION
**Pull request by bfraterman-tkhsecurity**
# Description
I was writing a typescript resource provider, but got errors that the the plugin didn't support imports, while the `read` method was implemented on the provider.
This PR also sets the `Inputs` on the `ReadResponse`, so imports will be supported.

Fixes # (issue)
Could not find existing issue

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [ ] I have run `make lint` to verify my code passes the lint check
- [ ] I have formatted my code using `gofumpt`
(None of the above, since the change is in js code)

- [ ] I have added tests that prove my fix is effective or that my feature works
There are no existing tests for the `server.ts` file. If really required for merging I could maybe take a look at a test for this use-case.

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Comment by Frassle** [comment]
> but got errors that the the plugin didn't support imports, 

What errors exactly? "inputs" are not "props" and are in general not required for the engine to do an import. Which also makes this change a bit suspicious, because the props returned by "read" _might not_ be the right thing to also tell the engine are inputs.

**Comment by bfraterman-tkhsecurity** [comment]
I got the error originating from here: https://github.com/pulumi/pulumi/blob/master/pkg/resource/deploy/step.go#L1037

I'm very unfamiliar with the pulumi codebase. Do you think it's maybe better to change the `ReadResult` interface in the node SDK and expand it with an `inputs` property?

Do we have an example (from maybe another SDK) what that should look like?

**Comment by bfraterman-tkhsecurity** [comment]
> Yeh that's probably more correct. It's what the C# SDK does (https://github.com/pulumi/pulumi-dotnet/blob/main/sdk/Pulumi/Provider/Provider.cs#L217-L222) and the Go SDK (https://github.com/pulumi/pulumi-go-provider/blob/main/infer/resource.go#L113-L114)

Fixed that, please let me know if you have any more concerns.

**Comment by Frassle** [comment]
> Not sure if you would call this feature 'user-facing' since it's about plugin development.

Provider developers are users too :) Add a changelog for this and we can get it merged.

**Review by Frassle — APPROVED** [review]

**Review by Frassle — APPROVED** [review]

**Comment by bfraterman-tkhsecurity** [comment]
@Frassle Any clue what's going on with the build pipeline? Doesn't seem likely that it's caused by these changes?

**Comment by Frassle** [comment]
CI pipeline is known to be flakey at the moment, I can just keep retrying this till it goes through.

**Pull request merged**
