### PR TITLE
Fix incorrect import for non-pulumi owned package on convert

### PR DESCRIPTION
**Pull request by aq17**
# Description

Fixes `pulumi/yaml` [335](https://github.com/pulumi/pulumi-yaml/issues/335)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by aq17** [comment]
Similar fix as https://github.com/pulumi/pulumi/pull/10485/files but for modules of the form `mod/sub`

**Review by iwahbe — APPROVED** [review]
LGTM. It would be great to have a test for these.

**Comment by aq17** [comment]
bors merge

**Comment by aq17** [comment]
bors merge

**Comment by aq17** [comment]
bors merge

**Review by AaronFriel — APPROVED** [review]
LGTM, though I'm wondering why our handling of slashes in the module section is so inconsistent.

**Comment by aq17** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors cancel

**Comment by aq17** [comment]
bors merge

**Pull request merged**
