### PR TITLE
Mark external modules as forign

### LINKED ISSUE #8070: Go program generation: fails to namespace some imports
This was found compiling our program generation tests. We have structs labeled as `GetAmiArgs` and `GetAmiFilter`. These should be `aws.GetAmitArgs` and `aws.GetAmiFilter`. 
## Steps to reproduce

1. `cd pkg/internal/test/testdata/aws-webserver-pp`
2. `go build`

Expected: A clean compile.
Actual:
```
# main
./aws-webserver.go:30:15: undefined: GetAmiArgs
```
After I manually fixed this line, I got: 
```
# main
./aws-webserver.go:30:15: undefined: GetAmiFilter
```

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #8070

Progress on https://github.com/pulumi/pulumi/issues/11427

### CODE REVIEW

**Review by aq17 — APPROVED** [review]

**Comment by justinvp** [comment]
bors cancel

**Comment by justinvp** [comment]
Canceled temporarily to get #11436 merged for the release.

**Comment by justinvp** [comment]
bors merge

**Pull request merged**
