### PR TITLE
Auto download converter plugins

### PR DESCRIPTION
**Pull request by Frassle**
Shares much of the same logic as auto-install of provider plugins during updates.

### CODE REVIEW

**Review by justinvp — APPROVED** [review]
LGTM

**Comment by Frassle** [comment]
bors merge

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
Sorry, I was in the middle of reviewing this

**Review by abhinav — APPROVED** [review]
The core logic was quite straightforward, but the effort to get into reviewing this change was higher the first few times I tried it because it wasn't obvious how much of the moved code was changed—GitHub doesn't really make it obvious.

Doing the move in a separate commit makes it much easier to review the new logic.
I've teased the commits apart and pushed to this branch—the topmost commit that adds the logic for this PR is quite straightforward after that change.

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
