### PR TITLE
fix(host/go): Download external plugins even if they're not imported

### LINKED ISSUE #13301: [go] http plugins fail to install for go programs when go dependencies are not present
### What happened?

When go deps are not present on a system (eg- a clean CI environment or after `go clean -cache -modcache` has been ran), go programs fail to install plugins that use HTTP for `pluginDownloadURL`.

Without go deps present, Pulumi fails to determine the appropriate plugin version to use for a given go package and attempts to retrieve the latest version of a plugin. This behavior is not currently supported for HTTP plugin sources, hence, the error:
```
newUpdateSource(): failed to install missing plugins: could not get latest version for plugin my-plugin: GetLatestVersion is not supported for plugins from http sources
```

`preview` and `up` both install go deps prior to beginning their execution, however, refresh and plugin install do not. This means that a refresh in this scenario will incur the above error message.

EDIT- `pulumi plugin install` also fails to install HTTP sourced plugins in this scenario.

### Expected Behavior

Plugin versions should be identified and properly installed regardless of which command is executed.

### Steps to reproduce

Using a plugin with HTTP source for `pluginDownloadURL`:
- add plugin to a pulumi go program
- `go clean -cache -modcache`
- `pulumi plugin rm --all --yes`
- `pulumi plugin install`

### Output of `pulumi about`

CLI
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v5  5.25.0
github.com/pulumi/pulumi/sdk/v3      3.73.0

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by abhinav**
We previously changed how the Go language host retrieves information
about a Go module:

    before: go list -m -json -mod=mod all
    after:  go list -m -json $importPath1 $importPath1

This change made it possible for us to supprot running in vendored mode
which allowed for use of private plugins that are not go-get-able.

This uncovered a corner case in the `go` command's behavior
when running in module mode:

If a package is listed in the go.mod
but it's not imported by the current module,
`go list -m -json $importPath` will not list its Dir in the output
even if it's present in the module cache.
For example, given a go.mod file that declares a dependency
but code that doesn't import it, as of Go 1.20.5,

    export GOMODCACHE=$(mktemp -d)
    go mod download -json
    go list -m -json $importPath

The output of `go mod download` will include information
about the dependency and the `Dir` where it was downloaded,
but `go list -m` will not.

Unfortunately, we can't just use `go mod download`
because that breaks vendoring:
vendored dependencies cannot always be redownloaded.

To resolve this issue,
we switch to a two-pass variant to gather this information:

- Run `go list -m` to get whatever information we can locally.
  This will be sufficient for the majority of use cases.
- For the handful of cases where the dependency isn't imported,
  we'll use `go mod download -json` to download them on-demand
  and get their location from that instead.

The `go mod download` step will take place only if we're in module mode.
In vendor mode, we'll work with what we have.

Resolves #13301

### CODE REVIEW

**Comment by abhinav** [comment]
Repro: https://github.com/pulumi/pulumi/actions/runs/5525559114/jobs/10079407337?pr=13455

```
=== FAIL: integration TestAutomation_externalPluginDownload_issue13301 (3.04s)
    environment.go:97: Created new test environment:  /tmp/test-env2781205917
    integration_go_test.go:964: Running command pulumi login --cloud-url file:///tmp/test-env2781205917
    integration_go_test.go:992: Running command pulumi plugin install
    integration_go_test.go:1024: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/integration/integration_go_test.go:1024
        	Error:      	Received unexpected error:
        	            	failed to run preview: exit status 255
        	            	code: 255
        	            	stdout: Previewing update (foo):
        	            	
        	            	 +  pulumi:pulumi:Stack issue-13301-foo create 
        	            	    pulumi:providers:hcp hcp  error: could not find latest version for provider hcp: GetLatestVersion is not supported for plugins from http sources
        	            	 +  pulumi:pulumi:Stack issue-13301-foo create 
        	            	    pulumi:providers:hcp hcp  1 error
        	            	
        	            	Diagnostics:
        	            	  pulumi:providers:hcp (hcp):
        	            	    error: could not find latest version for provider hcp: GetLatestVersion is not supported for plugins from http sources
        	            	
        	            	
        	            	
        	            	stderr: 
        	Test:       	TestAutomation_externalPluginDownload_issue13301
    integration_go_test.go:985: grpc debug log:
        {"method":"/pulumirpc.LanguageRuntime/GetPluginInfo","request":{},"response":{},"metadata":{"kind":"language","mode":"client","runtime":"go"}}
        {"method":"/pulumirpc.LanguageRuntime/GetRequiredPlugins","request":{"project":"issue-13301","pwd":"/tmp/test-env2781205917","program":"."},"response":{},"metadata":{"kind":"language","mode":"client","runtime":"go"}}
        {"method":"/pulumirpc.LanguageRuntime/GetRequiredPlugins","request":{"project":"issue-13301","pwd":"/tmp/test-env2781205917","program":"."},"response":{},"metadata":{"address":"127.0.0.1:[355](https://github.com/pulumi/pulumi/actions/runs/5525559114/jobs/10079407337?pr=13455#step:34:356)33","kind":"language","mode":"client"}}
        {"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"resourceReferences"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
        {"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"outputValues"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
        {"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"deletedWith"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
        {"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"aliasSpecs"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
        {"method":"/pulumirpc.ResourceMonitor/RegisterResource","request":{"type":"pulumi:pulumi:Stack","name":"issue-13301-foo","object":{},"acceptSecrets":true,"customTimeouts":{},"acceptResources":true},"response":{"urn":"urn:pulumi:foo::issue-13301::pulumi:pulumi:Stack::issue-13301-foo","object":{}},"metadata":{"mode":"server"}}
```

**Comment by abhinav** [comment]
Note that this fix depends on #13447.
Thanks to @Frassle for fixing.

**Review by Frassle — APPROVED** [review]
LGTM

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
