### PR TITLE
Add support for converting examples into serialized PCL form 

### PR DESCRIPTION
**Pull request by andrzejressel**
Continuation of #11754
Relates to #11882

This PR allows adding serialized PCL files into description just like any other language does. It allows developers of custom languages integrations to take this serialized form, deserialize it and generate example in own language.

terraform bridge PR: https://github.com/pulumi/pulumi-terraform-bridge/pull/2381

### CODE REVIEW

**Comment by andrzejressel** [comment]
`Config validation error in build.os. Value build not found.` - I don't understand what it is - I haven't changed anything docs related

**Comment by andrzejressel** [comment]
I've added 2 different forms: JSON for testing and Protobuf for production usage. There are some tests that does not pass, there is also no support for comments - but they will be added in subsequent PRs

**Comment by andrzejressel** [comment]
I don't know - the whole point is that custom language generators does not have to parse anything - that they get code already structured in some standardized format.

I think at this point parsing yaml would be easier pcl.

**Comment by Frassle** [comment]
> I don't know - the whole point is that custom language generators does not have to parse anything - that they get code already structured in some standardized format.

Yes, I get that. It's why I first suggested some sort of protobuf encoding for this, but I think that encoding needs to be carefully thought through to be a rich semantic object, not just a simple translation of the syntax. Otherwise you've solved parsing, but still have the problems of type checking and name binding to solve which are even harder.

> I think at this point parsing yaml would be easier than pcl.

YAML will give similar issues in terms of difficulty to type check and bind. But we have considered using yaml in the examples so we can use `pulumi convert` to gen that one yaml example out for each language, rather then the schema needing every language in it. Our YAML variant isn't as expressive as PCL though, so a lot of examples are only really expressible with PCL. Which led to our current thinking that we might want to put PCL (as text for now) into the schema to do these example conversions.

So the direction here is right, just the details are complicated.

**Pull request closed without merging**
