### PR TITLE
Fix version number in typerefs when marshalling schemas

### PR DESCRIPTION
**Pull request by Frassle**
# Description

Fixes https://github.com/pulumi/pulumi/issues/13000

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by abhinav — COMMENTED** [review]
Is this something we can add a unit test for?

**Comment by RobbieMcKinstry** [comment]
Do we need a guard in case the string already starts with `v`? i.e. check if the semver string is normalized to include the `v`, and if not, add the `v` ourselves. Or is that over-complicating things?

**Review by RobbieMcKinstry — COMMENTED** [review]
Do we need a guard in case the string already starts with v? i.e. check if the semver string is normalized to include the v, and if not, add the v ourselves. Or is that over-complicating things?

**Comment by Frassle** [comment]
> Do we need a guard in case the string already starts with v? i.e. check if the semver string is normalized to include the v, and if not, add the v ourselves. Or is that over-complicating things?

We don't. `container.Version` is a `semver.Version` which doesn't include a 'v' in it's `String()` result.

> Is this something we can add a unit test for?

I'll have a look, although stuff like this should get covered by matrix testing as that comes online anyway.

**Review by abhinav — APPROVED** [review]

**Comment by Frassle** [comment]
bors merge

**Comment by mikhailshilkov** [comment]
@Frassle I want to ask you to provide descriptions for your PRs. The fact that it fixes #13000 isn't enough for me to get the context. I want to read

- Description of a problem
- What happened why the problem occurred
- What the fix is
- How we test it

Thank you!

**Pull request merged**
