### PR TITLE
Fix links to outputs docs

### LINKED ISSUE #13461: Output[T] error message includes invalid URL
### What happened?

I did the bad thing with an output and a string, and got the now infamous error message.

However, the url is incorrect

### Expected Behavior

The url should be correct

### Steps to reproduce

```
Calling __str__ on an Output[T] is not supported.\n\nTo get the value of an Output[T] as an Output[str] consider:\n1. o.apply(lambda v: f\"prefix{v}suffix\")\n\nSee https://pulumi.io/help/outputs for more details.\nThis function may throw in a future version of Pulumi.
```

https://pulumi.io/help/outputs 

404s

### Output of `pulumi about`

not required

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by cnunciato**
Fixes some broken links pointing to the Inputs & Outputs docs.

Fixes #13461.

### CODE REVIEW

**Review by justinvp — APPROVED** [review]
LGTM

We'll need similar changes in the .NET and Java repos:
- [pulumi-dotnet](https://github.com/pulumi/pulumi-dotnet/blob/52d0a14fe316b2a9a3e3bc6cb6117721980a5ff7/sdk/Pulumi/Core/Output.cs#L660)
- [pulumi-java](https://github.com/pulumi/pulumi-java/blob/540be8a6d19f9316a635d76f69f8118ce13769ac/sdk/java/pulumi/src/main/java/com/pulumi/core/internal/OutputInternal.java#L149)

**Comment by Frassle** [comment]
dotnet's done: https://github.com/pulumi/pulumi-dotnet/pull/158

**Comment by Frassle** [comment]
Java needs review: https://github.com/pulumi/pulumi-java/pull/1154

**Comment by cnunciato** [comment]
Thank you both!

**Comment by cnunciato** [comment]
bors merge

**Pull request merged**
