### PR TITLE
asset streaming 13807

### LINKED ISSUE #13807: (Node.JS) pulumi.asset.RemoteAsset SIGKILL/OOM
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

(Opened on behalf of a customer)

When trying to use `pulumi.asset.RemoteAsset` with a file that is larger than available membory (RAM), one experiences SIGKILL and OOM errors/crashes. This issue can be reproduced with any file that is larger than the available memory (RAM). 

It appears that the file https://github.com/pulumi/pulumi/blob/master/sdk/go/common/resource/asset.go#L443 is calling `ReadAll` against the URL, causing the whole thing to be loaded into memory. 
This could be improved by utilizing streaming.

Below is some Node.JS reproducible code.
You will need to update `bigFileURL`.

```

const bigFileURL = `[https://link.to.many.gigabyte.file/`](https://link.to.many.gigabyte.file/);

const bucket = new aws.s3.BucketV2(`big-file-s3-bucket`, {

                bucketPrefix: `big-file-s3-bucket`

});

const bigFileInS3 = new aws.s3.BucketObjectv2(`big-file-in-s3`, {

    key: 'bigFile',

    bucket: [bucket.id](http://bucket.id/),

    source: new pulumi.asset.RemoteAsset(bigFileURL)

}, {

    ignoreChanges: ['source'],

    customTimeouts: {

        create: '120m',

        delete: '120m',

        update: '120m'

    },

    parent: bucket

});

```

 
Worth noting, the same code works just fine if the file is local, and you use `pulumi.asset.FileAsset` with a path to that local file.

### Affected area/feature

pulumi.asset

### PR DESCRIPTION
**Pull request by taytzehao**
# Description

Remote asset now streams data from response
Fixes #13807

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`
- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

### CODE REVIEW

**Comment by taytzehao** [comment]
@MitchellGerdisch

**Review by Frassle — COMMENTED** [review]
ReadAll already streams internally, why would we do our own fixed stream of 1024 bytes at a time?

**Comment by taytzehao** [comment]
@Frassle , thanks for pointing that out. this is pretty incorrect. I am noew thinking to write the data into a file and make it return a file blob. This would work in more situations and overcome the memory limitation. However, this would decrease performance for smaller files. I think it is worth it

Or do we wnat something with a more complex behaviour

**Comment by taytzehao** [comment]
@Frassle

**Comment by lunaris** [comment]
So I've spent a bit of time looking at this, and it seems fairly tricky to fix it. There are a couple of options:

### Stream directly from the HTTP response
We can do something like:
```go
func NewHTTPBlob(resp *http.Response) (*Blob, error) {
    return &Blob{
        rd: resp.Body,
        sz: resp.ContentLength,
    }, nil
}
```
Unfortunately, `resp.ContentLength` will typically always be `-1`, since Go's HTTP library will erase the header value when dealing with compressed HTTP responses. This is basically all responses, and even if we disabled it, the use case we are trying to fix (large files) is one where presumably we'd suffer the most. It's logical to ask "do we really need the size?" and I've explored that -- the gotcha currently is its use when writing tarball assets. Tarballs require sizes to be written before data, so we need the size up-front. The only (very cheeky) solution I can see here is writing a dummy size and then seeking back to write the real size when we've completed streaming, but this would require (I think) forking `archive/tar` or similar and demanding an `io.WriteSeeker` instead of a plain `io.Writer`. Even then, this would be an opportunistic optimisation I think since `io.Writer` forms part of a public contract, so we'd have a case where we could still fallback to the OOM behaviour.
### Write chunks to the filesystem
This is as you suggest. Here, we fall afoul of trying to find a part of the filesystem that is not _also_ mounted as a RAMdisk (e.g. `tmpfs` in Linux/macOS). This is fiddly since by default, if we request some `MkTemp`-directory, there is a good chance this is exactly where it'll end up. Thus, we end up writing the file to RAM in any case and hitting the same OOM issues.

Given how few people this appears to be affecting (I could be wrong on this) and the fact that this PR has been quiet a while, I'm minded to close this PR now since I don't think it's an approach we can integrate and fall back to monitoring the original issue.

**Pull request closed without merging**
