### PR TITLE
Update pulumi SDK version in go.mod in integration tests

### LINKED ISSUE #6807: Clean up go integration testing files
As part of the 3.0 beta program, we had to add go.mods with references to a single go commit in the testing/integration folder - we need to clean these up

### PR DESCRIPTION
**Pull request by mikhailshilkov**
# Description

Fixes #6807

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
Do these tests run in a PR?

**Comment by Frassle** [comment]
> Do these tests run in a PR?

I don't think so.

**Comment by iwahbe** [comment]
Instead of pinning a modern version of pulumi, which we will have to manually bump later, should we add a `replace` and have integration tests always run against the current SDK?

**Comment by Frassle** [comment]
> Instead of pinning a modern version of pulumi, which we will have to manually bump later, should we add a replace and have integration tests always run against the current SDK?

Yes

**Comment by mikhailshilkov** [comment]
Should I close this PR then? Do you want to adjust the original issue?

**Comment by iwahbe** [comment]
> As part of the 3.0 beta program, we had to add go.mods with references to a single go commit in the testing/integration folder - we need to clean these up

The original issue just says "cleanup", so I think the `replace` statements qualify. You can add the `replace` statements, or you can close the PR and I can take it.

**Comment by mikhailshilkov** [comment]
I won't have time to do that today, so I'll close it.

**Pull request closed without merging**
