### PR TITLE
Support `--clear-pending-creates` for `refresh` command in Go Automation API.

### PR DESCRIPTION
**Pull request by mcblair**
Further fulfills #11336.

### CODE REVIEW

**Comment by mcblair** [comment]
👋 @tgummerer @Frassle I appreciate your review!

**Review by justinvp — COMMENTED** [review]
Thanks, @mcblair! LGTM aside from needing a changelog entry (run `make changelog`). Mind adding that?

**Comment by mcblair** [comment]
> Thanks, @mcblair! LGTM aside from needing a changelog entry (run `make changelog`). Mind adding that?

Done! Thank you.

**Review by justinvp — APPROVED** [review]

**Pull request merged**
