### PR TITLE
Shortcut resource packages scan

### PR DESCRIPTION
**Pull request by t0yv0**
It seems reasonable that if an assembly does not reference Pulumi.dll that defines Resource type, then it cannot contain types that inherit from Resource, and therefore we can skip GetTypes() for that assembly. This saves some System.Type traversals (4000 -> 200 in our test). More importantly it seems to help with an issue @orionstudt had in their PR where this code blows up on trying to GetType() from Castle dynamic assembly.

### CODE REVIEW

**Review by mikhailshilkov — APPROVED** [review]
LGTM overall. Do we have enough coverage to be sure we don't miss some edge cases?

**Comment by t0yv0** [comment]
I'm wondering about that also. The happy path is definitely covered. I failed to get a big picture though, how do users use this thing?

**Comment by orionstudt** [comment]
I believe the `ResourcePackages` class is part of bringing this epic to .NET: https://github.com/pulumi/pulumi/issues/2430

**Comment by t0yv0** [comment]
Something funky with Mac OS tests timing out. I'm going to rerun them. There were some GitHub Actions availability issues yesterday.

**Review by justinvp — APPROVED** [review]

**Pull request merged**
