### PR TITLE
Fixes 6608: unusable venv after template copy, python not executable

### PR DESCRIPTION
**Pull request by t0yv0**
Toward fixing #6608.

To reproduce 6608:

```
#!/bin/sh

mkdir template
pushd template
pulumi new --yes aws-python --name "template-6608-1"
popd

mkdir user-project
pushd user-project
pulumi new --yes ../template --name "user-project-6608-1"
popd

```

What happens is that the second `pulumi new` copies `venv` but forgets to mark files like `python` executable. It also ignores any symlink structure, if any... Symlinks become regular files.

*Option 1*: as coded in the PR, propagate more permission bits from source to dest, so executable files remain executable after template expansion, but everything is at least 0600.

*Option 2*: drop 0600, use exact permissions from source file. This did NOT fix the bug when using os.Stat - because of symlink handling.. begs the question of what should template expansion do with symlinks anyway? Copying symlinks as symlinks its not possible when the contents are being modified by the logic in here.

*Option 3*: skip virtual environment from the template copying process. Where could we do this cleanly? If we can do it cleanly it might be the best as then we will let Python manage virtual environment folder including deciding which one is a symlink and which one is not; we do not mess with that. It seems that upon copying the template, Pulumi up does re-initialization of the virtual env (if configured to manage it in the yaml). So that'd be ideal perhaps.

### CODE REVIEW

**Comment by justinvp** [comment]
Thanks, @t0yv0! I want to take a look over this before merging. Hopefully I’ll be able to get to it tomorrow, but if not, Monday.

**Comment by t0yv0** [comment]
Oh right - the user has found a workaround so there is no rush on this one.

**Comment by justinvp** [comment]
Our stance on this has generally been that `venv` should not be committed in the template repo. If your template has specific dependencies, include them in `requirements.txt` and Pulumi will automatically create the virtual environment and install the `requirements.txt` dependencies into it.

> _Option 1_: as coded in the PR, propagate more permission bits from source to dest, so executable files remain executable after template expansion, but everything is at least 0600.

That said, this still seems like a reasonable change to make

**Comment by t0yv0** [comment]
Can still repro on 3.x. Accepting the fix I think is better than leaving as-is, although there's better way to fix it.

**Comment by t0yv0** [comment]
> Our stance on this has generally been that venv should not be committed in the template repo. If your template has specific dependencies, include them in requirements.txt and Pulumi will automatically create the virtual environment and install the requirements.txt dependencies into it.

Hm that sounds good but should we then teach Pulumi CLI to exclude venv from consideration when it scans template folders and venv is accidentally present? I think this happens when an existing project is used as a template before the user commits it cleanly to a template repo.

**Review by lblackstone — APPROVED** [review]
This seems like a reasonable improvement to me.

**Pull request merged**
