### PR TITLE
Display text-based diff if yaml/json diff is semantically equal

### LINKED ISSUE #11799: Diff display for string values with YAML contents displays empty objects incorrectly
This program:

```go
package main

import (
	p "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	p.Run(func(ctx *p.Context) error {
		ctx.Export("foo", p.String("foo:\n  bar: {}\n  baz: {}\n"))
		return nil
	})
}
```

Renders this on `pulumi up`:

```
Updating (dev)

View Live: https://app.pulumi.com/lukehoban/goawstest/dev/updates/1

     Type                 Name           Status              
 +   pulumi:pulumi:Stack  goawstest-dev  created (0.00s)     


Outputs:
    foo: (yaml) {
        foo: {
        }
    }


Resources:
    + 1 created

Duration: 2s
```

Note that it fails to render `bar` and `baz`.

If a diff is introduced - like adding a comment to the YAML string - the update diff is also wrong:

```go
package main

import (
	p "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	p.Run(func(ctx *p.Context) error {
		ctx.Export("foo", p.String("#foo\nfoo:\n  bar: {}\n  baz: {}\n"))
		return nil
	})
}
```

```
Previewing update (dev)

View Live: https://app.pulumi.com/lukehoban/goawstest/dev/previews/1416a1a4-251b-455f-b794-e597e3351975

     Type                 Name           Plan     
     pulumi:pulumi:Stack  goawstest-dev           


Outputs:
  ~ foo: (yaml) {
        foo: {
        }
    }

Resources:
    1 unchanged
```

Note that:
1. `bar` and `baz` are still missing
2. The comment that was introduced is not rendered in the diff
3. Pulumi shows a `~` indicating a diff, but not diff in the object

### PR DESCRIPTION
**Pull request by aq17**
Fixes #11799 

https://github.com/pulumi/pulumi/pull/9380 and https://github.com/pulumi/pulumi/pull/9484 introduced changes that render JSON/YAML parsable strings as objects in diffs – therefore, examples such as`"foo:\n  bar: {}\n  baz: {}\n"` and `"#foo\nfoo:\n  bar: {}\n  baz: {}\n"` are recognized as equal.

This change causes the display to fall back to showing the text-based diff if the JSON/YAML rendering does not indicate any diff.
It also prints all object keys even if the value is empty, i.e. `bar: {}` or `bar: ""` will be printed instead of `bar` being omitted.

### CODE REVIEW

**Review by lukehoban — COMMENTED** [review]
Can we add test coverage for this?

**Review by iwahbe — APPROVED** [review]
LGTM

Nit: Let's try to get the correct changelog before we merge.

**Comment by aq17** [comment]
bors retry

**Comment by iwahbe** [comment]
bors retry

**Comment by aq17** [comment]
bors retry

**Pull request merged**
