### PR TITLE
Fix enum rendering issue

### PR DESCRIPTION
**Pull request by sean1588**
Fixes: https://github.com/pulumi/registry/issues/3724
Fixes: https://github.com/pulumi/registry/issues/2966

This PR is to resolve the enum rendering issue. The enums were not being rendered on the page at all due to a misconfigured language choosable (i.e. `<pulumi-choosable>`) that wraps the enum section.  I found out this had to do with the lang property being set as `nodejs` when instead the choosable expects `javascript` or `typescript` as the valid values. I then followed the pattern of what we seem to be doing for the other pulumi-choosables which have this issue, which is to  have an if statement that sets it to `javascript,typescript` if `nodejs` is given.

This is how the rendering looks now. I have not adjusted any layouts of the template or anything along those lines, only fixed the choosable. I am wondering if this is actually what was intended for these, as we have a display name in the left column that is ~useless IMO and the right column has the value. I am assuming this was done to match the formatting of the other nested types that are displayed since these enums are treated as such. Though I don't think it is optimal for what we are trying to present given that we do not have descriptions for any of the individual enum values and what they represent.

Should we consider doing something like having a separate enum section that is more purpose built for the data we can display where we just have the enum type in the left column, followed by the valid enum values in the right column. For example:

| Instance Type | a1.2xlarge, a1.4xlarge , a1.large.... |

Should we consider moving to something like this or continue following the current pattern we have? Thoughts welcome!

Also, we can consider shipping this as it is as it is still an improvement over what we have now and file a follow up issue to re-assess the way this is presented.

This is the current render that this PR fix will produce:

Screen Shot 2024-02-09 at 8 35 21 AM

### CODE REVIEW

**Review by guineveresaenger — APPROVED** [review]
I think we can ship this as-is but I really like your suggestion for improvement.

**Review by cnunciato — APPROVED** [review]
Looks good! I think you'll just need to regenerate the baselines for the tests -- [here's how to do that](https://github.com/pulumi/pulumi/tree/master/pkg/codegen/docs#modifying-templates-and-updating-tests).

**Comment by t0yv0** [comment]
Something in the downstream checks hits a nilptr I might have recently introduced in upgrade-provider, checking up on this.

**Comment by t0yv0** [comment]
e.g. here https://github.com/pulumi/pulumi-azuread/actions/runs/7849687103/job/21423555290#step:4:9

**Comment by t0yv0** [comment]
Fix in https://github.com/pulumi/upgrade-provider/pull/250

**Comment by sean1588** [comment]
thanks so much @t0yv0 !!

**Review by iwahbe — APPROVED** [review]
LGTM

**Pull request merged**
