### PR TITLE
Avoid triple-building projects in the solution

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Another experiment in speeding up builds. The idea is to add a switch that makes `test_all` target avoid installing, since CI runs `install_all` before `test_all`, to avoid triple-building-and-installing.

Before:

```
$ make --debug=b TEST_ALL_DEPS= install_all -n | grep 'bdist_wheel'
cd ./env/src && pipenv run python setup.py build bdist_wheel --universal

$ make --debug=b test_all -n | grep 'bdist_wheel'
cd ./env/src && pipenv run python setup.py build bdist_wheel --universal
cd ./env/src && pipenv run python setup.py build bdist_wheel --universal

# CI would rebuild Python, .NET etc 3 times.
```

After:
```
make --debug=b TEST_ALL_DEPS= test_all -n | grep 'bdist_wheel'
```

With the extra magic flag test_all does not depend on build/install, which happened in the previous install_all step.

This shaves off a few minutes from the build time. Will not notice on 1:30 builds but once we get builds to 30 min, 3 min will be 10% which is noticeable.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by pgavlin** [comment]
> since CI runs install_all before test_all, to avoid triple-building-and-installing.

Why not just have CI run `test_all`?

**Comment by t0yv0** [comment]
test_all still builds everything twice on master.

**Review by komalali — APPROVED** [review]
Clever. I'm down to give it a try 👍🏽 🤞🏽

**Comment by t0yv0** [comment]
Credit to https://stackoverflow.com/questions/50633083/makefile-ignore-dependency-when-running-target

Thanks. I'm going to check this in as I'm pretty confident it shouldn't break anything existing. We can always back out.

**Pull request merged**
