### PR TITLE
Marshal non-string provider config

### PR DESCRIPTION
**Pull request by EvanBoyle**
https://github.com/pulumi/pulumi-azure/issues/461

cc @stack72

### CODE REVIEW

**Comment by stack72** [comment]
@EvanBoyle this is great - have you generated a provider ask against this change to see what comes out?

**Comment by EvanBoyle** [comment]
@stack72 this is @pgavlin's change, I just tested it with a minimal repro:

```go
package main

import (
	"github.com/pulumi/pulumi-azure/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, _ = azure.NewProvider(ctx, "peering-provider", &azure.ProviderArgs{
			SubscriptionId: pulumi.String("foo12"),
		})

		return nil
	})
}
```

It works!:

```
Updating (dev):
     Type                         Name              Status      
     pulumi:pulumi:Stack          go_az_qs-dev                  
 +   ├─ pulumi:providers:azure    peering-provider  created
```

**Comment by EvanBoyle** [comment]
and to be clear this isn't a change in the codegen, just in the way we unmarshall onto the wire in the engine, which means we don't have to regenerate any of the SDKs.

**Comment by stack72** [comment]
@EvanBoyle theres a similar bug in Pulumi Vault - can you see if this would fix that as well? It’s about provider config not being strings in the Go sdk

**Comment by pgavlin** [comment]
> theres a similar bug in Pulumi Vault - can you see if this would fix that as well? It’s about provider config not being strings in the Go sdk

This would fix that as well, yes. The error described in that bug is issued by the engine; these changes move the marshaling of non-string config into the engine itself.

**Comment by stack72** [comment]
Awesome! So we can have whatever values feel sensible in the providers and the engineer takes care of it?

**Comment by elsesiy** [comment]
@EvanBoyle The changelog for `1.11.1` seems incomplete as it doesn't mention this.

**Pull request merged**
