### PR TITLE
chore: WriteString(Sprintf(..)) => Fprintf(..)

### PR DESCRIPTION
**Pull request by abhinav**
Replace `buffer.WriteString(fmt.Sprintf(..))` calls,
where buffer is one of `bytes.Buffer`, `strings.Builder`, or `bufio.Writer`,
with equivalent `fmt.Fprintf` calls -- all those types are io.Writers.

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12268** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12268" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12268?utm_source=stack-comment).

**Review by justinvp — APPROVED** [review]

**Comment by abhinav** [comment]
!rebase

**Comment by abhinav** [comment]
Landing because this was green minus downstream codegen, which it doesn't actually change.
(Build above was canceled because workers were locked up yesterday.)

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
CI passed on merge. Failed during sign step:
https://github.com/pulumi/pulumi/actions/runs/4317693740/jobs/7535863162

**Pull request merged**
