### PR TITLE
chore: Update gocloud.dev, removing azure-sdk-for-go dep

### PR DESCRIPTION
**Pull request by AaronFriel**
Having previously made a pull request removing azure-sdk-for-go as a dependency of gocloud.dev, this PR updates the CLI to remove the transitive dependency.

Removing the dependency on azure-sdk-for-go reduces module cache weight by 492MiB. That's the apparent size of `~/go/pkg/mod/github.com/!azure` according to a disk usage utility.

This makes the new largest targets for reducing size:

```
258 MiB google.golang.org/api@v0.103.0
        - required by
250 MiB github.com/aws/aws-sdk-go@v1.44.151
        - required by pulumi/pkg/operations, an experimental function, not used
 83 MiB github.com/pierrec/lz4@v2.6.1+incompatible
        - required by gocloud.dev/secrets/hashivault
 25 MiB github.com/pulumi/pulumi-java
...
```

Returns rapidly diminish with most packages weighing under 1MiB after these.

Follow up work
==============

I've made an upstream issue with gocloud.dev to migrate off aws-sdk-go@v1:
- https://github.com/google/go-cloud/issues/3220

Moving storage backends to plugins would allow us to remove this and many other dependencies from the Pulumi CLI repository and remove conflicts between the Pulumi engine and providers. See:
- https://github.com/pulumi/pulumi-vault/issues/197

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
@pulumi/platform heads up, bors merge succeeded but GitHub appears to have glitched out. This commit is part of the master branch but GH has not auto-closed the PR yet as merged.

It's GitHub, not bors, that triggers that step, so we may have a partial GitHub outage on top of a Slack outage.

**Review by abhinav — APPROVED** [review]

**Comment by RobbieMcKinstry** [comment]
Seeing as the merge was complete, I'm going to review the stacked PRs 👍🏻

**Comment by AaronFriel** [comment]
Closing this PR as it did merge. Strange behavior from GitHub here.

**Pull request closed without merging**
