### PR TITLE
Replace macos-latest with macos-11

### PR DESCRIPTION
**Pull request by Frassle**
# Description

GitHub are rolling out macos 12 for the -latest image (https://github.com/actions/runner-images/issues/6384), but we need to continue to support and build for macos 11.

Fixes https://github.com/pulumi/pulumi/issues/11152

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Frassle** [comment]
bors merge

**Comment by Frassle** [comment]
bors retry

**Comment by Frassle** [comment]
bors retry

**Comment by directionless** [comment]
I know this is an old ticket, and you've probably figured out several ways to handle this, but I wanted to leave a note for future people. macOS does allow builds to target older platforms. In this case, if you export the environmental variable `MACOSX_DEPLOYMENT_TARGET` set to `11`, it should behave as you want.

**Pull request merged**
