### PR TITLE
Adding enum container types support for go codegen

### PR DESCRIPTION
**Pull request by viveklak**
Fixes https://github.com/pulumi/pulumi/issues/6298 (resulting in https://github.com/pulumi/pulumi-azure-nextgen/issues/300)

### CODE REVIEW

**Comment by lblackstone** [comment]
@viveklak Is this RFR, or are you still working on it?

**Comment by viveklak** [comment]
> @viveklak Is this RFR, or are you still working on it?

RFR!

**Review by lblackstone — APPROVED** [review]

**Review by komalali — APPROVED** [review]
I gotta say, I've really enjoyed the evolution of this plant test example.

**Comment by viveklak** [comment]
> I gotta say, I've really enjoyed the evolution of this plant test example.

Everything I know about rubber trees, I learnt from that example :)!

**Pull request merged**
